import { PERMISSION_CODES } from "@/modules/authorization/constants/permissions";

/** Menu permission aliases mapped to platform authorization codes. */
export const MENU_PERMISSIONS = {
  MENU_READ: PERMISSION_CODES.MENU_VIEW,
  MENU_CREATE: PERMISSION_CODES.MENU_CREATE,
  MENU_UPDATE: PERMISSION_CODES.MENU_UPDATE,
  MENU_DELETE: PERMISSION_CODES.MENU_DELETE,
  MENU_IMPORT: PERMISSION_CODES.PRODUCT_IMPORT,
  MENU_EXPORT: PERMISSION_CODES.PRODUCT_EXPORT,
  MENU_PUBLISH: PERMISSION_CODES.MENU_PUBLISH,
  MENU_MANAGE: PERMISSION_CODES.MENU_UPDATE,
} as const;

export type MenuPermissionCode = (typeof MENU_PERMISSIONS)[keyof typeof MENU_PERMISSIONS];
