export const PERMISSION_CODES = {
  DASHBOARD_VIEW: "dashboard.view",
  BUSINESS_VIEW: "business.view",
  BUSINESS_UPDATE: "business.update",
  STAFF_VIEW: "staff.view",
  STAFF_CREATE: "staff.create",
  STAFF_UPDATE: "staff.update",
  STAFF_DELETE: "staff.delete",
  STAFF_ASSIGN_ROLE: "staff.assign_role",
  STAFF_ASSIGN_BRANCH: "staff.assign_branch",
  ROLES_VIEW: "roles.view",
  ROLES_CREATE: "roles.create",
  ROLES_UPDATE: "roles.update",
  ROLES_DELETE: "roles.delete",
  ROLES_MANAGE: "roles.manage",
  MODULES_VIEW: "modules.view",
  MODULES_INSTALL: "modules.install",
  MODULES_ENABLE: "modules.enable",
  MODULES_DISABLE: "modules.disable",
  MODULES_MANAGE: "modules.manage",
  RESTAURANT_VIEW: "restaurant.view",
  RESTAURANT_UPDATE: "restaurant.update",
  RESTAURANT_BRANDING: "restaurant.branding",
  RESTAURANT_SETTINGS: "restaurant.settings",
  MENU_VIEW: "menu.view",
  MENU_CREATE: "menu.create",
  MENU_UPDATE: "menu.update",
  MENU_DELETE: "menu.delete",
  MENU_PUBLISH: "menu.publish",
  CATEGORY_VIEW: "category.view",
  CATEGORY_CREATE: "category.create",
  CATEGORY_UPDATE: "category.update",
  CATEGORY_DELETE: "category.delete",
  CATEGORY_PUBLISH: "category.publish",
  PRODUCT_VIEW: "product.view",
  PRODUCT_CREATE: "product.create",
  PRODUCT_UPDATE: "product.update",
  PRODUCT_DELETE: "product.delete",
  PRODUCT_PUBLISH: "product.publish",
  PRODUCT_IMPORT: "product.import",
  PRODUCT_EXPORT: "product.export",
  MODIFIER_VIEW: "modifier.view",
  MODIFIER_CREATE: "modifier.create",
  MODIFIER_UPDATE: "modifier.update",
  MODIFIER_DELETE: "modifier.delete",
  MODIFIER_ASSIGN: "modifier.assign",
  RESERVATION_VIEW: "reservation.view",
  RESERVATION_CREATE: "reservation.create",
  RESERVATION_UPDATE: "reservation.update",
  RESERVATION_DELETE: "reservation.delete",
  RESERVATION_CANCEL: "reservation.cancel",
  RESERVATION_ASSIGN_TABLE: "reservation.assign_table",
  RESERVATION_ASSIGN_STAFF: "reservation.assign_staff",
  RESERVATION_MANAGE: "reservation.manage",
  FLOOR_VIEW: "floor.view",
  FLOOR_CREATE: "floor.create",
  FLOOR_UPDATE: "floor.update",
  FLOOR_DELETE: "floor.delete",
  TABLE_VIEW: "table.view",
  TABLE_CREATE: "table.create",
  TABLE_UPDATE: "table.update",
  TABLE_DELETE: "table.delete",
  TABLE_MANAGE: "table.manage",
  QR_MANAGE: "qr.manage",
  QR_VIEW: "qr.view",
  QR_CREATE: "qr.create",
  QR_UPDATE: "qr.update",
  QR_DELETE: "qr.delete",
  QR_GENERATE: "qr.generate",
  CART_MANAGE: "cart.manage",
  ORDER_VIEW: "order.view",
  ORDER_CREATE: "order.create",
  ORDER_UPDATE: "order.update",
  ORDER_DELETE: "order.delete",
  ORDER_CANCEL: "order.cancel",
  ORDER_DISCOUNT: "order.discount",
  ORDER_TRANSFER: "order.transfer",
  KITCHEN_VIEW: "kitchen.view",
  KITCHEN_UPDATE: "kitchen.update",
  KITCHEN_ASSIGN_STATION: "kitchen.assign_station",
  KITCHEN_MANAGE: "kitchen.manage",
  POS_USE: "pos.use",
  PAYMENT_VIEW: "payment.view",
  PAYMENT_CREATE: "payment.create",
  PAYMENT_REFUND: "payment.refund",
  PAYMENT_VOID: "payment.void",
  RECEIPT_VIEW: "receipt.view",
  RECEIPT_PRINT: "receipt.print",
  RECEIPT_EMAIL: "receipt.email",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_CREATE: "inventory.create",
  INVENTORY_UPDATE: "inventory.update",
  INVENTORY_DELETE: "inventory.delete",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_MANAGE: "inventory.manage",
  SUPPLIER_VIEW: "supplier.view",
  SUPPLIER_CREATE: "supplier.create",
  SUPPLIER_UPDATE: "supplier.update",
  PURCHASE_ORDER_VIEW: "purchase_order.view",
  PURCHASE_ORDER_CREATE: "purchase_order.create",
  PURCHASE_ORDER_RECEIVE: "purchase_order.receive",
  RECIPE_MANAGE: "recipe.manage",
  CRM_VIEW: "crm.view",
  CRM_MANAGE: "crm.manage",
  CUSTOMER_VIEW: "customer.view",
  CUSTOMER_CREATE: "customer.create",
  CUSTOMER_UPDATE: "customer.update",
  CUSTOMER_DELETE: "customer.delete",
  CUSTOMER_IMPORT: "customer.import",
  CUSTOMER_EXPORT: "customer.export",
  LOYALTY_VIEW: "loyalty.view",
  LOYALTY_MANAGE: "loyalty.manage",
  ANALYTICS_VIEW: "analytics.view",
  ANALYTICS_EXPORT: "analytics.export",
  ANALYTICS_CREATE_REPORT: "analytics.create_report",
  ANALYTICS_EDIT_REPORT: "analytics.edit_report",
  ANALYTICS_DELETE_REPORT: "analytics.delete_report",
  DASHBOARD_MANAGE: "dashboard.manage",
  BRANCH_VIEW: "branch.view",
  BRANCH_CREATE: "branch.create",
  BRANCH_UPDATE: "branch.update",
  BRANCH_DELETE: "branch.delete",
  BRANCH_SETTINGS: "branch.settings",
  BRANCH_MANAGE: "branch.manage",
  BRANCH_ACCESS: "branch.access",
  COMMERCIAL_VIEW: "commercial.view",
  COMMERCIAL_CREATE: "commercial.create",
  COMMERCIAL_UPDATE: "commercial.update",
  COMMERCIAL_ARCHIVE: "commercial.archive",
  COMMERCIAL_MANAGE_PRICES: "commercial.manage_prices",
  COMMERCIAL_MANAGE_BUNDLES: "commercial.manage_bundles",
  SALES_VIEW: "sales.view",
  SALES_CREATE: "sales.create",
  SALES_UPDATE: "sales.update",
  SALES_MANAGE: "sales.manage",
  QUOTES_VIEW: "quotes.view",
  QUOTES_CREATE: "quotes.create",
  QUOTES_EDIT: "quotes.edit",
  QUOTES_SEND: "quotes.send",
  QUOTES_APPROVE: "quotes.approve",
  QUOTES_ACCEPT: "quotes.accept",
  PROPOSALS_MANAGE: "proposals.manage",
  CONTRACTS_VIEW: "contracts.view",
  CONTRACTS_CREATE: "contracts.create",
  CONTRACTS_EDIT: "contracts.edit",
  CONTRACTS_APPROVE: "contracts.approve",
  CONTRACTS_ACTIVATE: "contracts.activate",
  CONTRACTS_ARCHIVE: "contracts.archive",
  CLAUSES_MANAGE: "clauses.manage",
  IMPLEMENTATION_VIEW: "implementation.view",
  IMPLEMENTATION_MANAGE: "implementation.manage",
  IMPLEMENTATION_ASSIGN: "implementation.assign",
  IMPLEMENTATION_COMPLETE: "implementation.complete",
  IMPLEMENTATION_APPROVE: "implementation.approve",
  IMPLEMENTATION_CLOSE: "implementation.close",
  SUCCESS_VIEW: "success.view",
  SUCCESS_MANAGE: "success.manage",
  SUCCESS_ASSIGN: "success.assign",
  SUCCESS_REVIEW: "success.review",
  SUCCESS_RENEW: "success.renew",
  SUCCESS_EXPAND: "success.expand",
  REVENUE_VIEW: "revenue.view",
  REVENUE_MANAGE: "revenue.manage",
  INVOICES_MANAGE: "invoices.manage",
  REVOPS_PAYMENTS_MANAGE: "payments.manage",
  EXPENSES_MANAGE: "expenses.manage",
  FORECASTING_VIEW: "forecasting.view",
  AI_TOOL_EXECUTE: "ai.tool.execute",
  AI_VIEW: "ai.view",
  AI_USE: "ai.use",
  AI_CHAT: "ai.chat",
  AI_RECOMMENDATION_VIEW: "ai.recommendation.view",
  AI_RECOMMENDATION_MANAGE: "ai.recommendation.manage",
  AI_TOOL_REGISTER: "ai.tool.register",
  AI_TOOL_DISABLE: "ai.tool.disable",
  AI_TOOL_ADMIN: "ai.tool.admin",
  AI_KNOWLEDGE_VIEW: "ai.knowledge.view",
  AI_KNOWLEDGE_UPLOAD: "ai.knowledge.upload",
  AI_KNOWLEDGE_EDIT: "ai.knowledge.edit",
  AI_KNOWLEDGE_DELETE: "ai.knowledge.delete",
  AI_KNOWLEDGE_ADMIN: "ai.knowledge.admin",
  AI_AUTOMATION_VIEW: "ai.automation.view",
  AI_AUTOMATION_CREATE: "ai.automation.create",
  AI_AUTOMATION_EDIT: "ai.automation.edit",
  AI_AUTOMATION_DELETE: "ai.automation.delete",
  AI_AUTOMATION_ADMIN: "ai.automation.admin",
  AI_AUTOMATION_EXECUTE: "ai.automation.execute",
  AI_AUTOMATION_APPROVE: "ai.automation.approve",
  AI_AGENT_VIEW: "ai.agent.view",
  AI_AGENT_CREATE: "ai.agent.create",
  AI_AGENT_EDIT: "ai.agent.edit",
  AI_AGENT_UPDATE: "ai.agent.update",
  AI_AGENT_DELETE: "ai.agent.delete",
  AI_AGENT_EXECUTE: "ai.agent.execute",
  AI_AGENT_DEPLOY: "ai.agent.deploy",
  AI_AGENT_DISABLE: "ai.agent.disable",
  AI_AGENT_ADMIN: "ai.agent.admin",
  AI_MEMORY_VIEW: "ai.memory.view",
  AI_MEMORY_CREATE: "ai.memory.create",
  AI_MEMORY_UPDATE: "ai.memory.update",
  AI_MEMORY_DELETE: "ai.memory.delete",
  AI_SKILL_VIEW: "ai.skill.view",
  AI_SKILL_CREATE: "ai.skill.create",
  AI_SKILL_UPDATE: "ai.skill.update",
  AI_SKILL_DELETE: "ai.skill.delete",
  AI_SKILL_EXECUTE: "ai.skill.execute",
  AI_WORKFLOW_VIEW: "ai.workflow.view",
  AI_WORKFLOW_CREATE: "ai.workflow.create",
  AI_WORKFLOW_UPDATE: "ai.workflow.update",
  AI_WORKFLOW_DELETE: "ai.workflow.delete",
  AI_WORKFLOW_EXECUTE: "ai.workflow.execute",
  AI_SALES_VIEW: "ai.sales.view",
  AI_SALES_EXECUTE: "ai.sales.execute",
  AI_SALES_MANAGE: "ai.sales.manage",
  AI_MARKETING_VIEW: "ai.marketing.view",
  AI_MARKETING_EXECUTE: "ai.marketing.execute",
  AI_MARKETING_MANAGE: "ai.marketing.manage",
  AI_SUPPORT_VIEW: "ai.support.view",
  AI_SUPPORT_EXECUTE: "ai.support.execute",
  AI_SUPPORT_MANAGE: "ai.support.manage",
  AI_HR_VIEW: "ai.hr.view",
  AI_HR_EXECUTE: "ai.hr.execute",
  AI_HR_MANAGE: "ai.hr.manage",
  AI_FINANCE_VIEW: "ai.finance.view",
  AI_FINANCE_EXECUTE: "ai.finance.execute",
  AI_FINANCE_MANAGE: "ai.finance.manage",
  AI_OPERATIONS_VIEW: "ai.operations.view",
  AI_OPERATIONS_EXECUTE: "ai.operations.execute",
  AI_OPERATIONS_MANAGE: "ai.operations.manage",
  ORCHESTRATION_READ: "orchestration.read",
  ORCHESTRATION_PUBLISH: "orchestration.publish",
  ORCHESTRATION_ADMIN: "orchestration.admin",
  ORCHESTRATION_QUEUE: "orchestration.queue",
  AI_VOICE_VIEW: "ai.voice.view",
  AI_VOICE_EXECUTE: "ai.voice.execute",
  AI_VOICE_MANAGE: "ai.voice.manage",
  INTEGRATION_VIEW: "integration.view",
  INTEGRATION_CREATE: "integration.create",
  INTEGRATION_UPDATE: "integration.update",
  INTEGRATION_DELETE: "integration.delete",
  INTEGRATION_MANAGE: "integration.manage",
  AUTOMATION_VIEW: "automation.view",
  AUTOMATION_CREATE: "automation.create",
  AUTOMATION_UPDATE: "automation.update",
  AUTOMATION_DELETE: "automation.delete",
  AUTOMATION_EXECUTE: "automation.execute",
  MARKETPLACE_VIEW: "marketplace.view",
  MARKETPLACE_INSTALL: "marketplace.install",
  MARKETPLACE_UPDATE: "marketplace.update",
  MARKETPLACE_DELETE: "marketplace.delete",
  MARKETPLACE_MANAGE: "marketplace.manage",
  MARKETPLACE_PURCHASE: "marketplace.purchase",
  MARKETPLACE_PUBLISH: "marketplace.publish",
  MARKETPLACE_ADMIN: "marketplace.admin",
  BILLING_VIEW: "billing.view",
  BILLING_UPDATE: "billing.update",
  IAM_VIEW: "iam.view",
  IAM_ADMIN: "iam.admin",
  IAM_MANAGE_SESSIONS: "iam.manage_sessions",
  IAM_MANAGE_API_KEYS: "iam.manage_api_keys",
  IAM_MANAGE_SERVICE_ACCOUNTS: "iam.manage_service_accounts",
  IAM_MANAGE_POLICIES: "iam.manage_policies",
  IAM_MANAGE_IDENTITIES: "iam.manage_identities",
  NOTIFICATIONS_VIEW: "notifications.view",
  NOTIFICATIONS_ADMIN: "notifications.admin",
  NOTIFICATIONS_MANAGE_TEMPLATES: "notifications.manage_templates",
  NOTIFICATIONS_MANAGE_RULES: "notifications.manage_rules",
  NOTIFICATIONS_MANAGE_CHANNELS: "notifications.manage_channels",
  NOTIFICATIONS_MANAGE_PREFERENCES: "notifications.manage_preferences",
  NOTIFICATIONS_PUBLISH: "notifications.publish",
  COMMUNICATION_VIEW: "communication.view",
  COMMUNICATION_CREATE: "communication.create",
  COMMUNICATION_SEND: "communication.send",
  COMMUNICATION_REPLY: "communication.reply",
  COMMUNICATION_ASSIGN: "communication.assign",
  COMMUNICATION_MANAGE: "communication.manage",
  COMMUNICATION_DELETE: "communication.delete",
  COMMUNICATION_ADMIN: "communication.admin",
  DOCUMENT_VIEW: "document.view",
  DOCUMENT_CREATE: "document.create",
  DOCUMENT_UPDATE: "document.update",
  DOCUMENT_DELETE: "document.delete",
  DOCUMENT_EXPORT: "document.export",
  DOCUMENT_MANAGE: "document.manage",
  MEDIA_VIEW: "media.view",
  MEDIA_UPLOAD: "media.upload",
  MEDIA_UPDATE: "media.update",
  MEDIA_DELETE: "media.delete",
  MEDIA_DOWNLOAD: "media.download",
  MEDIA_MANAGE: "media.manage",
  DEVELOPER_VIEW: "developer.view",
  DEVELOPER_CREATE: "developer.create",
  DEVELOPER_UPDATE: "developer.update",
  DEVELOPER_DELETE: "developer.delete",
  DEVELOPER_MANAGE: "developer.manage",
  OBSERVABILITY_VIEW: "observability.view",
  OBSERVABILITY_MANAGE: "observability.manage",
  INCIDENT_MANAGE: "incident.manage",
  LOGS_VIEW: "logs.view",
  ALERTS_MANAGE: "alerts.manage",
  ENTERPRISE_VIEW: "enterprise.view",
  ENTERPRISE_MANAGE: "enterprise.manage",
  ORGANIZATION_MANAGE: "organization.manage",
  IDENTITY_MANAGE: "identity.manage",
  POLICY_MANAGE: "policy.manage",
  CLOUD_VIEW: "cloud.view",
  CLOUD_MANAGE: "cloud.manage",
  SUBSCRIPTION_MANAGE: "subscription.manage",
  TENANT_MANAGE: "tenant.manage",
  PLAN_MANAGE: "plan.manage",
  LICENSE_MANAGE: "license.manage",
  FILES_VIEW: "files.view",
  FILES_UPLOAD: "files.upload",
  FILES_DOWNLOAD: "files.download",
  FILES_EDIT: "files.edit",
  FILES_DELETE: "files.delete",
  FILES_SHARE: "files.share",
  FILES_MANAGE: "files.manage",
  FILES_ADMIN: "files.admin",
  SEARCH_VIEW: "search.view",
  SEARCH_QUERY: "search.query",
  SEARCH_MANAGE_INDEX: "search.manage_index",
  SEARCH_ADMIN: "search.admin",
  SETTINGS_VIEW: "settings.view",
  SETTINGS_EDIT: "settings.edit",
  SETTINGS_MANAGE: "settings.manage",
  SETTINGS_ADMIN: "settings.admin",
  FEATURE_FLAGS_VIEW: "feature_flags.view",
  FEATURE_FLAGS_EVALUATE: "feature_flags.evaluate",
  FEATURE_FLAGS_MANAGE: "feature_flags.manage",
  FEATURE_FLAGS_ADMIN: "feature_flags.admin",
  API_GATEWAY_VIEW: "api_gateway.view",
  API_GATEWAY_INVOKE: "api_gateway.invoke",
  API_GATEWAY_MANAGE: "api_gateway.manage",
  API_GATEWAY_ADMIN: "api_gateway.admin",
  MONITORING_PLATFORM_VIEW: "monitoring_platform.view",
  MONITORING_PLATFORM_MANAGE: "monitoring_platform.manage",
  MONITORING_PLATFORM_ADMIN: "monitoring_platform.admin",
  BACKUP_PLATFORM_VIEW: "backup_platform.view",
  BACKUP_PLATFORM_MANAGE: "backup_platform.manage",
  BACKUP_PLATFORM_ADMIN: "backup_platform.admin",
  LOCALIZATION_PLATFORM_VIEW: "localization_platform.view",
  LOCALIZATION_PLATFORM_MANAGE: "localization_platform.manage",
  LOCALIZATION_PLATFORM_ADMIN: "localization_platform.admin",
  IMPORT_EXPORT_PLATFORM_VIEW: "import_export_platform.view",
  IMPORT_EXPORT_PLATFORM_MANAGE: "import_export_platform.manage",
  IMPORT_EXPORT_PLATFORM_ADMIN: "import_export_platform.admin",
  TENANT_PLATFORM_VIEW: "tenant_platform.view",
  TENANT_PLATFORM_MANAGE: "tenant_platform.manage",
  TENANT_PLATFORM_ADMIN: "tenant_platform.admin",
  CONTROL_CENTER_VIEW: "control_center.view",
  CONTROL_CENTER_ADMIN: "control_center.admin",
  CONTROL_CENTER_TENANTS: "control_center.tenants",
  CONTROL_CENTER_TENANTS_EDIT: "control_center.tenants.edit",
  CONTROL_CENTER_TENANTS_SUSPEND: "control_center.tenants.suspend",
  CONTROL_CENTER_TENANTS_DELETE: "control_center.tenants.delete",
  CONTROL_CENTER_TENANTS_POLICIES: "control_center.tenants.policies",
  CONTROL_CENTER_TENANTS_RESOURCES: "control_center.tenants.resources",
  CONTROL_CENTER_TENANTS_MAINTENANCE: "control_center.tenants.maintenance",
  CONTROL_CENTER_TENANTS_ANALYTICS: "control_center.tenants.analytics",
  CONTROL_CENTER_BUSINESSES: "control_center.businesses",
  CONTROL_CENTER_BUSINESSES_EDIT: "control_center.businesses.edit",
  CONTROL_CENTER_BUSINESSES_SUSPEND: "control_center.businesses.suspend",
  CONTROL_CENTER_BUSINESSES_DELETE: "control_center.businesses.delete",
  CONTROL_CENTER_BUSINESSES_TRANSFER: "control_center.businesses.transfer",
  CONTROL_CENTER_WORKSPACES: "control_center.workspaces",
  CONTROL_CENTER_WORKSPACES_EDIT: "control_center.workspaces.edit",
  CONTROL_CENTER_WORKSPACES_SUSPEND: "control_center.workspaces.suspend",
  CONTROL_CENTER_WORKSPACES_DELETE: "control_center.workspaces.delete",
  CONTROL_CENTER_WORKSPACES_TRANSFER: "control_center.workspaces.transfer",
  CONTROL_CENTER_SUBSCRIPTIONS: "control_center.subscriptions",
  CONTROL_CENTER_BILLING: "control_center.billing",
  CONTROL_CENTER_BILLING_PLANS: "control_center.billing.plans",
  CONTROL_CENTER_BILLING_INVOICES: "control_center.billing.invoices",
  CONTROL_CENTER_BILLING_PAYMENTS: "control_center.billing.payments",
  CONTROL_CENTER_BILLING_REFUNDS: "control_center.billing.refunds",
  CONTROL_CENTER_BILLING_PROMOTIONS: "control_center.billing.promotions",
  CONTROL_CENTER_BILLING_ANALYTICS: "control_center.billing.analytics",
  CONTROL_CENTER_REVENUE: "control_center.revenue",
  CONTROL_CENTER_MARKETPLACE: "control_center.marketplace",
  CONTROL_CENTER_MARKETPLACE_PUBLISHERS: "control_center.marketplace.publishers",
  CONTROL_CENTER_MARKETPLACE_REVIEWS: "control_center.marketplace.reviews",
  CONTROL_CENTER_MARKETPLACE_LICENSES: "control_center.marketplace.licenses",
  CONTROL_CENTER_MARKETPLACE_MODERATION: "control_center.marketplace.moderation",
  CONTROL_CENTER_MARKETPLACE_ANALYTICS: "control_center.marketplace.analytics",
  CONTROL_CENTER_AI: "control_center.ai",
  CONTROL_CENTER_MONITORING: "control_center.monitoring",
  CONTROL_CENTER_MONITORING_LOGS: "control_center.monitoring.logs",
  CONTROL_CENTER_MONITORING_ALERTS: "control_center.monitoring.alerts",
  CONTROL_CENTER_MONITORING_INCIDENTS: "control_center.monitoring.incidents",
  CONTROL_CENTER_MONITORING_INFRASTRUCTURE: "control_center.monitoring.infrastructure",
  CONTROL_CENTER_MONITORING_AI: "control_center.monitoring.ai",
  CONTROL_CENTER_SUPPORT: "control_center.support",
  CONTROL_CENTER_SUPPORT_TICKETS: "control_center.support.tickets",
  CONTROL_CENTER_SUPPORT_INCIDENTS: "control_center.support.incidents",
  CONTROL_CENTER_SUPPORT_KNOWLEDGE: "control_center.support.knowledge",
  CONTROL_CENTER_SUPPORT_ANALYTICS: "control_center.support.analytics",
  CONTROL_CENTER_SUPPORT_SERVICE_STATUS: "control_center.support.service_status",
  CONTROL_CENTER_INCIDENTS: "control_center.incidents",
  CONTROL_CENTER_AUDIT: "control_center.audit",
  CONTROL_CENTER_SETTINGS: "control_center.settings",
  CONTROL_CENTER_MAINTENANCE: "control_center.maintenance",
  CONTROL_CENTER_RELEASES: "control_center.releases",
  CONTROL_CENTER_STAFF: "control_center.staff",
  CONTROL_CENTER_ANALYTICS: "control_center.analytics",
  CONTROL_CENTER_INTELLIGENCE: "control_center.intelligence",
  CONTROL_CENTER_FEATURE_FLAGS: "control_center.feature_flags",
  CONTROL_CENTER_SECURITY: "control_center.security",
  CONTROL_CENTER_SECURITY_SESSIONS: "control_center.security.sessions",
  CONTROL_CENTER_SECURITY_ACCOUNTS: "control_center.security.accounts",
  CONTROL_CENTER_SECURITY_API_KEYS: "control_center.security.api_keys",
  CONTROL_CENTER_SECURITY_EXPORT: "control_center.security.export",
  CONTROL_CENTER_OPERATORS: "control_center.operators",
  CONTROL_CENTER_OPERATORS_EDIT: "control_center.operators.edit",
  CONTROL_CENTER_OPERATORS_CREATE: "control_center.operators.create",
  CONTROL_CENTER_OPERATORS_DELETE: "control_center.operators.delete",
  CONTROL_CENTER_OPERATORS_SUSPEND: "control_center.operators.suspend",
  CONTROL_CENTER_OPERATORS_ROLES: "control_center.operators.roles",
  CONTROL_CENTER_OPERATORS_PERMISSIONS: "control_center.operators.permissions",
  CONTROL_CENTER_CEO: "control_center.ceo",
  CONTROL_CENTER_AUTOMATION: "control_center.automation",
  CONTROL_CENTER_AUTOMATION_CREATE: "control_center.automation.create",
  CONTROL_CENTER_AUTOMATION_EDIT: "control_center.automation.edit",
  CONTROL_CENTER_AUTOMATION_DELETE: "control_center.automation.delete",
  CONTROL_CENTER_AUTOMATION_EXECUTE: "control_center.automation.execute",
  CONTROL_CENTER_AUTOMATION_EXPORT: "control_center.automation.export",
  CONTROL_CENTER_AUTOMATION_EMERGENCY_STOP: "control_center.automation.emergency_stop",
} as const;

export const ALL_PERMISSION_CODES = Object.values(PERMISSION_CODES);

export const PERMISSION_MODULES = [
  "dashboard",
  "business",
  "staff",
  "roles",
  "modules",
  "restaurant",
  "menu",
  "reservation",
  "table",
  "qr",
  "cart",
  "order",
  "kitchen",
  "pos",
  "payment",
  "receipt",
  "inventory",
  "supplier",
  "purchase_order",
  "crm",
  "customer",
  "loyalty",
  "analytics",
  "branch",
  "billing",
  "commercial",
  "sales",
  "quotes",
  "contracts",
  "implementation",
  "success",
  "revenue",
  "ai",
  "marketplace",
  "integration",
  "automation",
  "iam",
  "notifications",
  "communication",
  "document",
  "media",
  "developer",
  "observability",
  "enterprise",
  "cloud",
  "files",
  "search",
  "settings",
  "feature_flags",
  "api_gateway",
  "monitoring_platform",
  "backup_platform",
  "localization_platform",
  "import_export_platform",
  "tenant_platform",
  "control_center",
  "orchestration",
] as const;

export const AUTHORIZATION_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  BUSINESS_NOT_FOUND: "BUSINESS_NOT_FOUND",
  ONBOARDING_REQUIRED: "ONBOARDING_REQUIRED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
} as const;

export const AUTHORIZATION_ERROR_MESSAGES = {
  [AUTHORIZATION_ERROR_CODES.UNAUTHORIZED]: "Unauthorized",
  [AUTHORIZATION_ERROR_CODES.FORBIDDEN]: "Forbidden",
  [AUTHORIZATION_ERROR_CODES.BUSINESS_NOT_FOUND]: "Business Not Found",
  [AUTHORIZATION_ERROR_CODES.ONBOARDING_REQUIRED]: "Onboarding Required",
  [AUTHORIZATION_ERROR_CODES.PERMISSION_DENIED]: "Permission Denied",
} as const;

export const SYSTEM_ROLE_SLUGS = {
  OWNER: "owner",
  MANAGER: "manager",
  SUPERVISOR: "supervisor",
  CASHIER: "cashier",
  KITCHEN_STAFF: "kitchen-staff",
  WAITER: "waiter",
  ACCOUNTANT: "accountant",
  MARKETING: "marketing",
  SUPPORT: "support",
  CHEF: "chef",
  RECEPTIONIST: "receptionist",
} as const;
