export const PERMISSION_CODES = {
  BUSINESS_VIEW: "business.view",
  BUSINESS_UPDATE: "business.update",
  STAFF_VIEW: "staff.view",
  STAFF_CREATE: "staff.create",
  STAFF_UPDATE: "staff.update",
  STAFF_DELETE: "staff.delete",
  MENU_VIEW: "menu.view",
  MENU_CREATE: "menu.create",
  MENU_UPDATE: "menu.update",
  MENU_DELETE: "menu.delete",
  RESERVATION_VIEW: "reservation.view",
  RESERVATION_MANAGE: "reservation.manage",
  TABLE_MANAGE: "table.manage",
  QR_MANAGE: "qr.manage",
  CART_MANAGE: "cart.manage",
  ORDER_VIEW: "order.view",
  ORDER_CREATE: "order.create",
  ORDER_CANCEL: "order.cancel",
  KITCHEN_VIEW: "kitchen.view",
  KITCHEN_UPDATE: "kitchen.update",
  POS_USE: "pos.use",
  PAYMENT_CREATE: "payment.create",
  PAYMENT_REFUND: "payment.refund",
  RECEIPT_VIEW: "receipt.view",
  RECEIPT_PRINT: "receipt.print",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_MANAGE: "inventory.manage",
  RECIPE_MANAGE: "recipe.manage",
  CRM_VIEW: "crm.view",
  CRM_MANAGE: "crm.manage",
  ANALYTICS_VIEW: "analytics.view",
  BRANCH_VIEW: "branch.view",
  BRANCH_MANAGE: "branch.manage",
  BRANCH_ACCESS: "branch.access",
  COMMERCIAL_VIEW: "commercial.view",
  COMMERCIAL_CREATE: "commercial.create",
  COMMERCIAL_UPDATE: "commercial.update",
  COMMERCIAL_ARCHIVE: "commercial.archive",
  COMMERCIAL_MANAGE_PRICES: "commercial.manage_prices",
  COMMERCIAL_MANAGE_BUNDLES: "commercial.manage_bundles",
  SALES_VIEW: "sales.view",
  SALES_CREATE: "sales.create",
  SALES_UPDATE: "sales.update",
  SALES_MANAGE: "sales.manage",
  QUOTES_VIEW: "quotes.view",
  QUOTES_CREATE: "quotes.create",
  QUOTES_EDIT: "quotes.edit",
  QUOTES_SEND: "quotes.send",
  QUOTES_APPROVE: "quotes.approve",
  QUOTES_ACCEPT: "quotes.accept",
  PROPOSALS_MANAGE: "proposals.manage",
  CONTRACTS_VIEW: "contracts.view",
  CONTRACTS_CREATE: "contracts.create",
  CONTRACTS_EDIT: "contracts.edit",
  CONTRACTS_APPROVE: "contracts.approve",
  CONTRACTS_ACTIVATE: "contracts.activate",
  CONTRACTS_ARCHIVE: "contracts.archive",
  CLAUSES_MANAGE: "clauses.manage",
  IMPLEMENTATION_VIEW: "implementation.view",
  IMPLEMENTATION_MANAGE: "implementation.manage",
  IMPLEMENTATION_ASSIGN: "implementation.assign",
  IMPLEMENTATION_COMPLETE: "implementation.complete",
  IMPLEMENTATION_APPROVE: "implementation.approve",
  IMPLEMENTATION_CLOSE: "implementation.close",
  SUCCESS_VIEW: "success.view",
  SUCCESS_MANAGE: "success.manage",
  SUCCESS_ASSIGN: "success.assign",
  SUCCESS_REVIEW: "success.review",
  SUCCESS_RENEW: "success.renew",
  SUCCESS_EXPAND: "success.expand",
  REVENUE_VIEW: "revenue.view",
  REVENUE_MANAGE: "revenue.manage",
  INVOICES_MANAGE: "invoices.manage",
  REVOPS_PAYMENTS_MANAGE: "payments.manage",
  EXPENSES_MANAGE: "expenses.manage",
  FORECASTING_VIEW: "forecasting.view",
  AI_TOOL_EXECUTE: "ai.tool.execute",
  AI_TOOL_REGISTER: "ai.tool.register",
  AI_TOOL_DISABLE: "ai.tool.disable",
  AI_TOOL_ADMIN: "ai.tool.admin",
  AI_KNOWLEDGE_VIEW: "ai.knowledge.view",
  AI_KNOWLEDGE_UPLOAD: "ai.knowledge.upload",
  AI_KNOWLEDGE_EDIT: "ai.knowledge.edit",
  AI_KNOWLEDGE_DELETE: "ai.knowledge.delete",
  AI_KNOWLEDGE_ADMIN: "ai.knowledge.admin",
  AI_AUTOMATION_VIEW: "ai.automation.view",
  AI_AUTOMATION_CREATE: "ai.automation.create",
  AI_AUTOMATION_EDIT: "ai.automation.edit",
  AI_AUTOMATION_DELETE: "ai.automation.delete",
  AI_AUTOMATION_ADMIN: "ai.automation.admin",
  AI_AUTOMATION_EXECUTE: "ai.automation.execute",
  AI_AUTOMATION_APPROVE: "ai.automation.approve",
  AI_AGENT_VIEW: "ai.agent.view",
  AI_AGENT_CREATE: "ai.agent.create",
  AI_AGENT_EDIT: "ai.agent.edit",
  AI_AGENT_DEPLOY: "ai.agent.deploy",
  AI_AGENT_DISABLE: "ai.agent.disable",
  AI_AGENT_ADMIN: "ai.agent.admin",
  MARKETPLACE_VIEW: "marketplace.view",
  MARKETPLACE_INSTALL: "marketplace.install",
  MARKETPLACE_PURCHASE: "marketplace.purchase",
  MARKETPLACE_PUBLISH: "marketplace.publish",
  MARKETPLACE_ADMIN: "marketplace.admin",
  IAM_VIEW: "iam.view",
  IAM_ADMIN: "iam.admin",
  IAM_MANAGE_SESSIONS: "iam.manage_sessions",
  IAM_MANAGE_API_KEYS: "iam.manage_api_keys",
  IAM_MANAGE_SERVICE_ACCOUNTS: "iam.manage_service_accounts",
  IAM_MANAGE_POLICIES: "iam.manage_policies",
  IAM_MANAGE_IDENTITIES: "iam.manage_identities",
  NOTIFICATIONS_VIEW: "notifications.view",
  NOTIFICATIONS_ADMIN: "notifications.admin",
  NOTIFICATIONS_MANAGE_TEMPLATES: "notifications.manage_templates",
  NOTIFICATIONS_MANAGE_RULES: "notifications.manage_rules",
  NOTIFICATIONS_MANAGE_CHANNELS: "notifications.manage_channels",
  NOTIFICATIONS_MANAGE_PREFERENCES: "notifications.manage_preferences",
  NOTIFICATIONS_PUBLISH: "notifications.publish",
  COMMUNICATION_VIEW: "communication.view",
  COMMUNICATION_REPLY: "communication.reply",
  COMMUNICATION_ASSIGN: "communication.assign",
  COMMUNICATION_MANAGE: "communication.manage",
  COMMUNICATION_ADMIN: "communication.admin",
  FILES_VIEW: "files.view",
  FILES_UPLOAD: "files.upload",
  FILES_DOWNLOAD: "files.download",
  FILES_EDIT: "files.edit",
  FILES_DELETE: "files.delete",
  FILES_SHARE: "files.share",
  FILES_MANAGE: "files.manage",
  FILES_ADMIN: "files.admin",
  SEARCH_VIEW: "search.view",
  SEARCH_QUERY: "search.query",
  SEARCH_MANAGE_INDEX: "search.manage_index",
  SEARCH_ADMIN: "search.admin",
  SETTINGS_VIEW: "settings.view",
  SETTINGS_EDIT: "settings.edit",
  SETTINGS_MANAGE: "settings.manage",
  SETTINGS_ADMIN: "settings.admin",
  FEATURE_FLAGS_VIEW: "feature_flags.view",
  FEATURE_FLAGS_EVALUATE: "feature_flags.evaluate",
  FEATURE_FLAGS_MANAGE: "feature_flags.manage",
  FEATURE_FLAGS_ADMIN: "feature_flags.admin",
  API_GATEWAY_VIEW: "api_gateway.view",
  API_GATEWAY_INVOKE: "api_gateway.invoke",
  API_GATEWAY_MANAGE: "api_gateway.manage",
  API_GATEWAY_ADMIN: "api_gateway.admin",
  MONITORING_PLATFORM_VIEW: "monitoring_platform.view",
  MONITORING_PLATFORM_MANAGE: "monitoring_platform.manage",
  MONITORING_PLATFORM_ADMIN: "monitoring_platform.admin",
  BACKUP_PLATFORM_VIEW: "backup_platform.view",
  BACKUP_PLATFORM_MANAGE: "backup_platform.manage",
  BACKUP_PLATFORM_ADMIN: "backup_platform.admin",
  LOCALIZATION_PLATFORM_VIEW: "localization_platform.view",
  LOCALIZATION_PLATFORM_MANAGE: "localization_platform.manage",
  LOCALIZATION_PLATFORM_ADMIN: "localization_platform.admin",
  IMPORT_EXPORT_PLATFORM_VIEW: "import_export_platform.view",
  IMPORT_EXPORT_PLATFORM_MANAGE: "import_export_platform.manage",
  IMPORT_EXPORT_PLATFORM_ADMIN: "import_export_platform.admin",
  TENANT_PLATFORM_VIEW: "tenant_platform.view",
  TENANT_PLATFORM_MANAGE: "tenant_platform.manage",
  TENANT_PLATFORM_ADMIN: "tenant_platform.admin",
} as const;

export const ALL_PERMISSION_CODES = Object.values(PERMISSION_CODES);

export const PERMISSION_MODULES = [
  "business",
  "staff",
  "menu",
  "reservation",
  "table",
  "qr",
  "cart",
  "order",
  "kitchen",
  "pos",
  "payment",
  "receipt",
  "inventory",
  "crm",
  "analytics",
  "branch",
  "commercial",
  "sales",
  "quotes",
  "contracts",
  "implementation",
  "success",
  "revenue",
  "ai",
  "marketplace",
  "iam",
  "notifications",
  "communication",
  "files",
  "search",
  "settings",
  "feature_flags",
  "api_gateway",
  "monitoring_platform",
  "backup_platform",
  "localization_platform",
  "import_export_platform",
  "tenant_platform",
] as const;

export const AUTHORIZATION_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  BUSINESS_NOT_FOUND: "BUSINESS_NOT_FOUND",
  ONBOARDING_REQUIRED: "ONBOARDING_REQUIRED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
} as const;

export const AUTHORIZATION_ERROR_MESSAGES = {
  [AUTHORIZATION_ERROR_CODES.UNAUTHORIZED]: "Unauthorized",
  [AUTHORIZATION_ERROR_CODES.FORBIDDEN]: "Forbidden",
  [AUTHORIZATION_ERROR_CODES.BUSINESS_NOT_FOUND]: "Business Not Found",
  [AUTHORIZATION_ERROR_CODES.ONBOARDING_REQUIRED]: "Onboarding Required",
  [AUTHORIZATION_ERROR_CODES.PERMISSION_DENIED]: "Permission Denied",
} as const;

export const SYSTEM_ROLE_SLUGS = {
  OWNER: "owner",
  MANAGER: "manager",
  WAITER: "waiter",
  CHEF: "chef",
} as const;
