import { PERMISSION_CODES } from "@/modules/authorization/constants/permissions";

/** Order management permission aliases mapped to platform authorization codes. */
export const ORDER_MODULE_PERMISSIONS = {
  ORDER_READ: PERMISSION_CODES.ORDER_VIEW,
  ORDER_CREATE: PERMISSION_CODES.ORDER_CREATE,
  ORDER_UPDATE: PERMISSION_CODES.ORDER_UPDATE,
  ORDER_DELETE: PERMISSION_CODES.ORDER_DELETE,
  ORDER_CANCEL: PERMISSION_CODES.ORDER_CANCEL,
  ORDER_REFUND: PERMISSION_CODES.ORDER_CANCEL,
  ORDER_DISCOUNT: PERMISSION_CODES.ORDER_DISCOUNT,
  ORDER_TRANSFER: PERMISSION_CODES.ORDER_TRANSFER,
} as const;

export type OrderModulePermissionCode =
  (typeof ORDER_MODULE_PERMISSIONS)[keyof typeof ORDER_MODULE_PERMISSIONS];
