export const PLATFORM_GUARD_ERROR_CODES = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  BUSINESS_REQUIRED: "BUSINESS_REQUIRED",
  BUSINESS_NOT_ACTIVE: "BUSINESS_NOT_ACTIVE",
  STAFF_INACTIVE: "STAFF_INACTIVE",
  ONBOARDING_REQUIRED: "ONBOARDING_REQUIRED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  ROLE_REQUIRED: "ROLE_REQUIRED",
} as const;

export const PLATFORM_GUARD_ERROR_MESSAGES = {
  [PLATFORM_GUARD_ERROR_CODES.UNAUTHENTICATED]: "Authentication required",
  [PLATFORM_GUARD_ERROR_CODES.BUSINESS_REQUIRED]: "Business context required",
  [PLATFORM_GUARD_ERROR_CODES.BUSINESS_NOT_ACTIVE]: "Business is not active",
  [PLATFORM_GUARD_ERROR_CODES.STAFF_INACTIVE]: "Staff account is inactive",
  [PLATFORM_GUARD_ERROR_CODES.ONBOARDING_REQUIRED]: "Onboarding must be completed",
  [PLATFORM_GUARD_ERROR_CODES.PERMISSION_DENIED]: "Permission denied",
  [PLATFORM_GUARD_ERROR_CODES.ROLE_REQUIRED]: "Required role not assigned",
} as const;
