import {
  API_KEY_STATUSES,
  INTEGRATION_CATEGORIES,
  INTEGRATION_STATUSES,
  LOG_LEVELS,
  OAUTH_STATUSES,
  SYNC_JOB_STATUSES,
  WEBHOOK_EVENT_STATUSES,
  WEBHOOK_STATUSES,
} from "@/modules/integrations/constants/integration-status";
import type { IntegrationRecord } from "@/modules/integrations/types/integration-platform";

export const DEFAULT_INTEGRATION_SCOPE = {
  tenantId: "tenant-harbour",
  workspaceId: "ws-harbour-kitchen",
  businessId: "biz-harbour-kitchen",
  branchId: "branch-harbour-main",
  userId: "user-harbour-owner",
} as const;

const PERIOD_START = "2026-02-01";
const PERIOD_END = "2026-02-28";
const NOW = "2026-02-15T23:00:00.000Z";

export const MOCK_INTEGRATION_RECORD: IntegrationRecord = {
  providers: [
    {
      id: "prov-stripe",
      slug: "stripe",
      name: "Stripe",
      category: INTEGRATION_CATEGORIES.PAYMENT,
      description: "Payment processing and subscriptions",
      logoUrl: null,
      authType: "api_key",
      supportedFeatures: ["payments", "subscriptions", "refunds"],
      isAvailable: true,
      documentationUrl: "https://stripe.com/docs",
    },
    {
      id: "prov-twilio",
      slug: "twilio",
      name: "Twilio",
      category: INTEGRATION_CATEGORIES.SMS,
      description: "SMS and voice communications",
      logoUrl: null,
      authType: "api_key",
      supportedFeatures: ["sms", "voice", "whatsapp"],
      isAvailable: true,
      documentationUrl: "https://twilio.com/docs",
    },
    {
      id: "prov-xero",
      slug: "xero",
      name: "Xero",
      category: INTEGRATION_CATEGORIES.ACCOUNTING,
      description: "Cloud accounting software",
      logoUrl: null,
      authType: "oauth2",
      supportedFeatures: ["invoices", "contacts", "bank_feeds"],
      isAvailable: true,
      documentationUrl: "https://developer.xero.com",
    },
    {
      id: "prov-openai",
      slug: "openai",
      name: "OpenAI",
      category: INTEGRATION_CATEGORIES.AI,
      description: "AI models and completions",
      logoUrl: null,
      authType: "api_key",
      supportedFeatures: ["chat", "embeddings", "fine_tuning"],
      isAvailable: true,
      documentationUrl: "https://platform.openai.com/docs",
    },
    {
      id: "prov-deliveroo",
      slug: "deliveroo",
      name: "Deliveroo",
      category: INTEGRATION_CATEGORIES.DELIVERY,
      description: "Food delivery platform integration",
      logoUrl: null,
      authType: "oauth2",
      supportedFeatures: ["orders", "menu_sync", "availability"],
      isAvailable: true,
      documentationUrl: null,
    },
  ],
  integrations: [
    {
      id: "int-stripe-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      workspaceId: DEFAULT_INTEGRATION_SCOPE.workspaceId,
      businessId: DEFAULT_INTEGRATION_SCOPE.businessId,
      branchId: DEFAULT_INTEGRATION_SCOPE.branchId,
      providerId: "prov-stripe",
      name: "Stripe Payments",
      category: INTEGRATION_CATEGORIES.PAYMENT,
      status: INTEGRATION_STATUSES.CONNECTED,
      externalAccountId: "acct_stripe_001",
      config: { mode: "live" },
      lastSyncAt: NOW,
      connectedAt: "2025-08-01T00:00:00.000Z",
      createdAt: "2025-08-01T00:00:00.000Z",
      updatedAt: NOW,
    },
    {
      id: "int-twilio-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      workspaceId: DEFAULT_INTEGRATION_SCOPE.workspaceId,
      businessId: DEFAULT_INTEGRATION_SCOPE.businessId,
      branchId: DEFAULT_INTEGRATION_SCOPE.branchId,
      providerId: "prov-twilio",
      name: "Twilio SMS",
      category: INTEGRATION_CATEGORIES.SMS,
      status: INTEGRATION_STATUSES.CONNECTED,
      externalAccountId: "twilio_acct_001",
      config: { fromNumber: "+447700900123" },
      lastSyncAt: NOW,
      connectedAt: "2025-09-15T00:00:00.000Z",
      createdAt: "2025-09-15T00:00:00.000Z",
      updatedAt: NOW,
    },
    {
      id: "int-xero-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      workspaceId: DEFAULT_INTEGRATION_SCOPE.workspaceId,
      businessId: DEFAULT_INTEGRATION_SCOPE.businessId,
      branchId: DEFAULT_INTEGRATION_SCOPE.branchId,
      providerId: "prov-xero",
      name: "Xero Accounting",
      category: INTEGRATION_CATEGORIES.ACCOUNTING,
      status: INTEGRATION_STATUSES.ERROR,
      externalAccountId: "xero_org_001",
      config: {},
      lastSyncAt: "2026-02-10T08:00:00.000Z",
      connectedAt: "2025-10-01T00:00:00.000Z",
      createdAt: "2025-10-01T00:00:00.000Z",
      updatedAt: NOW,
    },
  ],
  apiKeys: [
    {
      id: "key-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      businessId: DEFAULT_INTEGRATION_SCOPE.businessId,
      name: "Production API Key",
      keyPrefix: "busal_live_abc1",
      status: API_KEY_STATUSES.ACTIVE,
      scopes: ["orders.read", "menu.read", "pos.write"],
      rateLimitPerHour: 5000,
      expiresAt: null,
      lastUsedAt: NOW,
      createdByUserId: DEFAULT_INTEGRATION_SCOPE.userId,
      createdAt: "2025-08-01T00:00:00.000Z",
    },
    {
      id: "key-002",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      businessId: DEFAULT_INTEGRATION_SCOPE.businessId,
      name: "Development API Key",
      keyPrefix: "busal_test_xyz9",
      status: API_KEY_STATUSES.ACTIVE,
      scopes: ["orders.read", "menu.read"],
      rateLimitPerHour: 1000,
      expiresAt: "2026-12-31T23:59:59.000Z",
      lastUsedAt: "2026-02-14T10:00:00.000Z",
      createdByUserId: DEFAULT_INTEGRATION_SCOPE.userId,
      createdAt: "2025-11-01T00:00:00.000Z",
    },
  ],
  webhooks: [
    {
      id: "wh-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      businessId: DEFAULT_INTEGRATION_SCOPE.businessId,
      name: "Order Events",
      url: "https://api.partner.com/webhooks/orders",
      status: WEBHOOK_STATUSES.ACTIVE,
      secret: "whsec_mock_001",
      eventTypes: ["order.created", "order.completed", "order.cancelled"],
      retryPolicy: { maxRetries: 3, backoffMs: 5000 },
      isActive: true,
      createdAt: "2025-08-01T00:00:00.000Z",
      updatedAt: NOW,
    },
    {
      id: "wh-002",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      businessId: DEFAULT_INTEGRATION_SCOPE.businessId,
      name: "Inventory Alerts",
      url: "https://api.partner.com/webhooks/inventory",
      status: WEBHOOK_STATUSES.FAILED,
      secret: "whsec_mock_002",
      eventTypes: ["inventory.low_stock"],
      retryPolicy: { maxRetries: 5, backoffMs: 10000 },
      isActive: true,
      createdAt: "2025-09-01T00:00:00.000Z",
      updatedAt: NOW,
    },
  ],
  webhookEndpoints: [
    {
      id: "whe-stripe",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      integrationId: "int-stripe-001",
      path: "/webhooks/stripe",
      method: "POST",
      providerSlug: "stripe",
      isVerified: true,
      verificationToken: "stripe_wh_verify_001",
      createdAt: "2025-08-01T00:00:00.000Z",
    },
  ],
  webhookEvents: [
    {
      id: "wevt-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      webhookId: "wh-001",
      eventType: "order.completed",
      payload: { orderId: "ord-1234", totalCents: 4250 },
      status: WEBHOOK_EVENT_STATUSES.DELIVERED,
      attemptCount: 1,
      responseStatusCode: 200,
      responseBody: '{"received":true}',
      deliveredAt: "2026-02-15T18:05:00.000Z",
      nextRetryAt: null,
      createdAt: "2026-02-15T18:00:00.000Z",
    },
    {
      id: "wevt-002",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      webhookId: "wh-002",
      eventType: "inventory.low_stock",
      payload: { itemId: "inv-001", stockLevel: 2 },
      status: WEBHOOK_EVENT_STATUSES.FAILED,
      attemptCount: 3,
      responseStatusCode: 503,
      responseBody: "Service Unavailable",
      deliveredAt: null,
      nextRetryAt: "2026-02-15T23:30:00.000Z",
      createdAt: "2026-02-15T14:00:00.000Z",
    },
    {
      id: "wevt-003",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      webhookId: "wh-002",
      eventType: "inventory.low_stock",
      payload: { itemId: "inv-002", stockLevel: 1 },
      status: WEBHOOK_EVENT_STATUSES.RETRYING,
      attemptCount: 2,
      responseStatusCode: 500,
      responseBody: "Internal Server Error",
      deliveredAt: null,
      nextRetryAt: NOW,
      createdAt: "2026-02-15T16:00:00.000Z",
    },
  ],
  oauthConnections: [
    {
      id: "oauth-xero-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      businessId: DEFAULT_INTEGRATION_SCOPE.businessId,
      providerId: "prov-xero",
      providerSlug: "xero",
      status: OAUTH_STATUSES.EXPIRED,
      accessTokenExpiresAt: "2026-02-01T00:00:00.000Z",
      refreshTokenExpiresAt: "2026-08-01T00:00:00.000Z",
      scopes: ["accounting.transactions", "accounting.contacts"],
      authorizedAt: "2025-10-01T00:00:00.000Z",
      revokedAt: null,
    },
  ],
  externalAccounts: [
    {
      id: "ext-stripe-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      integrationId: "int-stripe-001",
      providerSlug: "stripe",
      externalId: "acct_stripe_001",
      displayName: "Harbour Kitchen Ltd",
      email: "owner@harbourkitchen.co.uk",
      metadata: { country: "GB", currency: "GBP" },
      linkedAt: "2025-08-01T00:00:00.000Z",
    },
  ],
  syncJobs: [
    {
      id: "sync-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      integrationId: "int-xero-001",
      jobType: "invoice_export",
      status: SYNC_JOB_STATUSES.FAILED,
      direction: "export",
      recordsProcessed: 45,
      recordsFailed: 3,
      startedAt: "2026-02-10T08:00:00.000Z",
      completedAt: "2026-02-10T08:15:00.000Z",
      errorMessage: "OAuth token expired",
      createdAt: "2026-02-10T08:00:00.000Z",
    },
    {
      id: "sync-002",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      integrationId: "int-stripe-001",
      jobType: "payment_import",
      status: SYNC_JOB_STATUSES.COMPLETED,
      direction: "import",
      recordsProcessed: 128,
      recordsFailed: 0,
      startedAt: "2026-02-15T06:00:00.000Z",
      completedAt: "2026-02-15T06:05:00.000Z",
      errorMessage: null,
      createdAt: "2026-02-15T06:00:00.000Z",
    },
  ],
  mappings: [
    {
      id: "map-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      integrationId: "int-xero-001",
      sourceEntity: "finance.invoice",
      targetEntity: "xero.invoice",
      fieldMappings: [
        { sourceField: "invoiceNumber", targetField: "InvoiceNumber", transform: null },
        { sourceField: "totalCents", targetField: "Total", transform: "cents_to_decimal" },
        { sourceField: "customerName", targetField: "Contact.Name", transform: null },
      ],
      isActive: true,
      createdAt: "2025-10-01T00:00:00.000Z",
      updatedAt: NOW,
    },
  ],
  logs: [
    {
      id: "log-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      integrationId: "int-stripe-001",
      level: LOG_LEVELS.INFO,
      action: "webhook.received",
      message: "Stripe payment_intent.succeeded received",
      metadata: { eventId: "evt_stripe_001" },
      occurredAt: NOW,
    },
    {
      id: "log-002",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      integrationId: "int-xero-001",
      level: LOG_LEVELS.ERROR,
      action: "sync.failed",
      message: "Invoice export failed — OAuth token expired",
      metadata: { jobId: "sync-001" },
      occurredAt: "2026-02-10T08:15:00.000Z",
    },
    {
      id: "log-003",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      integrationId: "int-twilio-001",
      level: LOG_LEVELS.WARN,
      action: "sms.rate_limited",
      message: "SMS rate limit approaching threshold",
      metadata: { currentRate: "85", limit: "100" },
      occurredAt: "2026-02-15T12:00:00.000Z",
    },
  ],
  apiClients: [
    {
      id: "client-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      name: "Harbour POS Terminal",
      clientId: "busal_client_pos_001",
      redirectUris: ["https://pos.harbourkitchen.co.uk/callback"],
      scopes: ["read", "write"],
      isActive: true,
      createdAt: "2025-08-01T00:00:00.000Z",
    },
  ],
  apiRequests: [
    {
      id: "req-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      apiKeyId: "key-001",
      clientId: null,
      method: "GET",
      path: "/api/v1/orders",
      statusCode: 200,
      durationMs: 45,
      ipAddress: "192.168.1.10",
      userAgent: "BusalPOS/1.0",
      requestedAt: NOW,
    },
    {
      id: "req-002",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      apiKeyId: "key-001",
      clientId: null,
      method: "POST",
      path: "/api/v1/orders",
      statusCode: 429,
      durationMs: 12,
      ipAddress: "192.168.1.10",
      userAgent: "BusalPOS/1.0",
      requestedAt: NOW,
    },
  ],
  apiResponses: [
    {
      id: "res-001",
      requestId: "req-001",
      statusCode: 200,
      bodySizeBytes: 2048,
      headers: { "content-type": "application/json" },
      errorCode: null,
      errorMessage: null,
      respondedAt: NOW,
    },
    {
      id: "res-002",
      requestId: "req-002",
      statusCode: 429,
      bodySizeBytes: 128,
      headers: { "content-type": "application/json", "retry-after": "60" },
      errorCode: "rate_limit_exceeded",
      errorMessage: "Rate limit exceeded. Retry after 60 seconds.",
      respondedAt: NOW,
    },
  ],
  rateLimits: [
    {
      id: "rl-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      apiKeyId: "key-001",
      endpoint: "/api/v1/*",
      limitPerHour: 5000,
      limitPerDay: 50000,
      burstLimit: 100,
      isActive: true,
    },
    {
      id: "rl-002",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      apiKeyId: "key-002",
      endpoint: "/api/v1/*",
      limitPerHour: 1000,
      limitPerDay: 10000,
      burstLimit: 50,
      isActive: true,
    },
  ],
  apiUsage: [
    {
      id: "usage-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      apiKeyId: "key-001",
      endpoint: "/api/v1/orders",
      requestCount: 8420,
      errorCount: 42,
      averageLatencyMs: 52,
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
    },
    {
      id: "usage-002",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      apiKeyId: "key-001",
      endpoint: "/api/v1/menu",
      requestCount: 3210,
      errorCount: 8,
      averageLatencyMs: 38,
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
    },
  ],
  developerApplications: [
    {
      id: "devapp-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      name: "Harbour Analytics Dashboard",
      description: "Custom analytics dashboard for Harbour Kitchen",
      clientId: "busal_dev_analytics_001",
      webhookUrl: "https://analytics.harbourkitchen.co.uk/webhook",
      scopes: ["read"],
      isPublished: false,
      createdByUserId: DEFAULT_INTEGRATION_SCOPE.userId,
      createdAt: "2025-12-01T00:00:00.000Z",
      updatedAt: NOW,
    },
  ],
  developerTokens: [
    {
      id: "devtok-001",
      tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
      applicationId: "devapp-001",
      tokenPrefix: "busal_dev_tok_abc",
      scopes: ["read"],
      expiresAt: "2026-08-01T00:00:00.000Z",
      lastUsedAt: "2026-02-14T15:00:00.000Z",
      isRevoked: false,
      createdAt: "2025-12-01T00:00:00.000Z",
    },
  ],
  developerAnalytics: {
    tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
    totalApplications: 1,
    activeApiKeys: 2,
    totalRequests: 11630,
    errorRateBps: 430,
    averageLatencyMs: 47,
    topEndpoints: [
      { path: "/api/v1/orders", count: 8420 },
      { path: "/api/v1/menu", count: 3210 },
    ],
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  aiContext: {
    tenantId: DEFAULT_INTEGRATION_SCOPE.tenantId,
    summary: "3 integrations connected — 2 active webhooks, 1 failed",
    connectedCount: 2,
    failedWebhookCount: 1,
    recommendedProviderId: "prov-deliveroo",
    insights: [
      "Xero OAuth token expired — re-authorization required",
      "Inventory webhook failing with 503 errors",
      "API error rate at 4.3% — within acceptable range",
    ],
    recommendedActions: [
      "Re-authorize Xero OAuth connection",
      "Investigate inventory webhook endpoint availability",
      "Consider Deliveroo integration for delivery orders",
    ],
    lastGeneratedAt: NOW,
  },
};
