import { TOOL_CATEGORIES } from "@/modules/ai/constants/tool-categories";
import type { RegisteredAiTool } from "@/modules/ai/types/tool";

function mockHandler(output: string): RegisteredAiTool["handler"] {
  return () => ({
    toolSlug: "",
    success: true,
    output,
    metadata: { source: "mock" },
  });
}

export const BUILTIN_TOOLS: RegisteredAiTool[] = [
  {
    id: "tool-crm-lookup",
    slug: "crm.lookup-customer",
    name: "Lookup Customer",
    description: "Retrieve customer profile and recent activity.",
    category: TOOL_CATEGORIES.CRM,
    inputSchema: { customerId: "string" },
    isEnabled: true,
    handler: mockHandler("Customer profile loaded from mock CRM store."),
  },
  {
    id: "tool-crm-lead",
    slug: "crm.create-lead",
    name: "Create Lead",
    description: "Create a new sales lead in CRM.",
    category: TOOL_CATEGORIES.CRM,
    inputSchema: { name: "string", email: "string" },
    isEnabled: true,
    handler: mockHandler("Lead created in mock CRM pipeline."),
  },
  {
    id: "tool-pos-order",
    slug: "pos.order-status",
    name: "Order Status",
    description: "Check POS order status.",
    category: TOOL_CATEGORIES.POS,
    inputSchema: { orderId: "string" },
    isEnabled: true,
    handler: mockHandler("Order status: in preparation (mock)."),
  },
  {
    id: "tool-pos-table",
    slug: "pos.table-status",
    name: "Table Status",
    description: "Check table availability in POS.",
    category: TOOL_CATEGORIES.POS,
    inputSchema: { tableId: "string" },
    isEnabled: true,
    handler: mockHandler("Table available (mock)."),
  },
  {
    id: "tool-res-lookup",
    slug: "reservations.lookup",
    name: "Lookup Reservation",
    description: "Find reservation by date or guest.",
    category: TOOL_CATEGORIES.RESERVATIONS,
    inputSchema: { date: "string", guestName: "string?" },
    isEnabled: true,
    handler: mockHandler("3 reservations found for today (mock)."),
  },
  {
    id: "tool-res-create",
    slug: "reservations.create",
    name: "Create Reservation",
    description: "Book a new reservation.",
    category: TOOL_CATEGORIES.RESERVATIONS,
    inputSchema: { guestName: "string", partySize: "number", dateTime: "string" },
    isEnabled: true,
    handler: mockHandler("Reservation confirmed (mock)."),
  },
  {
    id: "tool-inv-stock",
    slug: "inventory.stock-level",
    name: "Stock Level",
    description: "Check inventory stock for an item.",
    category: TOOL_CATEGORIES.INVENTORY,
    inputSchema: { sku: "string" },
    isEnabled: true,
    handler: mockHandler("Stock level: 42 units (mock)."),
  },
  {
    id: "tool-inv-reorder",
    slug: "inventory.reorder-suggestion",
    name: "Reorder Suggestion",
    description: "Get reorder recommendations.",
    category: TOOL_CATEGORIES.INVENTORY,
    inputSchema: { branchId: "string?" },
    isEnabled: true,
    handler: mockHandler("5 items below reorder point (mock)."),
  },
  {
    id: "tool-fin-invoice",
    slug: "finance.invoice-summary",
    name: "Invoice Summary",
    description: "Summarize outstanding invoices.",
    category: TOOL_CATEGORIES.FINANCE,
    inputSchema: { period: "string?" },
    isEnabled: true,
    handler: mockHandler("£12,450 outstanding across 8 invoices (mock)."),
  },
  {
    id: "tool-fin-payment",
    slug: "finance.payment-status",
    name: "Payment Status",
    description: "Check payment status for a transaction.",
    category: TOOL_CATEGORIES.FINANCE,
    inputSchema: { paymentId: "string" },
    isEnabled: true,
    handler: mockHandler("Payment settled (mock)."),
  },
  {
    id: "tool-mkt-campaign",
    slug: "marketing.campaign-status",
    name: "Campaign Status",
    description: "Get marketing campaign performance.",
    category: TOOL_CATEGORIES.MARKETING,
    inputSchema: { campaignId: "string" },
    isEnabled: true,
    handler: mockHandler("Campaign CTR 4.2% — above benchmark (mock)."),
  },
  {
    id: "tool-reports-summary",
    slug: "reports.summary",
    name: "Reports Summary",
    description: "Generate a cross-module business summary.",
    category: TOOL_CATEGORIES.REPORTS,
    inputSchema: { period: "string?" },
    isEnabled: true,
    handler: mockHandler("Revenue up 8% week-over-week (mock)."),
  },
  {
    id: "tool-reports-sales",
    slug: "reports.sales-summary",
    name: "Sales Summary",
    description: "Sales pipeline and revenue summary.",
    category: TOOL_CATEGORIES.REPORTS,
    inputSchema: { period: "string?" },
    isEnabled: true,
    handler: mockHandler("Pipeline value £84k across 12 opportunities (mock)."),
  },
  {
    id: "tool-reports-marketing",
    slug: "reports.marketing-summary",
    name: "Marketing Summary",
    description: "Marketing performance summary.",
    category: TOOL_CATEGORIES.REPORTS,
    inputSchema: { period: "string?" },
    isEnabled: true,
    handler: mockHandler("3 active campaigns, 1,240 new leads (mock)."),
  },
  {
    id: "tool-reports-inventory",
    slug: "reports.inventory-summary",
    name: "Inventory Summary",
    description: "Inventory health summary.",
    category: TOOL_CATEGORIES.REPORTS,
    inputSchema: { branchId: "string?" },
    isEnabled: true,
    handler: mockHandler("Inventory turnover 12 days average (mock)."),
  },
  {
    id: "tool-reports-finance",
    slug: "reports.finance-summary",
    name: "Finance Summary",
    description: "Financial performance summary.",
    category: TOOL_CATEGORIES.REPORTS,
    inputSchema: { period: "string?" },
    isEnabled: true,
    handler: mockHandler("Net margin 18.4% this month (mock)."),
  },
  {
    id: "tool-reports-export",
    slug: "reports.export",
    name: "Export Report",
    description: "Export a report to file.",
    category: TOOL_CATEGORIES.REPORTS,
    inputSchema: { reportType: "string", format: "string" },
    isEnabled: true,
    handler: mockHandler("Report export queued (mock)."),
  },
  {
    id: "tool-notify-send",
    slug: "notifications.send",
    name: "Send Notification",
    description: "Send a notification to a user or channel.",
    category: TOOL_CATEGORIES.NOTIFICATIONS,
    inputSchema: { channel: "string", message: "string" },
    isEnabled: true,
    handler: mockHandler("Notification sent (mock)."),
  },
  {
    id: "tool-dev-query",
    slug: "developer.query-api",
    name: "Query Developer API",
    description: "Execute a read-only developer API query.",
    category: TOOL_CATEGORIES.DEVELOPER,
    inputSchema: { endpoint: "string", params: "object?" },
    isEnabled: true,
    handler: mockHandler("API query returned 200 OK (mock)."),
  },
];
