import { PERMISSION_CODES } from "@/modules/authorization/constants/permissions";

/** Reservation permission aliases mapped to platform authorization codes. */
export const RESERVATION_MODULE_PERMISSIONS = {
  RESERVATION_READ: PERMISSION_CODES.RESERVATION_VIEW,
  RESERVATION_CREATE: PERMISSION_CODES.RESERVATION_CREATE,
  RESERVATION_UPDATE: PERMISSION_CODES.RESERVATION_UPDATE,
  RESERVATION_DELETE: PERMISSION_CODES.RESERVATION_DELETE,
  RESERVATION_CANCEL: PERMISSION_CODES.RESERVATION_CANCEL,
  RESERVATION_ASSIGN_TABLE: PERMISSION_CODES.RESERVATION_ASSIGN_TABLE,
  RESERVATION_MANAGE: PERMISSION_CODES.RESERVATION_MANAGE,
} as const;

export type ReservationModulePermissionCode =
  (typeof RESERVATION_MODULE_PERMISSIONS)[keyof typeof RESERVATION_MODULE_PERMISSIONS];
