import {
  ALERT_SEVERITIES,
  ANALYTICS_MODULE_SOURCES,
  CHART_TYPES,
  DASHBOARD_TYPES,
  KPI_TRENDS,
  REPORT_STATUSES,
  SCHEDULE_FREQUENCIES,
  WIDGET_TYPES,
} from "@/modules/analytics/constants/analytics-status";
import type { AnalyticsRecord, Dashboard } from "@/modules/analytics/types/analytics-platform";

export const DEFAULT_ANALYTICS_SCOPE = {
  tenantId: "tenant-harbour",
  workspaceId: "ws-harbour-kitchen",
  businessId: "biz-harbour-kitchen",
  branchId: "branch-harbour-main",
  userId: "user-harbour-owner",
  baseCurrency: "GBP",
} as const;

const PERIOD_START = "2026-02-01";
const PERIOD_END = "2026-02-28";
const NOW = "2026-02-15T23:00:00.000Z";

export const MOCK_EXECUTIVE_DASHBOARD: Dashboard = {
  id: "dash-executive",
  tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
  workspaceId: DEFAULT_ANALYTICS_SCOPE.workspaceId,
  businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
  name: "Executive Overview",
  dashboardType: DASHBOARD_TYPES.EXECUTIVE,
  description: "High-level business performance across all modules",
  widgetIds: ["widget-revenue-kpi", "widget-orders-kpi", "widget-revenue-chart", "widget-insights"],
  isDefault: true,
  isCustom: false,
  branchIds: [DEFAULT_ANALYTICS_SCOPE.branchId],
  createdByUserId: DEFAULT_ANALYTICS_SCOPE.userId,
  createdAt: NOW,
  updatedAt: NOW,
  deletedAt: null,
};

export const MOCK_OPERATIONS_DASHBOARD: Dashboard = {
  id: "dash-operations",
  tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
  workspaceId: DEFAULT_ANALYTICS_SCOPE.workspaceId,
  businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
  name: "Operations Dashboard",
  dashboardType: DASHBOARD_TYPES.OPERATIONS,
  description: "Real-time operations KPIs and alerts",
  widgetIds: ["widget-orders-kpi", "widget-kitchen-chart", "widget-reservations-kpi"],
  isDefault: false,
  isCustom: false,
  branchIds: [DEFAULT_ANALYTICS_SCOPE.branchId],
  createdByUserId: DEFAULT_ANALYTICS_SCOPE.userId,
  createdAt: NOW,
  updatedAt: NOW,
  deletedAt: null,
};

export const MOCK_ANALYTICS_RECORD: AnalyticsRecord = {
  dashboards: [MOCK_EXECUTIVE_DASHBOARD, MOCK_OPERATIONS_DASHBOARD],
  widgets: [
    {
      id: "widget-revenue-kpi",
      dashboardId: "dash-executive",
      widgetType: WIDGET_TYPES.KPI,
      title: "Total Revenue",
      metricId: null,
      kpiId: "kpi-revenue",
      chartId: null,
      reportId: null,
      positionX: 0,
      positionY: 0,
      width: 4,
      height: 2,
      refreshIntervalSec: 60,
      moduleSource: ANALYTICS_MODULE_SOURCES.POS,
    },
    {
      id: "widget-orders-kpi",
      dashboardId: "dash-executive",
      widgetType: WIDGET_TYPES.KPI,
      title: "Orders Today",
      metricId: null,
      kpiId: "kpi-orders",
      chartId: null,
      reportId: null,
      positionX: 4,
      positionY: 0,
      width: 4,
      height: 2,
      refreshIntervalSec: 30,
      moduleSource: ANALYTICS_MODULE_SOURCES.ORDERS,
    },
    {
      id: "widget-revenue-chart",
      dashboardId: "dash-executive",
      widgetType: WIDGET_TYPES.CHART,
      title: "Revenue Trend",
      metricId: null,
      kpiId: null,
      chartId: "chart-revenue",
      reportId: null,
      positionX: 0,
      positionY: 2,
      width: 8,
      height: 4,
      refreshIntervalSec: 300,
      moduleSource: ANALYTICS_MODULE_SOURCES.FINANCE,
    },
    {
      id: "widget-insights",
      dashboardId: "dash-executive",
      widgetType: WIDGET_TYPES.INSIGHT,
      title: "Business Insights",
      metricId: null,
      kpiId: null,
      chartId: null,
      reportId: null,
      positionX: 0,
      positionY: 6,
      width: 8,
      height: 3,
      refreshIntervalSec: 600,
      moduleSource: null,
    },
    {
      id: "widget-kitchen-chart",
      dashboardId: "dash-operations",
      widgetType: WIDGET_TYPES.CHART,
      title: "Kitchen Performance",
      metricId: null,
      kpiId: null,
      chartId: "chart-kitchen",
      reportId: null,
      positionX: 0,
      positionY: 2,
      width: 6,
      height: 4,
      refreshIntervalSec: 120,
      moduleSource: ANALYTICS_MODULE_SOURCES.KITCHEN,
    },
    {
      id: "widget-reservations-kpi",
      dashboardId: "dash-operations",
      widgetType: WIDGET_TYPES.KPI,
      title: "Reservations",
      metricId: null,
      kpiId: "kpi-reservations",
      chartId: null,
      reportId: null,
      positionX: 0,
      positionY: 0,
      width: 4,
      height: 2,
      refreshIntervalSec: 60,
      moduleSource: ANALYTICS_MODULE_SOURCES.RESERVATIONS,
    },
  ],
  metrics: [
    {
      id: "metric-revenue-daily",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      key: "revenue_daily",
      label: "Daily Revenue",
      value: 425000,
      unit: "GBP_cents",
      moduleSource: ANALYTICS_MODULE_SOURCES.POS,
      recordedAt: NOW,
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
    },
    {
      id: "metric-orders-daily",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      key: "orders_daily",
      label: "Daily Orders",
      value: 187,
      unit: "count",
      moduleSource: ANALYTICS_MODULE_SOURCES.ORDERS,
      recordedAt: NOW,
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
    },
  ],
  kpis: [
    {
      id: "kpi-revenue",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      key: "total_revenue",
      label: "Total Revenue",
      currentValue: 11850000,
      previousValue: 10920000,
      targetValue: 12000000,
      unit: "GBP_cents",
      trend: KPI_TRENDS.UP,
      changePercent: 8.5,
      moduleSource: ANALYTICS_MODULE_SOURCES.POS,
      updatedAt: NOW,
    },
    {
      id: "kpi-orders",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      key: "order_count",
      label: "Total Orders",
      currentValue: 5234,
      previousValue: 4980,
      targetValue: 5500,
      unit: "count",
      trend: KPI_TRENDS.UP,
      changePercent: 5.1,
      moduleSource: ANALYTICS_MODULE_SOURCES.ORDERS,
      updatedAt: NOW,
    },
    {
      id: "kpi-reservations",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      key: "reservation_count",
      label: "Reservations",
      currentValue: 342,
      previousValue: 318,
      targetValue: 400,
      unit: "count",
      trend: KPI_TRENDS.UP,
      changePercent: 7.5,
      moduleSource: ANALYTICS_MODULE_SOURCES.RESERVATIONS,
      updatedAt: NOW,
    },
    {
      id: "kpi-labour-cost",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      key: "labour_cost_percent",
      label: "Labour Cost %",
      currentValue: 28.5,
      previousValue: 30.2,
      targetValue: 27.0,
      unit: "percent",
      trend: KPI_TRENDS.DOWN,
      changePercent: -5.6,
      moduleSource: ANALYTICS_MODULE_SOURCES.STAFF,
      updatedAt: NOW,
    },
  ],
  charts: [
    {
      id: "chart-revenue",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      title: "Weekly Revenue",
      chartType: CHART_TYPES.LINE,
      moduleSource: ANALYTICS_MODULE_SOURCES.FINANCE,
      labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      datasets: [
        {
          id: "ds-revenue",
          label: "Revenue",
          data: [152000, 168000, 145000, 172000, 198000, 245000, 228000],
          color: "#2563eb",
        },
      ],
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
    },
    {
      id: "chart-kitchen",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      title: "Kitchen Ticket Volume",
      chartType: CHART_TYPES.BAR,
      moduleSource: ANALYTICS_MODULE_SOURCES.KITCHEN,
      labels: ["Grill", "Fry", "Salad", "Dessert", "Bar"],
      datasets: [
        {
          id: "ds-tickets",
          label: "Tickets",
          data: [420, 280, 190, 95, 310],
          color: "#16a34a",
        },
      ],
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
    },
  ],
  reports: [
    {
      id: "report-weekly-ops",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      name: "Weekly Operations Report",
      description: "Cross-module operations summary",
      status: REPORT_STATUSES.PUBLISHED,
      moduleSources: [
        ANALYTICS_MODULE_SOURCES.ORDERS,
        ANALYTICS_MODULE_SOURCES.KITCHEN,
        ANALYTICS_MODULE_SOURCES.STAFF,
      ],
      chartIds: ["chart-revenue", "chart-kitchen"],
      kpiIds: ["kpi-revenue", "kpi-orders", "kpi-labour-cost"],
      branchIds: [DEFAULT_ANALYTICS_SCOPE.branchId],
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
      createdByUserId: DEFAULT_ANALYTICS_SCOPE.userId,
      createdAt: NOW,
      updatedAt: NOW,
      deletedAt: null,
    },
  ],
  reportTemplates: [],
  dataSources: [],
  dashboardLayouts: [],
  savedViews: [],
  savedReports: [
    {
      id: "saved-report-001",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      reportId: "report-weekly-ops",
      name: "Feb Week 2 Ops Snapshot",
      savedAt: NOW,
      savedByUserId: DEFAULT_ANALYTICS_SCOPE.userId,
      snapshotData: { revenueCents: 11850000, orderCount: 5234 },
    },
  ],
  scheduledReports: [
    {
      id: "sched-report-001",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      reportId: "report-weekly-ops",
      name: "Weekly Ops Email",
      frequency: SCHEDULE_FREQUENCIES.WEEKLY,
      recipientEmails: ["owner@harbourkitchen.co.uk"],
      nextRunAt: "2026-02-22T08:00:00.000Z",
      lastRunAt: "2026-02-08T08:00:00.000Z",
      isActive: true,
      createdAt: NOW,
    },
  ],
  insights: [
    {
      id: "insight-001",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      title: "Weekend revenue up 12%",
      summary: "Saturday and Sunday revenue exceeded weekday average by 12%",
      moduleSource: ANALYTICS_MODULE_SOURCES.POS,
      severity: ALERT_SEVERITIES.INFO,
      impactScore: 0.72,
      recommendedActions: ["Increase weekend staffing", "Promote weekend specials"],
      generatedAt: NOW,
    },
    {
      id: "insight-002",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      title: "No-show rate elevated",
      summary: "Reservation no-show rate at 8.2%, above 5% target",
      moduleSource: ANALYTICS_MODULE_SOURCES.RESERVATIONS,
      severity: ALERT_SEVERITIES.WARNING,
      impactScore: 0.58,
      recommendedActions: ["Enable deposit for large parties", "Send reminder SMS 24h before"],
      generatedAt: NOW,
    },
  ],
  forecasts: [
    {
      id: "forecast-revenue-001",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      forecastType: "revenue",
      moduleSource: ANALYTICS_MODULE_SOURCES.FINANCE,
      periodStart: "2026-03-01",
      periodEnd: "2026-03-31",
      projectedValues: [
        { date: "2026-03-07", value: 1250000, lowerBound: 1100000, upperBound: 1400000 },
        { date: "2026-03-14", value: 1280000, lowerBound: 1120000, upperBound: 1440000 },
        { date: "2026-03-21", value: 1310000, lowerBound: 1140000, upperBound: 1480000 },
        { date: "2026-03-28", value: 1340000, lowerBound: 1160000, upperBound: 1520000 },
      ],
      confidenceScore: 0.82,
      generatedAt: NOW,
    },
    {
      id: "forecast-demand-001",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      forecastType: "demand",
      moduleSource: ANALYTICS_MODULE_SOURCES.ORDERS,
      periodStart: "2026-03-01",
      periodEnd: "2026-03-07",
      projectedValues: [
        { date: "2026-03-01", value: 180, lowerBound: 150, upperBound: 210 },
        { date: "2026-03-02", value: 175, lowerBound: 145, upperBound: 205 },
        { date: "2026-03-03", value: 190, lowerBound: 160, upperBound: 220 },
      ],
      confidenceScore: 0.75,
      generatedAt: NOW,
    },
  ],
  alerts: [
    {
      id: "alert-001",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      title: "Low stock: Salmon fillet",
      message: "Salmon fillet below reorder threshold (2 units remaining)",
      severity: ALERT_SEVERITIES.WARNING,
      moduleSource: ANALYTICS_MODULE_SOURCES.INVENTORY,
      metricKey: "stock_level",
      thresholdValue: 5,
      actualValue: 2,
      isAcknowledged: false,
      triggeredAt: NOW,
    },
    {
      id: "alert-002",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
      title: "Kitchen prep time spike",
      message: "Average prep time exceeded 18 min threshold",
      severity: ALERT_SEVERITIES.CRITICAL,
      moduleSource: ANALYTICS_MODULE_SOURCES.KITCHEN,
      metricKey: "avg_prep_time_min",
      thresholdValue: 18,
      actualValue: 22,
      isAcknowledged: false,
      triggeredAt: NOW,
    },
  ],
  benchmarks: [
    {
      id: "bench-001",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      metricKey: "average_order_value",
      label: "Average Order Value",
      businessValue: 2270,
      industryAverage: 2100,
      topPerformerValue: 2800,
      percentileRank: 68,
      moduleSource: ANALYTICS_MODULE_SOURCES.POS,
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
    },
    {
      id: "bench-002",
      tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
      businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
      metricKey: "labour_cost_percent",
      label: "Labour Cost %",
      businessValue: 28.5,
      industryAverage: 30.0,
      topPerformerValue: 24.0,
      percentileRank: 72,
      moduleSource: ANALYTICS_MODULE_SOURCES.STAFF,
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
    },
  ],
  sales: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
    branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
    totalRevenueCents: 11850000,
    orderCount: 5234,
    averageOrderValueCents: 2264,
    topSellingItems: [
      { itemId: "menu-001", name: "Fish & Chips", quantity: 842, revenueCents: 1684000 },
      { itemId: "menu-002", name: "Harbour Burger", quantity: 621, revenueCents: 1117800 },
      { itemId: "menu-003", name: "Seafood Platter", quantity: 312, revenueCents: 1248000 },
    ],
    revenueByHour: [
      { hour: 12, revenueCents: 980000 },
      { hour: 13, revenueCents: 1120000 },
      { hour: 18, revenueCents: 1450000 },
      { hour: 19, revenueCents: 1680000 },
      { hour: 20, revenueCents: 1520000 },
    ],
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  customers: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
    totalCustomers: 2847,
    newCustomers: 186,
    returningCustomers: 412,
    retentionRateBps: 6200,
    averageLifetimeValueCents: 48500,
    topSegments: [
      { segment: "Regular", count: 890, revenueCents: 4200000 },
      { segment: "VIP", count: 124, revenueCents: 2100000 },
      { segment: "Walk-in", count: 1833, revenueCents: 5550000 },
    ],
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  menu: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
    branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
    totalItems: 86,
    activeItems: 72,
    topPerformers: [
      { itemId: "menu-001", name: "Fish & Chips", orders: 842, revenueCents: 1684000 },
      { itemId: "menu-003", name: "Seafood Platter", orders: 312, revenueCents: 1248000 },
    ],
    underperformers: [
      { itemId: "menu-045", name: "Vegetable Risotto", orders: 12 },
      { itemId: "menu-052", name: "Lamb Shank", orders: 18 },
    ],
    categoryBreakdown: [
      { category: "Mains", revenueCents: 6200000, orderCount: 2100 },
      { category: "Starters", revenueCents: 2100000, orderCount: 1800 },
      { category: "Drinks", revenueCents: 2450000, orderCount: 3200 },
    ],
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  reservations: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
    branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
    totalReservations: 342,
    confirmedCount: 298,
    cancelledCount: 24,
    noShowCount: 20,
    noShowRateBps: 820,
    averagePartySize: 3.4,
    peakHours: [
      { hour: 19, count: 68 },
      { hour: 20, count: 72 },
      { hour: 13, count: 45 },
    ],
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  kitchen: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
    branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
    totalTickets: 1295,
    averagePrepTimeMin: 14.2,
    onTimeRateBps: 9100,
    stationBreakdown: [
      { station: "Grill", ticketCount: 420, avgPrepTimeMin: 16.5 },
      { station: "Fry", ticketCount: 280, avgPrepTimeMin: 8.2 },
      { station: "Salad", ticketCount: 190, avgPrepTimeMin: 5.1 },
    ],
    rushHourPeak: "19:00-20:00",
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  inventory: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
    branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
    totalSkus: 142,
    lowStockCount: 8,
    wasteValueCents: 42000,
    turnoverRateBps: 4500,
    topConsumedItems: [
      { itemId: "inv-001", name: "Atlantic Salmon", quantityUsed: 48 },
      { itemId: "inv-002", name: "Potatoes", quantityUsed: 120 },
    ],
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  staff: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
    branchId: DEFAULT_ANALYTICS_SCOPE.branchId,
    totalStaff: 24,
    activeShifts: 6,
    labourCostCents: 3378000,
    labourCostPercentBps: 2850,
    overtimeHours: 12,
    attendanceRateBps: 9600,
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  finance: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    businessId: DEFAULT_ANALYTICS_SCOPE.businessId,
    revenueCents: 11850000,
    expenseCents: 8420000,
    netProfitCents: 3430000,
    grossMarginBps: 6200,
    accountsReceivableCents: 245000,
    cashOnHandCents: 1850000,
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  billing: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    mrrCents: 29900,
    arrCents: 358800,
    activeSubscriptions: 1,
    churnRateBps: 250,
    upgradeCount: 1,
    downgradeCount: 0,
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  aiContext: {
    tenantId: DEFAULT_ANALYTICS_SCOPE.tenantId,
    summary: "Revenue up 8.5% — 5,234 orders, £118.5k MTD",
    topInsights: [
      "Weekend revenue up 12%",
      "No-show rate elevated at 8.2%",
      "Labour cost improved to 28.5%",
    ],
    anomalyCount: 2,
    forecastConfidence: 0.82,
    recommendedActions: [
      "Increase weekend staffing",
      "Enable reservation deposits",
      "Reorder salmon fillet",
    ],
    executiveSummary:
      "Harbour Kitchen is performing above industry benchmarks with 8.5% revenue growth. Key focus areas: reservation no-shows and kitchen prep times during peak hours.",
    lastGeneratedAt: NOW,
  },
};
