import { BUILTIN_AGENT_SLUGS } from "@/modules/ai/constants/agent-slugs";
import { PLATFORM_SKILL_SLUGS } from "@/modules/ai-tools/constants/skills";
import {
  PLATFORM_MODULES,
  PLATFORM_TOOL_IDS,
  PLATFORM_TOOL_PERMISSIONS,
} from "@/modules/ai-tools/constants/platform-tools";
import type { RegisteredPlatformSkill } from "@/modules/ai-tools/types/skill";

export const BUILTIN_PLATFORM_SKILLS: RegisteredPlatformSkill[] = [
  {
    id: "skill-def-customer-lookup",
    slug: PLATFORM_SKILL_SLUGS.CUSTOMER_LOOKUP,
    name: "Customer Lookup",
    description: "Find a customer and summarize their profile.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.CUSTOMER],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.CUSTOMERS_READ],
    requiredModules: [PLATFORM_MODULES.CRM],
    supportedAgents: [BUILTIN_AGENT_SLUGS.SALES, BUILTIN_AGENT_SLUGS.CUSTOMER_SUPPORT],
    inputSchema: { type: "object", properties: { query: { type: "string" } } },
    outputSchema: { type: "object", properties: { customer: { type: "object" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-reservation-book",
    slug: PLATFORM_SKILL_SLUGS.RESERVATION_BOOK,
    name: "Book Reservation",
    description: "Check availability and book a reservation.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.RESERVATION],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.RESERVATIONS_MANAGE],
    requiredModules: [PLATFORM_MODULES.RESERVATIONS],
    supportedAgents: [BUILTIN_AGENT_SLUGS.RESERVATION],
    inputSchema: {
      type: "object",
      properties: { guestName: { type: "string" }, partySize: { type: "number" } },
    },
    outputSchema: { type: "object", properties: { reservationId: { type: "string" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-menu-browse",
    slug: PLATFORM_SKILL_SLUGS.MENU_BROWSE,
    name: "Browse Menu",
    description: "List menu items by category.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.MENU],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.MENU_READ],
    requiredModules: [PLATFORM_MODULES.MENU],
    supportedAgents: ["waiter", BUILTIN_AGENT_SLUGS.OPERATIONS],
    inputSchema: { type: "object", properties: { categoryId: { type: "string" } } },
    outputSchema: { type: "object", properties: { items: { type: "array" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-order-track",
    slug: PLATFORM_SKILL_SLUGS.ORDER_TRACK,
    name: "Track Order",
    description: "Track order status and timeline.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.ORDER],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.ORDERS_READ],
    requiredModules: [PLATFORM_MODULES.ORDERS],
    supportedAgents: [BUILTIN_AGENT_SLUGS.OPERATIONS, "waiter"],
    inputSchema: { type: "object", properties: { orderId: { type: "string" } } },
    outputSchema: { type: "object", properties: { status: { type: "string" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-kitchen-monitor",
    slug: PLATFORM_SKILL_SLUGS.KITCHEN_MONITOR,
    name: "Monitor Kitchen",
    description: "Monitor kitchen ticket queue and load.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.KITCHEN],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.KITCHEN_READ],
    requiredModules: [PLATFORM_MODULES.KITCHEN],
    supportedAgents: ["kitchen-staff"],
    inputSchema: { type: "object", properties: {} },
    outputSchema: { type: "object", properties: { load: { type: "string" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-pos-checkout",
    slug: PLATFORM_SKILL_SLUGS.POS_CHECKOUT,
    name: "POS Checkout",
    description: "Process a POS checkout flow.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.POS, PLATFORM_TOOL_IDS.ORDER],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.POS_MANAGE],
    requiredModules: [PLATFORM_MODULES.POS, PLATFORM_MODULES.ORDERS],
    supportedAgents: ["cashier"],
    inputSchema: { type: "object", properties: { orderId: { type: "string" } } },
    outputSchema: { type: "object", properties: { receiptId: { type: "string" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-inventory-check",
    slug: PLATFORM_SKILL_SLUGS.INVENTORY_CHECK,
    name: "Check Inventory",
    description: "Check stock and reorder suggestions.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.INVENTORY],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.INVENTORY_READ],
    requiredModules: [PLATFORM_MODULES.INVENTORY],
    supportedAgents: [BUILTIN_AGENT_SLUGS.INVENTORY],
    inputSchema: { type: "object", properties: { sku: { type: "string" } } },
    outputSchema: { type: "object", properties: { stock: { type: "number" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-finance-summary",
    slug: PLATFORM_SKILL_SLUGS.FINANCE_SUMMARY,
    name: "Finance Summary",
    description: "Summarize financial performance.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.FINANCE],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.FINANCE_READ],
    requiredModules: [PLATFORM_MODULES.FINANCE],
    supportedAgents: [BUILTIN_AGENT_SLUGS.FINANCE],
    inputSchema: { type: "object", properties: { period: { type: "string" } } },
    outputSchema: { type: "object", properties: { summary: { type: "object" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-marketing-campaign",
    slug: PLATFORM_SKILL_SLUGS.MARKETING_CAMPAIGN,
    name: "Campaign Insight",
    description: "Analyze marketing campaign performance.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.MARKETING],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.MARKETING_READ],
    requiredModules: [PLATFORM_MODULES.MARKETING],
    supportedAgents: [BUILTIN_AGENT_SLUGS.MARKETING],
    inputSchema: { type: "object", properties: { campaignId: { type: "string" } } },
    outputSchema: { type: "object", properties: { performance: { type: "object" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-analytics-insight",
    slug: PLATFORM_SKILL_SLUGS.ANALYTICS_INSIGHT,
    name: "Analytics Insight",
    description: "Generate analytics insights for a metric.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.ANALYTICS],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.ANALYTICS_READ],
    requiredModules: [PLATFORM_MODULES.ANALYTICS],
    supportedAgents: [BUILTIN_AGENT_SLUGS.ANALYTICS],
    inputSchema: { type: "object", properties: { metric: { type: "string" } } },
    outputSchema: { type: "object", properties: { insight: { type: "string" } } },
    isEnabled: true,
  },
  {
    id: "skill-def-notify-staff",
    slug: PLATFORM_SKILL_SLUGS.NOTIFY_STAFF,
    name: "Notify Staff",
    description: "Send a notification to staff members.",
    version: "1.0.0",
    toolIds: [PLATFORM_TOOL_IDS.NOTIFICATION],
    requiredPermissions: [PLATFORM_TOOL_PERMISSIONS.NOTIFICATIONS_SEND],
    requiredModules: [PLATFORM_MODULES.NOTIFICATIONS],
    supportedAgents: [BUILTIN_AGENT_SLUGS.STAFF, BUILTIN_AGENT_SLUGS.OPERATIONS],
    inputSchema: {
      type: "object",
      properties: { message: { type: "string" }, staffIds: { type: "array" } },
    },
    outputSchema: { type: "object", properties: { sent: { type: "boolean" } } },
    isEnabled: true,
  },
];
