export const CUSTOMER_PORTAL_ROUTES = {
  home: "/portal",
  login: "/portal/login",
  register: "/portal/register",
  dashboard: "/portal",
  profile: "/portal/profile",
  orders: "/portal/orders",
  orderDetail: (orderId: string) => `/portal/orders/${orderId}`,
  reservations: "/portal/reservations",
  reservationDetail: (reservationId: string) => `/portal/reservations/${reservationId}`,
  loyalty: "/portal/loyalty",
  rewards: "/portal/rewards",
  wallet: "/portal/wallet",
  giftCards: "/portal/gift-cards",
  coupons: "/portal/coupons",
  addresses: "/portal/addresses",
  payments: "/portal/payments",
  notifications: "/portal/notifications",
  messages: "/portal/messages",
  support: "/portal/support",
  assistant: "/portal/assistant",
  security: "/portal/security",
  preferences: "/portal/preferences",
  receipts: "/portal/receipts",
  receiptDetail: (receiptId: string) => `/portal/receipts/${receiptId}`,
  invoices: "/portal/invoices",
  invoiceDetail: (invoiceId: string) => `/portal/invoices/${invoiceId}`,
  favorites: "/portal/favorites",
  settings: "/portal/settings",
} as const;

export const CUSTOMER_PORTAL_COOKIE = "busal-portal-business" as const;

export const CUSTOMER_PORTAL_NAV = [
  { label: "Dashboard", href: CUSTOMER_PORTAL_ROUTES.dashboard, icon: "layout-dashboard" },
  { label: "Profile", href: CUSTOMER_PORTAL_ROUTES.profile, icon: "user" },
  { label: "Orders", href: CUSTOMER_PORTAL_ROUTES.orders, icon: "shopping-bag" },
  { label: "Reservations", href: CUSTOMER_PORTAL_ROUTES.reservations, icon: "calendar" },
  { label: "Loyalty", href: CUSTOMER_PORTAL_ROUTES.loyalty, icon: "star" },
  { label: "Rewards", href: CUSTOMER_PORTAL_ROUTES.rewards, icon: "gift" },
  { label: "Wallet", href: CUSTOMER_PORTAL_ROUTES.wallet, icon: "wallet" },
  { label: "Gift Cards", href: CUSTOMER_PORTAL_ROUTES.giftCards, icon: "credit-card" },
  { label: "Coupons", href: CUSTOMER_PORTAL_ROUTES.coupons, icon: "ticket" },
  { label: "Addresses", href: CUSTOMER_PORTAL_ROUTES.addresses, icon: "map-pin" },
  { label: "Payments", href: CUSTOMER_PORTAL_ROUTES.payments, icon: "banknote" },
  { label: "Notifications", href: CUSTOMER_PORTAL_ROUTES.notifications, icon: "bell" },
  { label: "Messages", href: CUSTOMER_PORTAL_ROUTES.messages, icon: "message-square" },
  { label: "Support", href: CUSTOMER_PORTAL_ROUTES.support, icon: "life-buoy" },
  { label: "AI Assistant", href: CUSTOMER_PORTAL_ROUTES.assistant, icon: "bot" },
  { label: "Receipts", href: CUSTOMER_PORTAL_ROUTES.receipts, icon: "receipt" },
  { label: "Invoices", href: CUSTOMER_PORTAL_ROUTES.invoices, icon: "file-text" },
  { label: "Favorites", href: CUSTOMER_PORTAL_ROUTES.favorites, icon: "heart" },
  { label: "Preferences", href: CUSTOMER_PORTAL_ROUTES.preferences, icon: "sliders-horizontal" },
  { label: "Security", href: CUSTOMER_PORTAL_ROUTES.security, icon: "shield" },
  { label: "Settings", href: CUSTOMER_PORTAL_ROUTES.settings, icon: "settings" },
] as const;
