export {
  buildAnalyticsAiContext,
  generateReportForAi,
  explainKpiForAi,
  forecastRevenueForAi,
  forecastDemandForAi,
  detectBusinessAnomaliesForAi,
  recommendImprovementsForAi,
  generateExecutiveSummaryForAi,
  compareBranchesForAi,
  customerInsightsForAi,
  churnPredictionForAi,
  inventoryForecastForAi,
  staffingRecommendationsForAi,
  financialForecastForAi,
  businessHealthScoreForAi,
} from "@/modules/analytics/services/analytics-ai.service";
