export const WORKSPACE_SHELL_ROUTES = {
  dashboard: "/dashboard",
  business: "/dashboard/business",
  customers: "/dashboard/crm",
  orders: "/dashboard/restaurant/orders",
  reservations: "/dashboard/reservations",
  menu: "/dashboard/menu",
  kitchen: "/dashboard/kitchen",
  pos: "/dashboard/pos",
  inventory: "/dashboard/inventory",
  marketing: "/dashboard/commercial",
  finance: "/dashboard/payments",
  staff: "/dashboard/staff",
  reports: "/dashboard/reporting",
  ai: "/dashboard/ai-platform",
  settings: "/dashboard/settings",
  help: "/help",
  notifications: "/dashboard/notifications",
} as const;
