import "server-only";

import { PERMISSION_CODES } from "@/modules/authorization/constants/permissions";
import {
  CONTROL_CENTER_ENVIRONMENT,
  CONTROL_CENTER_OPERATOR_ENV_KEY,
} from "@/modules/control-center/constants/routes";
import type { ControlCenterOperatorContext } from "@/modules/control-center/types/control-center-types";
import type { AuthUser } from "@/types/auth";

const CONTROL_CENTER_PERMISSIONS = [
  PERMISSION_CODES.CONTROL_CENTER_VIEW,
  PERMISSION_CODES.CONTROL_CENTER_ADMIN,
  PERMISSION_CODES.CONTROL_CENTER_TENANTS,
  PERMISSION_CODES.CONTROL_CENTER_TENANTS_EDIT,
  PERMISSION_CODES.CONTROL_CENTER_TENANTS_SUSPEND,
  PERMISSION_CODES.CONTROL_CENTER_TENANTS_DELETE,
  PERMISSION_CODES.CONTROL_CENTER_TENANTS_POLICIES,
  PERMISSION_CODES.CONTROL_CENTER_TENANTS_RESOURCES,
  PERMISSION_CODES.CONTROL_CENTER_TENANTS_MAINTENANCE,
  PERMISSION_CODES.CONTROL_CENTER_TENANTS_ANALYTICS,
  PERMISSION_CODES.CONTROL_CENTER_SUBSCRIPTIONS,
  PERMISSION_CODES.CONTROL_CENTER_BILLING,
  PERMISSION_CODES.CONTROL_CENTER_BILLING_PLANS,
  PERMISSION_CODES.CONTROL_CENTER_BILLING_INVOICES,
  PERMISSION_CODES.CONTROL_CENTER_BILLING_PAYMENTS,
  PERMISSION_CODES.CONTROL_CENTER_BILLING_REFUNDS,
  PERMISSION_CODES.CONTROL_CENTER_BILLING_PROMOTIONS,
  PERMISSION_CODES.CONTROL_CENTER_BILLING_ANALYTICS,
  PERMISSION_CODES.CONTROL_CENTER_REVENUE,
  PERMISSION_CODES.CONTROL_CENTER_MARKETPLACE,
  PERMISSION_CODES.CONTROL_CENTER_MARKETPLACE_PUBLISHERS,
  PERMISSION_CODES.CONTROL_CENTER_MARKETPLACE_REVIEWS,
  PERMISSION_CODES.CONTROL_CENTER_MARKETPLACE_LICENSES,
  PERMISSION_CODES.CONTROL_CENTER_MARKETPLACE_MODERATION,
  PERMISSION_CODES.CONTROL_CENTER_MARKETPLACE_ANALYTICS,
  PERMISSION_CODES.CONTROL_CENTER_AI,
  PERMISSION_CODES.CONTROL_CENTER_MONITORING,
  PERMISSION_CODES.CONTROL_CENTER_MONITORING_LOGS,
  PERMISSION_CODES.CONTROL_CENTER_MONITORING_ALERTS,
  PERMISSION_CODES.CONTROL_CENTER_MONITORING_INCIDENTS,
  PERMISSION_CODES.CONTROL_CENTER_MONITORING_INFRASTRUCTURE,
  PERMISSION_CODES.CONTROL_CENTER_MONITORING_AI,
  PERMISSION_CODES.CONTROL_CENTER_SUPPORT,
  PERMISSION_CODES.CONTROL_CENTER_SUPPORT_TICKETS,
  PERMISSION_CODES.CONTROL_CENTER_SUPPORT_INCIDENTS,
  PERMISSION_CODES.CONTROL_CENTER_SUPPORT_KNOWLEDGE,
  PERMISSION_CODES.CONTROL_CENTER_SUPPORT_ANALYTICS,
  PERMISSION_CODES.CONTROL_CENTER_SUPPORT_SERVICE_STATUS,
  PERMISSION_CODES.CONTROL_CENTER_INCIDENTS,
  PERMISSION_CODES.CONTROL_CENTER_AUDIT,
  PERMISSION_CODES.CONTROL_CENTER_SETTINGS,
  PERMISSION_CODES.CONTROL_CENTER_MAINTENANCE,
  PERMISSION_CODES.CONTROL_CENTER_RELEASES,
  PERMISSION_CODES.CONTROL_CENTER_STAFF,
  PERMISSION_CODES.CONTROL_CENTER_ANALYTICS,
  PERMISSION_CODES.CONTROL_CENTER_FEATURE_FLAGS,
] as const;

export function getControlCenterOperatorEmails(): string[] {
  return (process.env[CONTROL_CENTER_OPERATOR_ENV_KEY] ?? "")
    .split(",")
    .map((email) => email.trim().toLowerCase())
    .filter(Boolean);
}

export function isControlCenterOperatorEmail(email: string): boolean {
  const operators = getControlCenterOperatorEmails();
  const normalized = email.trim().toLowerCase();

  if (!normalized) {
    return false;
  }

  if (operators.length === 0) {
    return process.env.BUSAL_CONTROL_CENTER_ALLOW_DEV === "true";
  }

  return operators.includes(normalized);
}

export function resolveControlCenterPermissions(email: string): string[] {
  if (!isControlCenterOperatorEmail(email)) {
    return [];
  }

  return [...CONTROL_CENTER_PERMISSIONS];
}

export function buildControlCenterOperatorContext(user: AuthUser): ControlCenterOperatorContext {
  const permissions = resolveControlCenterPermissions(user.email);

  return {
    userId: user.id,
    email: user.email,
    fullName: user.fullName ?? user.email,
    permissions,
    environment: CONTROL_CENTER_ENVIRONMENT,
    isOperator: permissions.length > 0,
  };
}

export function controlCenterOperatorHasPermission(
  context: ControlCenterOperatorContext,
  permission: string,
): boolean {
  return (
    context.permissions.includes(PERMISSION_CODES.CONTROL_CENTER_ADMIN) ||
    context.permissions.includes(permission)
  );
}
