import { PERMISSION_CODES } from "@/modules/authorization/constants/permissions";
import { PLATFORM_OPERATOR_ROLES } from "@/modules/control-center/operators/types/control-center-operators-types";
import type { PlatformOperatorRole } from "@/modules/control-center/operators/types/control-center-operators-types";

export { PLATFORM_OPERATOR_ROLES };

export const CONTROL_CENTER_OPERATOR_ROUTES = {
  directory: "/control-center/operators",
  detail: (operatorId: string) => `/control-center/operators/${operatorId}`,
} as const;

export const CONTROL_CENTER_OPERATOR_PAGE_SIZE = 20;

export const OPERATOR_REGISTRY_SETTING_KEY = "platform.operators.registry";

export const OPERATOR_STATUS_FILTER_OPTIONS = ["active", "suspended"] as const;

export const OPERATOR_SORT_OPTIONS = [
  "createdAt",
  "fullName",
  "email",
  "role",
  "lastLogin",
  "status",
] as const;

export const OPERATOR_ROLE_LABELS: Record<PlatformOperatorRole, string> = {
  PLATFORM_OWNER: "Platform Owner",
  SUPER_ADMIN: "Super Admin",
  PLATFORM_ADMIN: "Platform Admin",
  SUPPORT: "Support",
  FINANCE: "Finance",
  SALES: "Sales",
  CUSTOMER_SUCCESS: "Customer Success",
  DEVELOPER: "Developer",
  READ_ONLY: "Read Only",
};

export const OPERATOR_ROLE_PERMISSIONS: Record<PlatformOperatorRole, string[]> = {
  PLATFORM_OWNER: Object.values(PERMISSION_CODES).filter((code) => code.startsWith("control_center")),
  SUPER_ADMIN: [
    PERMISSION_CODES.CONTROL_CENTER_VIEW,
    PERMISSION_CODES.CONTROL_CENTER_ADMIN,
    PERMISSION_CODES.CONTROL_CENTER_TENANTS,
    PERMISSION_CODES.CONTROL_CENTER_TENANTS_EDIT,
    PERMISSION_CODES.CONTROL_CENTER_TENANTS_SUSPEND,
    PERMISSION_CODES.CONTROL_CENTER_BUSINESSES,
    PERMISSION_CODES.CONTROL_CENTER_BUSINESSES_EDIT,
    PERMISSION_CODES.CONTROL_CENTER_BUSINESSES_SUSPEND,
    PERMISSION_CODES.CONTROL_CENTER_WORKSPACES,
    PERMISSION_CODES.CONTROL_CENTER_WORKSPACES_EDIT,
    PERMISSION_CODES.CONTROL_CENTER_WORKSPACES_SUSPEND,
    PERMISSION_CODES.CONTROL_CENTER_OPERATORS,
    PERMISSION_CODES.CONTROL_CENTER_OPERATORS_EDIT,
    PERMISSION_CODES.CONTROL_CENTER_OPERATORS_SUSPEND,
    PERMISSION_CODES.CONTROL_CENTER_OPERATORS_ROLES,
    PERMISSION_CODES.CONTROL_CENTER_OPERATORS_PERMISSIONS,
    PERMISSION_CODES.CONTROL_CENTER_SECURITY,
    PERMISSION_CODES.CONTROL_CENTER_SECURITY_SESSIONS,
    PERMISSION_CODES.CONTROL_CENTER_SECURITY_ACCOUNTS,
    PERMISSION_CODES.CONTROL_CENTER_MONITORING,
    PERMISSION_CODES.CONTROL_CENTER_SUPPORT,
    PERMISSION_CODES.CONTROL_CENTER_AUDIT,
    PERMISSION_CODES.CONTROL_CENTER_ANALYTICS,
    PERMISSION_CODES.CONTROL_CENTER_INTELLIGENCE,
    PERMISSION_CODES.CONTROL_CENTER_CEO,
  ],
  PLATFORM_ADMIN: [
    PERMISSION_CODES.CONTROL_CENTER_VIEW,
    PERMISSION_CODES.CONTROL_CENTER_TENANTS,
    PERMISSION_CODES.CONTROL_CENTER_TENANTS_EDIT,
    PERMISSION_CODES.CONTROL_CENTER_BUSINESSES,
    PERMISSION_CODES.CONTROL_CENTER_BUSINESSES_EDIT,
    PERMISSION_CODES.CONTROL_CENTER_WORKSPACES,
    PERMISSION_CODES.CONTROL_CENTER_WORKSPACES_EDIT,
    PERMISSION_CODES.CONTROL_CENTER_OPERATORS,
    PERMISSION_CODES.CONTROL_CENTER_OPERATORS_EDIT,
    PERMISSION_CODES.CONTROL_CENTER_MONITORING,
    PERMISSION_CODES.CONTROL_CENTER_SUPPORT,
    PERMISSION_CODES.CONTROL_CENTER_AUDIT,
  ],
  SUPPORT: [
    PERMISSION_CODES.CONTROL_CENTER_VIEW,
    PERMISSION_CODES.CONTROL_CENTER_TENANTS,
    PERMISSION_CODES.CONTROL_CENTER_BUSINESSES,
    PERMISSION_CODES.CONTROL_CENTER_WORKSPACES,
    PERMISSION_CODES.CONTROL_CENTER_SUPPORT,
    PERMISSION_CODES.CONTROL_CENTER_SUPPORT_TICKETS,
  ],
  FINANCE: [
    PERMISSION_CODES.CONTROL_CENTER_VIEW,
    PERMISSION_CODES.CONTROL_CENTER_BILLING,
    PERMISSION_CODES.CONTROL_CENTER_BILLING_INVOICES,
    PERMISSION_CODES.CONTROL_CENTER_BILLING_PAYMENTS,
    PERMISSION_CODES.CONTROL_CENTER_REVENUE,
    PERMISSION_CODES.CONTROL_CENTER_SUBSCRIPTIONS,
  ],
  SALES: [
    PERMISSION_CODES.CONTROL_CENTER_VIEW,
    PERMISSION_CODES.CONTROL_CENTER_TENANTS,
    PERMISSION_CODES.CONTROL_CENTER_BUSINESSES,
    PERMISSION_CODES.CONTROL_CENTER_REVENUE,
    PERMISSION_CODES.CONTROL_CENTER_ANALYTICS,
  ],
  CUSTOMER_SUCCESS: [
    PERMISSION_CODES.CONTROL_CENTER_VIEW,
    PERMISSION_CODES.CONTROL_CENTER_TENANTS,
    PERMISSION_CODES.CONTROL_CENTER_BUSINESSES,
    PERMISSION_CODES.CONTROL_CENTER_WORKSPACES,
    PERMISSION_CODES.CONTROL_CENTER_SUPPORT,
    PERMISSION_CODES.CONTROL_CENTER_SUPPORT_TICKETS,
  ],
  DEVELOPER: [
    PERMISSION_CODES.CONTROL_CENTER_VIEW,
    PERMISSION_CODES.CONTROL_CENTER_MONITORING,
    PERMISSION_CODES.CONTROL_CENTER_MONITORING_LOGS,
    PERMISSION_CODES.CONTROL_CENTER_FEATURE_FLAGS,
    PERMISSION_CODES.CONTROL_CENTER_RELEASES,
    PERMISSION_CODES.CONTROL_CENTER_AI,
  ],
  READ_ONLY: [PERMISSION_CODES.CONTROL_CENTER_VIEW, PERMISSION_CODES.CONTROL_CENTER_OPERATORS],
};
