import type { CoverArtVariant } from "@/modules/marketing/components/marketing-cover-art";

export const RESOURCE_CATEGORIES = [
  "AI",
  "Operations",
  "Marketing",
  "CRM",
  "POS",
  "Inventory",
  "Finance",
  "Analytics",
  "Growth",
  "Security",
] as const;

export type ResourceCategory = (typeof RESOURCE_CATEGORIES)[number];

export type ResourceType =
  "Guide" | "Playbook" | "Checklist" | "Template" | "Whitepaper" | "Case Study" | "Video";

export type ResourceItem = {
  id: string;
  title: string;
  category: ResourceCategory;
  type: ResourceType;
  readTime: string;
  gradient: string;
  coverVariant: CoverArtVariant;
  href: string;
  cta: string;
  featured?: boolean;
};

export const ALL_RESOURCES: ResourceItem[] = [
  {
    id: "ai-business-guide",
    title: "AI Business Guide",
    category: "AI",
    type: "Guide",
    readTime: "18 min read",
    gradient: "linear-gradient(145deg, #3b82f6, #6366f1)",
    coverVariant: "ai",
    href: "/blog/ai-that-knows-your-service",
    cta: "Read guide",
    featured: true,
  },
  {
    id: "restaurant-playbook",
    title: "Restaurant Growth Playbook",
    category: "Operations",
    type: "Playbook",
    readTime: "22 min read",
    gradient: "linear-gradient(145deg, #f97316, #ef4444)",
    coverVariant: "restaurant",
    href: "/blog/ai-for-restaurants",
    cta: "Read playbook",
    featured: true,
  },
  {
    id: "retail-ops",
    title: "Retail Operations Guide",
    category: "POS",
    type: "Guide",
    readTime: "16 min read",
    gradient: "linear-gradient(145deg, #8b5cf6, #a855f7)",
    coverVariant: "retail",
    href: "/blog/retail-automation-without-chaos",
    cta: "Read guide",
    featured: true,
  },
  {
    id: "automation-handbook",
    title: "Business Automation Handbook",
    category: "Operations",
    type: "Playbook",
    readTime: "20 min read",
    gradient: "linear-gradient(145deg, #06b6d4, #3b82f6)",
    coverVariant: "automation",
    href: "/blog/retail-automation-without-chaos",
    cta: "Read handbook",
    featured: true,
  },
  {
    id: "digital-toolkit",
    title: "Digital Transformation Toolkit",
    category: "Growth",
    type: "Whitepaper",
    readTime: "25 min read",
    gradient: "linear-gradient(145deg, #10b981, #059669)",
    coverVariant: "growth",
    href: "/blog/operating-system-vs-tool-stack",
    cta: "Explore toolkit",
    featured: true,
  },
  {
    id: "retention-strategies",
    title: "Customer Retention Strategies",
    category: "CRM",
    type: "Guide",
    readTime: "14 min read",
    gradient: "linear-gradient(145deg, #ec4899, #8b5cf6)",
    coverVariant: "loyalty",
    href: "/blog/customer-loyalty-that-compounds",
    cta: "Read strategies",
    featured: true,
  },
  {
    id: "inventory-playbook",
    title: "Inventory Optimization Playbook",
    category: "Inventory",
    type: "Playbook",
    readTime: "19 min read",
    gradient: "linear-gradient(145deg, #6366f1, #8b5cf6)",
    coverVariant: "inventory",
    href: "/blog/inventory-optimization-guide",
    cta: "Read playbook",
  },
  {
    id: "crm-service-guide",
    title: "CRM Best Practices for Service",
    category: "CRM",
    type: "Guide",
    readTime: "15 min read",
    gradient: "linear-gradient(145deg, #ec4899, #f97316)",
    coverVariant: "crm",
    href: "/blog/crm-best-practices-service",
    cta: "Read guide",
  },
  {
    id: "bi-operators",
    title: "Business Intelligence for Operators",
    category: "Analytics",
    type: "Whitepaper",
    readTime: "21 min read",
    gradient: "linear-gradient(145deg, #06b6d4, #0891b2)",
    coverVariant: "analytics",
    href: "/blog/business-intelligence-for-operators",
    cta: "Read whitepaper",
  },
  {
    id: "analytics-decisions",
    title: "Analytics That Drive Decisions",
    category: "Analytics",
    type: "Guide",
    readTime: "12 min read",
    gradient: "linear-gradient(145deg, #3b82f6, #06b6d4)",
    coverVariant: "analytics",
    href: "/blog/analytics-that-drive-decisions",
    cta: "Read guide",
  },
  {
    id: "staff-management",
    title: "Staff Management Checklist",
    category: "Operations",
    type: "Checklist",
    readTime: "8 min read",
    gradient: "linear-gradient(145deg, #f59e0b, #f97316)",
    coverVariant: "staff",
    href: "/blog/staff-management-modern-ops",
    cta: "View checklist",
  },
  {
    id: "security-whitepaper",
    title: "Security by Design for Operators",
    category: "Security",
    type: "Whitepaper",
    readTime: "17 min read",
    gradient: "linear-gradient(145deg, #1e293b, #475569)",
    coverVariant: "security",
    href: "/blog/security-by-design-operators",
    cta: "Read whitepaper",
  },
  {
    id: "implementation-template",
    title: "Implementation Success Template",
    category: "Operations",
    type: "Template",
    readTime: "10 min read",
    gradient: "linear-gradient(145deg, #06b6d4, #3b82f6)",
    coverVariant: "operations",
    href: "/blog/implementation-that-sticks",
    cta: "Use template",
  },
  {
    id: "pos-workflow",
    title: "POS & Kitchen Workflow Guide",
    category: "POS",
    type: "Guide",
    readTime: "16 min read",
    gradient: "linear-gradient(145deg, #f97316, #ef4444)",
    coverVariant: "restaurant",
    href: "/help",
    cta: "Read guide",
  },
  {
    id: "finance-ops",
    title: "Finance Operations for Multi-Branch",
    category: "Finance",
    type: "Guide",
    readTime: "14 min read",
    gradient: "linear-gradient(145deg, #10b981, #059669)",
    coverVariant: "finance",
    href: "/platform",
    cta: "Read guide",
  },
  {
    id: "harbour-case-study",
    title: "Harbour Kitchen Group Case Study",
    category: "Operations",
    type: "Case Study",
    readTime: "11 min read",
    gradient: "linear-gradient(145deg, #3b82f6, #8b5cf6)",
    coverVariant: "restaurant",
    href: "/customer-success",
    cta: "Read case study",
  },
  {
    id: "northline-case-study",
    title: "Northline Retail Case Study",
    category: "Growth",
    type: "Case Study",
    readTime: "10 min read",
    gradient: "linear-gradient(145deg, #8b5cf6, #ec4899)",
    coverVariant: "retail",
    href: "/customer-success",
    cta: "Read case study",
  },
  {
    id: "ai-agents-video",
    title: "AI Agents in Practice",
    category: "AI",
    type: "Video",
    readTime: "7 min watch",
    gradient: "linear-gradient(145deg, #8b5cf6, #a855f7)",
    coverVariant: "ai",
    href: "/help#videos",
    cta: "Watch video",
  },
  {
    id: "platform-overview-video",
    title: "Busal OS Platform Overview",
    category: "Growth",
    type: "Video",
    readTime: "10 min watch",
    gradient: "linear-gradient(145deg, #3b82f6, #6366f1)",
    coverVariant: "product",
    href: "/help#videos",
    cta: "Watch video",
  },
  {
    id: "marketing-automation",
    title: "Marketing Automation Playbook",
    category: "Marketing",
    type: "Playbook",
    readTime: "18 min read",
    gradient: "linear-gradient(145deg, #a855f7, #ec4899)",
    coverVariant: "crm",
    href: "/blog/customer-loyalty-that-compounds",
    cta: "Read playbook",
  },
  {
    id: "integration-guide",
    title: "Integrations & API Quick Start",
    category: "AI",
    type: "Guide",
    readTime: "13 min read",
    gradient: "linear-gradient(145deg, #6366f1, #06b6d4)",
    coverVariant: "integration",
    href: "/help#developer",
    cta: "Read guide",
  },
];

export const FEATURED_RESOURCES = ALL_RESOURCES.filter((r) => r.featured);

export const FREE_DOWNLOADS = [
  {
    title: "Business Checklists",
    desc: "Daily, weekly, and monthly operator checklists for service businesses.",
    format: "PDF · 12 pages",
    category: "Operations",
  },
  {
    title: "Implementation Templates",
    desc: "Discovery, configuration, and go-live templates for Busal OS rollout.",
    format: "PDF · 18 pages",
    category: "Operations",
  },
  {
    title: "Business KPIs",
    desc: "Essential metrics for restaurants, retail, and hospitality operators.",
    format: "PDF · 8 pages",
    category: "Analytics",
  },
  {
    title: "AI Readiness Assessment",
    desc: "Score your operation's readiness for AI agents and automation.",
    format: "PDF · 6 pages",
    category: "AI",
  },
  {
    title: "Restaurant Startup Guide",
    desc: "From concept to first service—systems, staffing, and tech stack.",
    format: "PDF · 24 pages",
    category: "Operations",
  },
  {
    title: "Operations Checklist",
    desc: "Pre-service, service, and close-out workflows for multi-branch teams.",
    format: "PDF · 10 pages",
    category: "Operations",
  },
  {
    title: "CRM Segmentation Worksheet",
    desc: "Build guest segments from visit frequency, spend, and channel preference.",
    format: "PDF · 5 pages",
    category: "CRM",
  },
  {
    title: "Inventory Par Level Calculator",
    desc: "Set par levels and reorder points from velocity and lead time inputs.",
    format: "Spreadsheet · XLSX",
    category: "Inventory",
  },
  {
    title: "Security Review Checklist",
    desc: "Role, access, and audit review template for multi-location operators.",
    format: "PDF · 7 pages",
    category: "Security",
  },
  {
    title: "Go-Live Runbook",
    desc: "Hour-by-hour launch checklist for restaurants and retail branches.",
    format: "PDF · 14 pages",
    category: "Operations",
  },
] as const;

export const LEARNING_CENTER = [
  {
    type: "Articles",
    count: "13",
    desc: "Operator insights on AI, automation, and modern business software.",
    href: "/blog",
  },
  {
    type: "Guides",
    count: "21",
    desc: "Step-by-step playbooks for POS, CRM, inventory, and AI workflows.",
    href: "/help",
  },
  {
    type: "Case Studies",
    count: "6",
    desc: "Real businesses, measured outcomes—revenue, time saved, efficiency.",
    href: "/customer-success",
  },
  {
    type: "Videos",
    count: "8",
    desc: "Product walkthroughs, feature deep-dives, and operator tips.",
    href: "/help#videos",
  },
  {
    type: "Webinars",
    count: "4",
    desc: "Live sessions with Busal specialists and industry operators.",
    href: "/book-demo",
  },
  {
    type: "Whitepapers",
    count: "5",
    desc: "Enterprise architecture, security, and AI operating system strategy.",
    href: "/resources",
  },
] as const;

export const LATEST_INSIGHTS = [
  {
    slug: "busal-platform-summer-2026",
    title: "Busal Platform Summer 2026: what we shipped",
    excerpt:
      "AI Manager briefings, multi-location dashboard, predictive inventory, and customer portal refresh—now live.",
    author: "Busal Product Team",
    category: "Product Updates",
    readTime: "5 min",
    date: "Aug 1, 2026",
  },
  {
    slug: "ai-for-restaurants",
    title: "AI for restaurants: from hype to pre-service intelligence",
    excerpt:
      "How domain agents turn kitchen queues, covers, and margin signals into briefings managers act on.",
    author: "Sarah Chen",
    category: "Restaurants",
    readTime: "9 min",
    date: "Jul 22, 2026",
  },
  {
    slug: "retail-automation-without-chaos",
    title: "Retail automation without operational chaos",
    excerpt: "Automate replenishment, checkout, and CRM segments without losing merchant judgment.",
    author: "James Okonkwo",
    category: "Retail",
    readTime: "8 min",
    date: "Jul 8, 2026",
  },
  {
    slug: "inventory-optimization-guide",
    title: "Inventory optimization without spreadsheet drift",
    excerpt: "Purchase orders, low-stock alerts, and supplier continuity on one ledger.",
    author: "Amira Hassan",
    category: "Operations",
    readTime: "10 min",
    date: "Jun 18, 2026",
  },
] as const;

export const FEATURED_VIDEO = {
  title: "Busal OS in 10 Minutes",
  desc: "See how one AI operating system replaces POS, CRM, kitchen, inventory, and analytics—with live operational intelligence.",
  duration: "10:24",
  gradient: "linear-gradient(145deg, #3b82f6, #6366f1)",
  coverVariant: "product" as const,
} as const;
