import {
  MANAGER_PERMISSION_KEYS,
  OWNER_PERMISSION_KEYS,
  TENANT_PERMISSION_CATALOG,
} from "@/modules/tenant/constants/permissions";
import { INDUSTRIES } from "@/modules/tenant/types/industry";
import { DEFAULT_ROLE_SLUGS } from "@/modules/tenant/types/rbac";
import type {
  Branch,
  Business,
  Organization,
  StaffMember,
  Tenant,
  Workspace,
} from "@/modules/tenant/types/entities";
import type { Role } from "@/modules/tenant/types/rbac";

export const MOCK_TENANTS: Tenant[] = [
  {
    id: "tenant-harbour",
    slug: "harbour-group",
    name: "Harbour Group",
    industry: INDUSTRIES.RESTAURANT,
    status: "active",
    organizationId: "org-harbour",
    createdAt: "2025-01-10T10:00:00.000Z",
  },
  {
    id: "tenant-northside",
    slug: "northside-holdings",
    name: "Northside Holdings",
    industry: INDUSTRIES.RETAIL,
    status: "active",
    organizationId: "org-northside",
    createdAt: "2025-03-02T10:00:00.000Z",
  },
  {
    id: "tenant-atlas",
    slug: "atlas-wellness",
    name: "Atlas Wellness",
    industry: INDUSTRIES.SERVICES,
    status: "trial",
    organizationId: "org-atlas",
    createdAt: "2025-06-18T10:00:00.000Z",
  },
];

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: "org-harbour",
    tenantId: "tenant-harbour",
    slug: "harbour-org",
    name: "Harbour Organization",
    status: "active",
    createdAt: "2025-01-10T10:00:00.000Z",
  },
  {
    id: "org-northside",
    tenantId: "tenant-northside",
    slug: "northside-org",
    name: "Northside Organization",
    status: "active",
    createdAt: "2025-03-02T10:00:00.000Z",
  },
  {
    id: "org-atlas",
    tenantId: "tenant-atlas",
    slug: "atlas-org",
    name: "Atlas Organization",
    status: "active",
    createdAt: "2025-06-18T10:00:00.000Z",
  },
];

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: "ws-harbour-kitchen",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    businessId: "biz-harbour-kitchen",
    slug: "harbour-kitchen",
    name: "Harbour Kitchen",
    status: "active",
    createdAt: "2025-01-12T10:00:00.000Z",
  },
  {
    id: "ws-harbour-rooftop",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    businessId: "biz-harbour-rooftop",
    slug: "harbour-rooftop",
    name: "Harbour Rooftop",
    status: "active",
    createdAt: "2025-02-01T10:00:00.000Z",
  },
  {
    id: "ws-northside-retail",
    tenantId: "tenant-northside",
    organizationId: "org-northside",
    businessId: "biz-northside-retail",
    slug: "northside-retail",
    name: "Northside Retail",
    status: "active",
    createdAt: "2025-03-05T10:00:00.000Z",
  },
  {
    id: "ws-atlas-clinic",
    tenantId: "tenant-atlas",
    organizationId: "org-atlas",
    businessId: "biz-atlas-clinic",
    slug: "atlas-clinic",
    name: "Atlas Wellness Clinic",
    status: "provisioning",
    createdAt: "2025-06-20T10:00:00.000Z",
  },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "biz-harbour-kitchen",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    workspaceId: "ws-harbour-kitchen",
    slug: "harbour-kitchen",
    name: "Harbour Kitchen",
    industry: INDUSTRIES.RESTAURANT,
    status: "active",
    timezone: "Europe/London",
    currency: "GBP",
    createdAt: "2025-01-12T10:00:00.000Z",
  },
  {
    id: "biz-harbour-rooftop",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    workspaceId: "ws-harbour-rooftop",
    slug: "harbour-rooftop",
    name: "Harbour Rooftop",
    industry: INDUSTRIES.RESTAURANT,
    status: "active",
    timezone: "Europe/London",
    currency: "GBP",
    createdAt: "2025-02-01T10:00:00.000Z",
  },
  {
    id: "biz-northside-retail",
    tenantId: "tenant-northside",
    organizationId: "org-northside",
    workspaceId: "ws-northside-retail",
    slug: "northside-retail",
    name: "Northside Retail",
    industry: INDUSTRIES.RETAIL,
    status: "active",
    timezone: "Europe/London",
    currency: "GBP",
    createdAt: "2025-03-05T10:00:00.000Z",
  },
  {
    id: "biz-atlas-clinic",
    tenantId: "tenant-atlas",
    organizationId: "org-atlas",
    workspaceId: "ws-atlas-clinic",
    slug: "atlas-clinic",
    name: "Atlas Wellness Clinic",
    industry: INDUSTRIES.SERVICES,
    status: "pending",
    timezone: "Europe/Dublin",
    currency: "EUR",
    createdAt: "2025-06-20T10:00:00.000Z",
  },
];

export const MOCK_BRANCHES: Branch[] = [
  {
    id: "branch-harbour-main",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    workspaceId: "ws-harbour-kitchen",
    businessId: "biz-harbour-kitchen",
    slug: "main",
    name: "Main Dining",
    status: "active",
    isMain: true,
    timezone: "Europe/London",
    createdAt: "2025-01-12T10:00:00.000Z",
  },
  {
    id: "branch-harbour-harbourfront",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    workspaceId: "ws-harbour-kitchen",
    businessId: "biz-harbour-kitchen",
    slug: "harbourfront",
    name: "Harbourfront",
    status: "active",
    isMain: false,
    timezone: "Europe/London",
    createdAt: "2025-01-20T10:00:00.000Z",
  },
  {
    id: "branch-rooftop-main",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    workspaceId: "ws-harbour-rooftop",
    businessId: "biz-harbour-rooftop",
    slug: "main",
    name: "Rooftop Main",
    status: "active",
    isMain: true,
    timezone: "Europe/London",
    createdAt: "2025-02-01T10:00:00.000Z",
  },
  {
    id: "branch-northside-flagship",
    tenantId: "tenant-northside",
    organizationId: "org-northside",
    workspaceId: "ws-northside-retail",
    businessId: "biz-northside-retail",
    slug: "flagship",
    name: "Flagship Store",
    status: "active",
    isMain: true,
    timezone: "Europe/London",
    createdAt: "2025-03-05T10:00:00.000Z",
  },
  {
    id: "branch-northside-outlet",
    tenantId: "tenant-northside",
    organizationId: "org-northside",
    workspaceId: "ws-northside-retail",
    businessId: "biz-northside-retail",
    slug: "outlet",
    name: "Outlet",
    status: "active",
    isMain: false,
    timezone: "Europe/London",
    createdAt: "2025-04-01T10:00:00.000Z",
  },
  {
    id: "branch-atlas-main",
    tenantId: "tenant-atlas",
    organizationId: "org-atlas",
    workspaceId: "ws-atlas-clinic",
    businessId: "biz-atlas-clinic",
    slug: "main",
    name: "Clinic Main",
    status: "active",
    isMain: true,
    timezone: "Europe/Dublin",
    createdAt: "2025-06-20T10:00:00.000Z",
  },
];

export const MOCK_ROLES: Role[] = [
  {
    id: "role-owner-harbour-kitchen",
    slug: DEFAULT_ROLE_SLUGS.OWNER,
    name: "Owner",
    description: "Full workspace ownership",
    workspaceId: "ws-harbour-kitchen",
    permissionKeys: [...OWNER_PERMISSION_KEYS],
    isSystem: true,
  },
  {
    id: "role-manager-harbour-kitchen",
    slug: DEFAULT_ROLE_SLUGS.MANAGER,
    name: "Manager",
    description: "Day-to-day operations",
    workspaceId: "ws-harbour-kitchen",
    permissionKeys: [...MANAGER_PERMISSION_KEYS],
    isSystem: true,
  },
  {
    id: "role-owner-northside",
    slug: DEFAULT_ROLE_SLUGS.OWNER,
    name: "Owner",
    description: "Full workspace ownership",
    workspaceId: "ws-northside-retail",
    permissionKeys: [...OWNER_PERMISSION_KEYS],
    isSystem: true,
  },
  {
    id: "role-owner-atlas",
    slug: DEFAULT_ROLE_SLUGS.OWNER,
    name: "Owner",
    description: "Full workspace ownership",
    workspaceId: "ws-atlas-clinic",
    permissionKeys: [...OWNER_PERMISSION_KEYS],
    isSystem: true,
  },
];

export const MOCK_STAFF: StaffMember[] = [
  {
    id: "staff-harbour-owner",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    workspaceId: "ws-harbour-kitchen",
    businessId: "biz-harbour-kitchen",
    branchId: "branch-harbour-main",
    userId: "user-harbour-owner",
    email: "owner@harbour.example",
    fullName: "Alex Harbour",
    roleSlug: DEFAULT_ROLE_SLUGS.OWNER,
    status: "active",
    permissionKeys: [...OWNER_PERMISSION_KEYS],
    createdAt: "2025-01-12T10:00:00.000Z",
  },
  {
    id: "staff-harbour-manager",
    tenantId: "tenant-harbour",
    organizationId: "org-harbour",
    workspaceId: "ws-harbour-kitchen",
    businessId: "biz-harbour-kitchen",
    branchId: "branch-harbour-harbourfront",
    userId: "user-harbour-manager",
    email: "manager@harbour.example",
    fullName: "Sam Rivera",
    roleSlug: DEFAULT_ROLE_SLUGS.MANAGER,
    status: "active",
    permissionKeys: [...MANAGER_PERMISSION_KEYS],
    createdAt: "2025-01-15T10:00:00.000Z",
  },
  {
    id: "staff-northside-owner",
    tenantId: "tenant-northside",
    organizationId: "org-northside",
    workspaceId: "ws-northside-retail",
    businessId: "biz-northside-retail",
    branchId: "branch-northside-flagship",
    userId: "user-northside-owner",
    email: "owner@northside.example",
    fullName: "Jordan Lee",
    roleSlug: DEFAULT_ROLE_SLUGS.OWNER,
    status: "active",
    permissionKeys: [...OWNER_PERMISSION_KEYS],
    createdAt: "2025-03-05T10:00:00.000Z",
  },
  {
    id: "staff-atlas-owner",
    tenantId: "tenant-atlas",
    organizationId: "org-atlas",
    workspaceId: "ws-atlas-clinic",
    businessId: "biz-atlas-clinic",
    branchId: "branch-atlas-main",
    userId: "user-atlas-owner",
    email: "owner@atlas.example",
    fullName: "Casey Quinn",
    roleSlug: DEFAULT_ROLE_SLUGS.OWNER,
    status: "active",
    permissionKeys: [...OWNER_PERMISSION_KEYS],
    createdAt: "2025-06-20T10:00:00.000Z",
  },
];

export const MOCK_PERMISSIONS = TENANT_PERMISSION_CATALOG;

export const DEFAULT_MOCK_SELECTION = {
  tenantId: "tenant-harbour",
  organizationId: "org-harbour",
  workspaceId: "ws-harbour-kitchen",
  businessId: "biz-harbour-kitchen",
  branchId: "branch-harbour-main",
} as const;
