import {
  ACCOUNT_NORMAL_BALANCE,
  ACCOUNT_TYPES,
  EXPENSE_CATEGORIES,
  FINANCE_PAYMENT_METHODS,
  FINANCE_TRANSACTION_TYPES,
  FINANCIAL_PERIOD_STATUSES,
  INVOICE_STATUSES,
  JOURNAL_ENTRY_STATUSES,
  TAX_TYPES,
} from "@/modules/finance/constants/finance-status";
import type {
  BankAccount,
  ChartOfAccount,
  FinanceRecord,
  FinancialPeriod,
  Invoice,
} from "@/modules/finance/types/finance-platform";

export const DEFAULT_FINANCE_SCOPE = {
  tenantId: "tenant-harbour",
  workspaceId: "ws-harbour-kitchen",
  businessId: "biz-harbour-kitchen",
  branchId: "branch-harbour-main",
  userId: "user-harbour-owner",
  currentPeriodId: "period-2026-02",
  baseCurrency: "GBP",
} as const;

const NOW = "2026-02-15T22:00:00.000Z";

export const MOCK_FINANCIAL_PERIOD: FinancialPeriod = {
  id: DEFAULT_FINANCE_SCOPE.currentPeriodId,
  tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
  businessId: DEFAULT_FINANCE_SCOPE.businessId,
  name: "February 2026",
  startDate: "2026-02-01",
  endDate: "2026-02-28",
  status: FINANCIAL_PERIOD_STATUSES.OPEN,
  fiscalYear: 2026,
  isCurrent: true,
};

export const MOCK_CHART_OF_ACCOUNTS: ChartOfAccount[] = [
  {
    id: "acct-cash",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    code: "1000",
    name: "Cash on Hand",
    accountType: ACCOUNT_TYPES.ASSET,
    normalBalance: ACCOUNT_NORMAL_BALANCE.DEBIT,
    parentAccountId: null,
    currency: "GBP",
    isActive: true,
    isSystemAccount: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "acct-bank",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    code: "1010",
    name: "Business Bank Account",
    accountType: ACCOUNT_TYPES.ASSET,
    normalBalance: ACCOUNT_NORMAL_BALANCE.DEBIT,
    parentAccountId: null,
    currency: "GBP",
    isActive: true,
    isSystemAccount: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "acct-ar",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    code: "1200",
    name: "Accounts Receivable",
    accountType: ACCOUNT_TYPES.ASSET,
    normalBalance: ACCOUNT_NORMAL_BALANCE.DEBIT,
    parentAccountId: null,
    currency: "GBP",
    isActive: true,
    isSystemAccount: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "acct-ap",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    code: "2000",
    name: "Accounts Payable",
    accountType: ACCOUNT_TYPES.LIABILITY,
    normalBalance: ACCOUNT_NORMAL_BALANCE.CREDIT,
    parentAccountId: null,
    currency: "GBP",
    isActive: true,
    isSystemAccount: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "acct-revenue",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    code: "4000",
    name: "Sales Revenue",
    accountType: ACCOUNT_TYPES.REVENUE,
    normalBalance: ACCOUNT_NORMAL_BALANCE.CREDIT,
    parentAccountId: null,
    currency: "GBP",
    isActive: true,
    isSystemAccount: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "acct-cogs",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    code: "5000",
    name: "Cost of Goods Sold",
    accountType: ACCOUNT_TYPES.EXPENSE,
    normalBalance: ACCOUNT_NORMAL_BALANCE.DEBIT,
    parentAccountId: null,
    currency: "GBP",
    isActive: true,
    isSystemAccount: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "acct-payroll",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    code: "6100",
    name: "Payroll Expense",
    accountType: ACCOUNT_TYPES.EXPENSE,
    normalBalance: ACCOUNT_NORMAL_BALANCE.DEBIT,
    parentAccountId: null,
    currency: "GBP",
    isActive: true,
    isSystemAccount: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "acct-vat",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    code: "2200",
    name: "VAT Payable",
    accountType: ACCOUNT_TYPES.LIABILITY,
    normalBalance: ACCOUNT_NORMAL_BALANCE.CREDIT,
    parentAccountId: null,
    currency: "GBP",
    isActive: true,
    isSystemAccount: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const MOCK_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: "bank-main",
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    accountName: "Operating Account",
    bankName: "Barclays",
    accountNumberLast4: "4521",
    sortCode: "20-00-00",
    currency: "GBP",
    currentBalanceCents: 12500000,
    ledgerAccountId: "acct-bank",
    isActive: true,
  },
];

function buildInvoice(partial: {
  id: string;
  invoiceNumber: string;
  customerName: string;
  status: (typeof INVOICE_STATUSES)[keyof typeof INVOICE_STATUSES];
  subtotalCents: number;
  paidCents?: number;
}): Invoice {
  const taxCents = Math.round(partial.subtotalCents * 0.2);
  const totalCents = partial.subtotalCents + taxCents;
  const paid = partial.paidCents ?? (partial.status === INVOICE_STATUSES.PAID ? totalCents : 0);

  return {
    id: partial.id,
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    branchId: DEFAULT_FINANCE_SCOPE.branchId,
    invoiceNumber: partial.invoiceNumber,
    status: partial.status,
    customerId: null,
    customerName: partial.customerName,
    issueDate: "2026-02-10",
    dueDate: "2026-02-24",
    subtotalCents: partial.subtotalCents,
    taxCents,
    discountCents: 0,
    totalCents,
    amountPaidCents: paid,
    amountDueCents: totalCents - paid,
    currency: "GBP",
    lineItems: [
      {
        id: `line-${partial.id}`,
        invoiceId: partial.id,
        description: "Catering services",
        quantity: 1,
        unitPriceCents: partial.subtotalCents,
        taxCents,
        totalCents,
      },
    ],
    notes: null,
    createdAt: NOW,
    updatedAt: NOW,
  };
}

export const MOCK_FINANCE_RECORD: FinanceRecord = {
  period: MOCK_FINANCIAL_PERIOD,
  chartOfAccounts: MOCK_CHART_OF_ACCOUNTS,
  ledgers: [
    {
      id: "ledger-cash",
      accountId: "acct-cash",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
      openingBalanceCents: 450000,
      debitTotalCents: 2850000,
      creditTotalCents: 1200000,
      closingBalanceCents: 2100000,
      currency: "GBP",
      entryCount: 42,
      updatedAt: NOW,
    },
    {
      id: "ledger-revenue",
      accountId: "acct-revenue",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
      openingBalanceCents: 0,
      debitTotalCents: 0,
      creditTotalCents: 4850000,
      closingBalanceCents: 4850000,
      currency: "GBP",
      entryCount: 38,
      updatedAt: NOW,
    },
  ],
  journalEntries: [
    {
      id: "je-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      entryNumber: "JE-2026-0042",
      status: JOURNAL_ENTRY_STATUSES.POSTED,
      description: "Daily POS sales",
      referenceType: "pos",
      referenceId: "pos-batch-001",
      periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
      lines: [
        {
          id: "jel-001-a",
          journalEntryId: "je-001",
          accountId: "acct-cash",
          accountCode: "1000",
          description: "Cash sales",
          debitCents: 125000,
          creditCents: 0,
        },
        {
          id: "jel-001-b",
          journalEntryId: "je-001",
          accountId: "acct-revenue",
          accountCode: "4000",
          description: "Sales revenue",
          debitCents: 0,
          creditCents: 104167,
        },
        {
          id: "jel-001-c",
          journalEntryId: "je-001",
          accountId: "acct-vat",
          accountCode: "2200",
          description: "VAT on sales",
          debitCents: 0,
          creditCents: 20833,
        },
      ],
      postedAt: NOW,
      createdByUserId: DEFAULT_FINANCE_SCOPE.userId,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],
  transactions: [
    {
      id: "txn-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      transactionType: FINANCE_TRANSACTION_TYPES.SALE,
      amountCents: 125000,
      currency: "GBP",
      journalEntryId: "je-001",
      referenceType: "pos",
      referenceId: "pos-batch-001",
      description: "Daily POS sales",
      occurredAt: NOW,
      createdByUserId: DEFAULT_FINANCE_SCOPE.userId,
    },
    {
      id: "txn-002",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      transactionType: FINANCE_TRANSACTION_TYPES.EXPENSE,
      amountCents: 85000,
      currency: "GBP",
      journalEntryId: null,
      referenceType: "expense",
      referenceId: "exp-001",
      description: "Fresh produce supplier payment",
      occurredAt: "2026-02-14T10:00:00.000Z",
      createdByUserId: DEFAULT_FINANCE_SCOPE.userId,
    },
  ],
  invoices: [
    buildInvoice({
      id: "inv-001",
      invoiceNumber: "INV-2026-0012",
      customerName: "Harbour Events Ltd",
      status: INVOICE_STATUSES.PAID,
      subtotalCents: 250000,
    }),
    buildInvoice({
      id: "inv-002",
      invoiceNumber: "INV-2026-0013",
      customerName: "Coastal Catering Co",
      status: INVOICE_STATUSES.SENT,
      subtotalCents: 180000,
    }),
    buildInvoice({
      id: "inv-003",
      invoiceNumber: "INV-2026-0014",
      customerName: "Private Dining — Table 12",
      status: INVOICE_STATUSES.OVERDUE,
      subtotalCents: 95000,
      paidCents: 0,
    }),
  ],
  payments: [
    {
      id: "pay-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      paymentMethod: FINANCE_PAYMENT_METHODS.BANK_TRANSFER,
      amountCents: 300000,
      currency: "GBP",
      invoiceId: "inv-001",
      reference: "BACS-HARBOUR-001",
      paidAt: "2026-02-12T14:00:00.000Z",
      recordedByUserId: DEFAULT_FINANCE_SCOPE.userId,
    },
  ],
  refunds: [
    {
      id: "ref-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      paymentId: "pay-pos-001",
      invoiceId: null,
      refundNumber: "RF-2026-0003",
      amountCents: 3500,
      currency: "GBP",
      reason: "Order cancelled",
      refundedAt: "2026-02-13T16:00:00.000Z",
      approvedByUserId: DEFAULT_FINANCE_SCOPE.userId,
    },
  ],
  expenses: [
    {
      id: "exp-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      category: EXPENSE_CATEGORIES.COGS,
      vendorName: "Fresh Fields Produce",
      description: "Weekly produce delivery",
      amountCents: 85000,
      taxCents: 17000,
      totalCents: 102000,
      currency: "GBP",
      expenseDate: "2026-02-14",
      accountId: "acct-cogs",
      receiptUrl: null,
      approvedByUserId: DEFAULT_FINANCE_SCOPE.userId,
      createdAt: NOW,
    },
    {
      id: "exp-002",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      category: EXPENSE_CATEGORIES.PAYROLL,
      vendorName: "Internal Payroll",
      description: "February payroll — week 2",
      amountCents: 1250000,
      taxCents: 0,
      totalCents: 1250000,
      currency: "GBP",
      expenseDate: "2026-02-14",
      accountId: "acct-payroll",
      receiptUrl: null,
      approvedByUserId: DEFAULT_FINANCE_SCOPE.userId,
      createdAt: NOW,
    },
    {
      id: "exp-003",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      category: EXPENSE_CATEGORIES.RENT,
      vendorName: "Harbour Properties",
      description: "Monthly rent — February",
      amountCents: 450000,
      taxCents: 90000,
      totalCents: 540000,
      currency: "GBP",
      expenseDate: "2026-02-01",
      accountId: "acct-cogs",
      receiptUrl: null,
      approvedByUserId: DEFAULT_FINANCE_SCOPE.userId,
      createdAt: NOW,
    },
  ],
  income: [
    {
      id: "inc-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      source: "POS Sales",
      description: "Dine-in and takeaway sales",
      amountCents: 4200000,
      taxCents: 840000,
      totalCents: 5040000,
      currency: "GBP",
      incomeDate: "2026-02-01",
      accountId: "acct-revenue",
      createdAt: NOW,
    },
  ],
  taxes: [
    {
      id: "tax-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      taxType: TAX_TYPES.VAT,
      name: "VAT — February 2026",
      rateBps: 2000,
      taxableAmountCents: 4850000,
      taxAmountCents: 970000,
      periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
      jurisdiction: "GB",
      isPaid: false,
      dueDate: "2026-03-07",
    },
  ],
  cashRegisters: [
    {
      id: "cr-main",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      registerId: "register-main",
      name: "Main Register",
      currentBalanceCents: 78500,
      expectedBalanceCents: 78000,
      currency: "GBP",
      lastReconciledAt: NOW,
    },
  ],
  bankAccounts: MOCK_BANK_ACCOUNTS,
  payrollTransactions: [
    {
      id: "payroll-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      staffId: "staff-manager-1",
      payPeriodStart: "2026-02-01",
      payPeriodEnd: "2026-02-14",
      grossPayCents: 173077,
      taxCents: 34615,
      deductionsCents: 5000,
      netPayCents: 133462,
      currency: "GBP",
      status: "paid",
      processedAt: "2026-02-14T09:00:00.000Z",
    },
  ],
  supplierPayments: [
    {
      id: "sp-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      supplierId: "supplier-fresh-produce",
      supplierName: "Fresh Fields Produce",
      purchaseOrderId: "po-001",
      amountCents: 102000,
      currency: "GBP",
      paymentMethod: FINANCE_PAYMENT_METHODS.BANK_TRANSFER,
      paidAt: "2026-02-14T11:00:00.000Z",
      reference: "BACS-FF-001",
    },
  ],
  customerPayments: [
    {
      id: "cp-001",
      tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
      businessId: DEFAULT_FINANCE_SCOPE.businessId,
      branchId: DEFAULT_FINANCE_SCOPE.branchId,
      customerId: "cust-harbour-events",
      customerName: "Harbour Events Ltd",
      invoiceId: "inv-001",
      amountCents: 300000,
      currency: "GBP",
      paymentMethod: FINANCE_PAYMENT_METHODS.BANK_TRANSFER,
      receivedAt: "2026-02-12T14:00:00.000Z",
      reference: "BACS-HARBOUR-001",
    },
  ],
  profitAndLoss: {
    periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    revenueCents: 4850000,
    cogsCents: 1785000,
    grossProfitCents: 3065000,
    operatingExpensesCents: 2145000,
    netProfitCents: 920000,
    currency: "GBP",
    generatedAt: NOW,
  },
  balanceSheet: {
    periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    assetsCents: 14850000,
    liabilitiesCents: 3200000,
    equityCents: 11650000,
    currency: "GBP",
    generatedAt: NOW,
  },
  cashFlow: {
    periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
    tenantId: DEFAULT_FINANCE_SCOPE.tenantId,
    businessId: DEFAULT_FINANCE_SCOPE.businessId,
    operatingCents: 850000,
    investingCents: -120000,
    financingCents: -450000,
    netCashChangeCents: 280000,
    openingCashCents: 450000,
    closingCashCents: 730000,
    currency: "GBP",
    generatedAt: NOW,
  },
  analytics: {
    periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
    revenueCents: 4850000,
    expenseCents: 3930000,
    netProfitCents: 920000,
    grossMarginBps: 6319,
    netMarginBps: 1897,
    accountsReceivableCents: 330000,
    accountsPayableCents: 520000,
    cashOnHandCents: 2100000,
    anomalyScore: 0.12,
  },
  aiContext: {
    periodId: DEFAULT_FINANCE_SCOPE.currentPeriodId,
    summary: "February 2026 — Net profit £9,200, gross margin 63%",
    revenueForecastCents: 5200000,
    cashFlowForecastCents: 950000,
    anomalyRiskScore: 0.12,
    costSavingOpportunitiesCents: 85000,
    insights: ["COGS ratio stable at 37%", "One overdue invoice — £1,140"],
    recommendedActions: ["Follow up on INV-2026-0014", "Review utility contracts for savings"],
    lastGeneratedAt: NOW,
  },
};
