import { PERMISSION_CODES } from "@/modules/authorization/constants/permissions";
import { registerMarketplaceExtension } from "@/modules/marketplace/registry/marketplace-registry";
import { BUSAL_PLATFORM_VERSION } from "@/modules/marketplace/constants/routes";

const CATALOGUE_ITEMS = [
  {
    slug: "sales-ai-agent-pack",
    name: "Sales AI Agent Pack",
    description: "Pre-built sales agents with CRM and lead nurture workflows.",
    category: "AI_AGENTS" as const,
    publisherSlug: "busal-labs",
    pricingType: "PAID" as const,
    priceCents: 4900,
    licenseType: "MONTHLY" as const,
    screenshots: ["/marketplace/sales-ai-agent.png"],
    dependencies: [],
    permissionsRequired: [PERMISSION_CODES.AI_AGENT_VIEW, PERMISSION_CODES.AI_AGENT_DEPLOY],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: ["ai-agents", "sales-crm"],
    requiredIndustries: [],
    requiresAi: true,
    changelog: "Initial release with sales and CRM agents.",
    versionLabel: "1.0.0",
  },
  {
    slug: "stripe-integration",
    name: "Stripe Integration",
    description: "Connect Stripe payments and subscription billing.",
    category: "INTEGRATIONS" as const,
    publisherSlug: "busal-labs",
    pricingType: "FREE" as const,
    priceCents: 0,
    licenseType: "FREE" as const,
    screenshots: ["/marketplace/stripe-integration.png"],
    dependencies: [],
    permissionsRequired: [PERMISSION_CODES.REVOPS_PAYMENTS_MANAGE],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: ["payments", "revops"],
    requiredIndustries: [],
    requiresAi: false,
    changelog: "Stripe webhook and payment sync support.",
    versionLabel: "1.0.0",
  },
  {
    slug: "restaurant-industry-pack",
    name: "Restaurant Industry Pack",
    description: "Menu, kitchen, reservations, and POS enhancements for restaurants.",
    category: "INDUSTRY_PACKS" as const,
    publisherSlug: "busal-labs",
    pricingType: "PAID" as const,
    priceCents: 9900,
    licenseType: "ANNUAL" as const,
    screenshots: ["/marketplace/restaurant-pack.png"],
    dependencies: [],
    permissionsRequired: [PERMISSION_CODES.MENU_VIEW, PERMISSION_CODES.KITCHEN_VIEW],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: ["menu", "kitchen", "reservations", "pos"],
    requiredIndustries: ["restaurant"],
    requiresAi: false,
    changelog: "Restaurant workflows and dashboard presets.",
    versionLabel: "1.0.0",
  },
  {
    slug: "modern-dark-theme",
    name: "Modern Dark Theme",
    description: "Premium dark theme for dashboard and POS surfaces.",
    category: "THEMES" as const,
    publisherSlug: "busal-labs",
    pricingType: "FREE" as const,
    priceCents: 0,
    licenseType: "FREE" as const,
    screenshots: ["/marketplace/dark-theme.png"],
    dependencies: [],
    permissionsRequired: [],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: [],
    requiredIndustries: [],
    requiresAi: false,
    changelog: "Dark mode palette and typography.",
    versionLabel: "1.0.0",
  },
  {
    slug: "invoice-overdue-workflow-pack",
    name: "Invoice Overdue Workflow Pack",
    description: "Automation workflows for overdue invoice reminders.",
    category: "WORKFLOW_PACKS" as const,
    publisherSlug: "busal-labs",
    pricingType: "FREE" as const,
    priceCents: 0,
    licenseType: "FREE" as const,
    screenshots: ["/marketplace/workflow-pack.png"],
    dependencies: [],
    permissionsRequired: [PERMISSION_CODES.AI_AUTOMATION_VIEW],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: ["ai-automation", "revops"],
    requiredIndustries: [],
    requiresAi: true,
    changelog: "Overdue invoice reminder automations.",
    versionLabel: "1.0.0",
  },
  {
    slug: "executive-dashboard-pack",
    name: "Executive Dashboard Pack",
    description: "KPI dashboards for owners and managers.",
    category: "DASHBOARD_PACKS" as const,
    publisherSlug: "busal-labs",
    pricingType: "PAID" as const,
    priceCents: 2900,
    licenseType: "MONTHLY" as const,
    screenshots: ["/marketplace/dashboard-pack.png"],
    dependencies: [],
    permissionsRequired: [PERMISSION_CODES.ANALYTICS_VIEW],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: ["reporting"],
    requiredIndustries: [],
    requiresAi: false,
    changelog: "Executive KPI widgets and layouts.",
    versionLabel: "1.0.0",
  },
  {
    slug: "revops-report-pack",
    name: "RevOps Report Pack",
    description: "Revenue, forecast, and invoice reporting templates.",
    category: "REPORT_PACKS" as const,
    publisherSlug: "busal-labs",
    pricingType: "PAID" as const,
    priceCents: 1900,
    licenseType: "MONTHLY" as const,
    screenshots: ["/marketplace/report-pack.png"],
    dependencies: [],
    permissionsRequired: [PERMISSION_CODES.REVENUE_VIEW],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: ["revops", "reporting"],
    requiredIndustries: [],
    requiresAi: false,
    changelog: "RevOps report templates and exports.",
    versionLabel: "1.0.0",
  },
  {
    slug: "proposal-document-templates",
    name: "Proposal Document Templates",
    description: "Professional proposal and quote document templates.",
    category: "DOCUMENT_TEMPLATES" as const,
    publisherSlug: "busal-labs",
    pricingType: "FREE" as const,
    priceCents: 0,
    licenseType: "FREE" as const,
    screenshots: ["/marketplace/document-templates.png"],
    dependencies: [],
    permissionsRequired: [PERMISSION_CODES.PROPOSALS_MANAGE],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: ["quotes"],
    requiredIndustries: [],
    requiresAi: false,
    changelog: "Proposal and quote PDF templates.",
    versionLabel: "1.0.0",
  },
  {
    slug: "inventory-plugin",
    name: "Inventory Sync Plugin",
    description: "Low-stock alerts and supplier sync plugin.",
    category: "PLUGINS" as const,
    publisherSlug: "busal-labs",
    pricingType: "FREE" as const,
    priceCents: 0,
    licenseType: "FREE" as const,
    screenshots: ["/marketplace/inventory-plugin.png"],
    dependencies: [],
    permissionsRequired: [PERMISSION_CODES.INVENTORY_VIEW],
    minBusalVersion: BUSAL_PLATFORM_VERSION,
    requiredModules: ["inventory"],
    requiredIndustries: [],
    requiresAi: false,
    changelog: "Inventory sync and alert plugin.",
    versionLabel: "1.0.0",
  },
] as const;

export function registerBootstrapMarketplaceExtensions(): void {
  for (const item of CATALOGUE_ITEMS) {
    registerMarketplaceExtension({
      slug: item.slug,
      name: item.name,
      description: item.description,
      category: item.category,
      publisherSlug: item.publisherSlug,
      pricingType: item.pricingType,
      priceCents: item.priceCents,
      licenseType: item.licenseType,
      screenshots: [...item.screenshots],
      dependencies: [...item.dependencies],
      permissionsRequired: [...item.permissionsRequired],
      minBusalVersion: item.minBusalVersion,
      requiredModules: [...item.requiredModules],
      requiredIndustries: [...item.requiredIndustries],
      requiresAi: item.requiresAi,
      changelog: item.changelog,
      versionLabel: item.versionLabel,
    });
  }
}

let bootstrapComplete = false;

export function ensureBootstrapMarketplacePlugins(): void {
  if (bootstrapComplete) {
    return;
  }

  registerBootstrapMarketplaceExtensions();
  bootstrapComplete = true;
}

export { CATALOGUE_ITEMS as DEFAULT_MARKETPLACE_CATALOGUE };
