import {
  ATTENDANCE_STATUSES,
  EMPLOYMENT_STATUSES,
  LEAVE_STATUSES,
  LEAVE_TYPES,
  PAYROLL_FREQUENCIES,
  PERFORMANCE_RATINGS,
  STAFF_ACTIVITY_EVENT_TYPES,
  STAFF_DEPARTMENTS,
  STAFF_SHIFT_STATUSES,
  TRAINING_STATUSES,
} from "@/modules/staff/constants/staff-status";
import type { Department, Designation, StaffRecord } from "@/modules/staff/types/staff-platform";

export const DEFAULT_STAFF_SCOPE = {
  tenantId: "tenant-harbour",
  workspaceId: "ws-harbour-kitchen",
  businessId: "biz-harbour-kitchen",
  branchId: "branch-harbour-main",
  userId: "user-harbour-owner",
  managerStaffId: "staff-manager-1",
} as const;

const NOW = "2026-02-15T21:00:00.000Z";

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: "dept-management",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    name: "Management",
    departmentType: STAFF_DEPARTMENTS.MANAGEMENT,
    customLabel: null,
    displayOrder: 1,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "dept-kitchen",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    name: "Kitchen",
    departmentType: STAFF_DEPARTMENTS.KITCHEN,
    customLabel: null,
    displayOrder: 2,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "dept-service",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    name: "Service",
    departmentType: STAFF_DEPARTMENTS.SERVICE,
    customLabel: null,
    displayOrder: 3,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "dept-delivery",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    name: "Delivery",
    departmentType: STAFF_DEPARTMENTS.DELIVERY,
    customLabel: null,
    displayOrder: 4,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "dept-hr",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    name: "Human Resources",
    departmentType: STAFF_DEPARTMENTS.HR,
    customLabel: null,
    displayOrder: 5,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const MOCK_DESIGNATIONS: Designation[] = [
  {
    id: "desig-gm",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    departmentId: "dept-management",
    title: "General Manager",
    level: 5,
    description: "Overall restaurant operations",
    isActive: true,
  },
  {
    id: "desig-head-chef",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    departmentId: "dept-kitchen",
    title: "Head Chef",
    level: 4,
    description: "Kitchen leadership",
    isActive: true,
  },
  {
    id: "desig-line-cook",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    departmentId: "dept-kitchen",
    title: "Line Cook",
    level: 2,
    description: "Food preparation",
    isActive: true,
  },
  {
    id: "desig-server",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    departmentId: "dept-service",
    title: "Server",
    level: 2,
    description: "Front-of-house service",
    isActive: true,
  },
  {
    id: "desig-cashier",
    tenantId: DEFAULT_STAFF_SCOPE.tenantId,
    businessId: DEFAULT_STAFF_SCOPE.businessId,
    departmentId: "dept-service",
    title: "Cashier",
    level: 2,
    description: "POS and payments",
    isActive: true,
  },
];

function buildRecord(partial: {
  id: string;
  employeeNumber: string;
  firstName: string;
  lastName: string;
  email: string;
  departmentId: string;
  designationId: string;
  employmentStatus: (typeof EMPLOYMENT_STATUSES)[keyof typeof EMPLOYMENT_STATUSES];
  hourlyRateCents?: number;
  salaryCents?: number;
  hasPendingLeave?: boolean;
  hasLateAttendance?: boolean;
  isManager?: boolean;
}): StaffRecord {
  const department = MOCK_DEPARTMENTS.find((d) => d.id === partial.departmentId)!;
  const designation = MOCK_DESIGNATIONS.find((d) => d.id === partial.designationId)!;
  const displayName = `${partial.firstName} ${partial.lastName}`;

  return {
    member: {
      id: partial.id,
      tenantId: DEFAULT_STAFF_SCOPE.tenantId,
      workspaceId: DEFAULT_STAFF_SCOPE.workspaceId,
      businessId: DEFAULT_STAFF_SCOPE.businessId,
      userId: partial.isManager ? DEFAULT_STAFF_SCOPE.userId : null,
      employeeNumber: partial.employeeNumber,
      firstName: partial.firstName,
      lastName: partial.lastName,
      displayName,
      email: partial.email,
      phone: "+44 7700 900123",
      avatarUrl: null,
      employmentStatus: partial.employmentStatus,
      hireDate: "2024-06-01",
      terminationDate: null,
      isActive: partial.employmentStatus === EMPLOYMENT_STATUSES.ACTIVE,
      createdAt: NOW,
      updatedAt: NOW,
    },
    profile: {
      staffId: partial.id,
      dateOfBirth: "1990-05-15",
      nationalId: null,
      address: "12 Harbour Street",
      city: "London",
      postcode: "E1 6AN",
      country: "GB",
      departmentId: partial.departmentId,
      designationId: partial.designationId,
      managerStaffId: partial.isManager ? null : DEFAULT_STAFF_SCOPE.managerStaffId,
      bio: null,
      preferredLanguage: "en-GB",
      timezone: "Europe/London",
    },
    department,
    designation,
    branchAssignments: [
      {
        id: `ba-${partial.id}`,
        staffId: partial.id,
        branchId: DEFAULT_STAFF_SCOPE.branchId,
        branchName: "Main Branch",
        isPrimary: true,
        assignedAt: "2024-06-01T00:00:00.000Z",
        assignedByStaffId: DEFAULT_STAFF_SCOPE.managerStaffId,
      },
    ],
    roleAssignments: [
      {
        id: `ra-${partial.id}`,
        staffId: partial.id,
        roleId: partial.isManager ? "role-manager" : "role-staff",
        roleName: partial.isManager ? "Manager" : "Staff",
        scope: "branch",
        scopeId: DEFAULT_STAFF_SCOPE.branchId,
        assignedAt: "2024-06-01T00:00:00.000Z",
        assignedByStaffId: DEFAULT_STAFF_SCOPE.managerStaffId,
        expiresAt: null,
      },
    ],
    permissionAssignments: [],
    shifts: [
      {
        id: `shift-${partial.id}-today`,
        tenantId: DEFAULT_STAFF_SCOPE.tenantId,
        businessId: DEFAULT_STAFF_SCOPE.businessId,
        branchId: DEFAULT_STAFF_SCOPE.branchId,
        staffId: partial.id,
        scheduleId: null,
        status: STAFF_SHIFT_STATUSES.SCHEDULED,
        shiftDate: "2026-02-15",
        startTime: "10:00",
        endTime: "18:00",
        breakMinutes: 30,
        roleId: partial.isManager ? "role-manager" : "role-staff",
        notes: null,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    schedules: [
      {
        id: `sched-${partial.id}`,
        tenantId: DEFAULT_STAFF_SCOPE.tenantId,
        businessId: DEFAULT_STAFF_SCOPE.businessId,
        branchId: DEFAULT_STAFF_SCOPE.branchId,
        name: "Standard Weekday",
        staffId: partial.id,
        dayOfWeek: 1,
        startTime: "10:00",
        endTime: "18:00",
        isRecurring: true,
        effectiveFrom: "2024-06-01",
        effectiveTo: null,
        isActive: true,
      },
    ],
    attendance: [
      {
        id: `att-${partial.id}-today`,
        staffId: partial.id,
        shiftId: `shift-${partial.id}-today`,
        tenantId: DEFAULT_STAFF_SCOPE.tenantId,
        businessId: DEFAULT_STAFF_SCOPE.businessId,
        branchId: DEFAULT_STAFF_SCOPE.branchId,
        status: partial.hasLateAttendance ? ATTENDANCE_STATUSES.LATE : ATTENDANCE_STATUSES.PRESENT,
        clockInAt: partial.hasLateAttendance
          ? "2026-02-15T10:22:00.000Z"
          : "2026-02-15T09:58:00.000Z",
        clockOutAt: null,
        scheduledMinutes: 480,
        workedMinutes: partial.hasLateAttendance ? 458 : 480,
        overtimeMinutes: 0,
        attendanceDate: "2026-02-15",
        notes: null,
      },
    ],
    leaveRequests: partial.hasPendingLeave
      ? [
          {
            id: `leave-${partial.id}`,
            staffId: partial.id,
            tenantId: DEFAULT_STAFF_SCOPE.tenantId,
            businessId: DEFAULT_STAFF_SCOPE.businessId,
            branchId: DEFAULT_STAFF_SCOPE.branchId,
            leaveType: LEAVE_TYPES.ANNUAL,
            status: LEAVE_STATUSES.PENDING,
            startDate: "2026-03-01",
            endDate: "2026-03-05",
            totalDays: 5,
            reason: "Family holiday",
            approvedByStaffId: null,
            approvedAt: null,
            rejectionReason: null,
            createdAt: NOW,
            updatedAt: NOW,
          },
        ]
      : [],
    payroll: {
      staffId: partial.id,
      tenantId: DEFAULT_STAFF_SCOPE.tenantId,
      businessId: DEFAULT_STAFF_SCOPE.businessId,
      payFrequency: PAYROLL_FREQUENCIES.MONTHLY,
      hourlyRateCents: partial.hourlyRateCents ?? null,
      salaryCents: partial.salaryCents ?? null,
      currency: "GBP",
      taxCode: "1257L",
      bankAccountLast4: "4242",
      isPayrollEnabled: true,
      effectiveFrom: "2024-06-01",
    },
    performanceReviews: [
      {
        id: `review-${partial.id}`,
        staffId: partial.id,
        tenantId: DEFAULT_STAFF_SCOPE.tenantId,
        businessId: DEFAULT_STAFF_SCOPE.businessId,
        reviewerStaffId: DEFAULT_STAFF_SCOPE.managerStaffId,
        reviewPeriodStart: "2025-07-01",
        reviewPeriodEnd: "2025-12-31",
        rating: PERFORMANCE_RATINGS.MEETS,
        scoreBps: 7800,
        strengths: ["Reliable attendance", "Team player"],
        improvements: ["Speed during peak hours"],
        goals: ["Complete food safety refresher"],
        notes: null,
        completedAt: "2026-01-15T10:00:00.000Z",
      },
    ],
    trainingRecords: [
      {
        id: `training-${partial.id}`,
        staffId: partial.id,
        tenantId: DEFAULT_STAFF_SCOPE.tenantId,
        businessId: DEFAULT_STAFF_SCOPE.businessId,
        courseName: "Food Safety Level 2",
        provider: "CIEH",
        status: TRAINING_STATUSES.COMPLETED,
        startedAt: "2024-06-15T00:00:00.000Z",
        completedAt: "2024-07-01T00:00:00.000Z",
        expiresAt: "2027-07-01T00:00:00.000Z",
        certificateId: `cert-${partial.id}`,
      },
    ],
    certifications: [
      {
        id: `cert-${partial.id}`,
        staffId: partial.id,
        name: "Food Safety Level 2",
        issuingBody: "CIEH",
        certificateNumber: `FS-${partial.employeeNumber}`,
        issuedAt: "2024-07-01T00:00:00.000Z",
        expiresAt: "2027-07-01T00:00:00.000Z",
        documentId: `doc-${partial.id}`,
        isVerified: true,
      },
    ],
    emergencyContacts: [
      {
        id: `ec-${partial.id}`,
        staffId: partial.id,
        name: "Emergency Contact",
        relationship: "Spouse",
        phone: "+44 7700 900456",
        email: null,
        isPrimary: true,
      },
    ],
    documents: [
      {
        id: `doc-${partial.id}`,
        staffId: partial.id,
        tenantId: DEFAULT_STAFF_SCOPE.tenantId,
        businessId: DEFAULT_STAFF_SCOPE.businessId,
        documentType: "contract",
        fileName: `employment-contract-${partial.employeeNumber}.pdf`,
        fileUrl: null,
        uploadedAt: "2024-06-01T00:00:00.000Z",
        uploadedByStaffId: DEFAULT_STAFF_SCOPE.managerStaffId,
        expiresAt: null,
      },
    ],
    activityLog: [
      {
        id: `log-${partial.id}-hired`,
        staffId: partial.id,
        tenantId: DEFAULT_STAFF_SCOPE.tenantId,
        businessId: DEFAULT_STAFF_SCOPE.businessId,
        eventType: STAFF_ACTIVITY_EVENT_TYPES.HIRED,
        actorStaffId: DEFAULT_STAFF_SCOPE.managerStaffId,
        message: `${displayName} joined the team`,
        metadata: { department: department.name },
        occurredAt: "2024-06-01T00:00:00.000Z",
      },
    ],
    analytics: {
      staffId: partial.id,
      attendanceRateBps: partial.hasLateAttendance ? 9200 : 9800,
      punctualityRateBps: partial.hasLateAttendance ? 8500 : 9600,
      overtimeHoursMonth: 4,
      leaveDaysUsed: 8,
      leaveDaysRemaining: 20,
      avgPerformanceScoreBps: 7800,
      trainingCompletionRateBps: 10000,
      shiftCoverageRateBps: 9500,
    },
    aiContext: {
      staffId: partial.id,
      summary: `${displayName} — ${designation.title}, ${department.name}`,
      labourDemandScore: 0.72,
      staffingGapHours: partial.hasPendingLeave ? 40 : 0,
      attendanceRiskScore: partial.hasLateAttendance ? 0.35 : 0.08,
      performanceTrend: "stable",
      recommendedShiftHours: 40,
      insights: partial.hasLateAttendance ? ["Late clock-in pattern on Mondays"] : [],
      recommendedActions: partial.hasPendingLeave ? ["Review leave coverage for March"] : [],
      lastGeneratedAt: NOW,
    },
  };
}

export const MOCK_STAFF_RECORDS: StaffRecord[] = [
  buildRecord({
    id: "staff-manager-1",
    employeeNumber: "EMP-001",
    firstName: "James",
    lastName: "Wright",
    email: "james.wright@harbourkitchen.co.uk",
    departmentId: "dept-management",
    designationId: "desig-gm",
    employmentStatus: EMPLOYMENT_STATUSES.ACTIVE,
    salaryCents: 4500000,
    isManager: true,
  }),
  buildRecord({
    id: "staff-chef-1",
    employeeNumber: "EMP-002",
    firstName: "Maria",
    lastName: "Santos",
    email: "maria.santos@harbourkitchen.co.uk",
    departmentId: "dept-kitchen",
    designationId: "desig-head-chef",
    employmentStatus: EMPLOYMENT_STATUSES.ACTIVE,
    salaryCents: 3800000,
  }),
  buildRecord({
    id: "staff-cook-1",
    employeeNumber: "EMP-003",
    firstName: "Tom",
    lastName: "Baker",
    email: "tom.baker@harbourkitchen.co.uk",
    departmentId: "dept-kitchen",
    designationId: "desig-line-cook",
    employmentStatus: EMPLOYMENT_STATUSES.ACTIVE,
    hourlyRateCents: 1450,
    hasLateAttendance: true,
  }),
  buildRecord({
    id: "staff-server-1",
    employeeNumber: "EMP-004",
    firstName: "Sarah",
    lastName: "Chen",
    email: "sarah.chen@harbourkitchen.co.uk",
    departmentId: "dept-service",
    designationId: "desig-server",
    employmentStatus: EMPLOYMENT_STATUSES.ACTIVE,
    hourlyRateCents: 1250,
    hasPendingLeave: true,
  }),
  buildRecord({
    id: "staff-cashier-1",
    employeeNumber: "EMP-005",
    firstName: "Alex",
    lastName: "Patel",
    email: "alex.patel@harbourkitchen.co.uk",
    departmentId: "dept-service",
    designationId: "desig-cashier",
    employmentStatus: EMPLOYMENT_STATUSES.ON_LEAVE,
    hourlyRateCents: 1200,
  }),
  buildRecord({
    id: "staff-delivery-1",
    employeeNumber: "EMP-006",
    firstName: "Jordan",
    lastName: "Lee",
    email: "jordan.lee@harbourkitchen.co.uk",
    departmentId: "dept-delivery",
    designationId: "desig-server",
    employmentStatus: EMPLOYMENT_STATUSES.INACTIVE,
    hourlyRateCents: 1150,
  }),
];
