export interface SystemRoleDefinition {
  slug: string;
  name: string;
  description: string;
  permissionKeys: string[] | "all";
}

export const SYSTEM_ROLE_DEFINITIONS: SystemRoleDefinition[] = [
  {
    slug: "owner",
    name: "Owner",
    description: "Full access to all business features and settings.",
    permissionKeys: "all",
  },
  {
    slug: "manager",
    name: "Manager",
    description: "Manage daily operations, staff, and business settings.",
    permissionKeys: [
      "dashboard.view",
      "business.view",
      "business.update",
      "branch.view",
      "branch.create",
      "branch.update",
      "branch.delete",
      "branch.settings",
      "branch.manage",
      "branch.access",
      "staff.view",
      "staff.create",
      "staff.update",
      "roles.view",
      "roles.manage",
      "modules.view",
      "modules.install",
      "modules.enable",
      "modules.disable",
      "modules.manage",
      "menu.view",
      "menu.create",
      "menu.update",
      "menu.delete",
      "reservation.view",
      "reservation.manage",
      "table.manage",
      "qr.manage",
      "order.view",
      "order.create",
      "order.cancel",
      "kitchen.view",
      "kitchen.update",
      "analytics.view",
      "analytics.export",
      "analytics.create_report",
      "analytics.edit_report",
      "analytics.delete_report",
      "dashboard.manage",
      "ai.view",
      "ai.chat",
      "ai.recommendation.view",
      "ai.recommendation.manage",
      "inventory.view",
      "inventory.create",
      "inventory.update",
      "inventory.delete",
      "inventory.adjust",
      "inventory.manage",
      "supplier.view",
      "supplier.create",
      "supplier.update",
      "purchase_order.view",
      "purchase_order.create",
      "purchase_order.receive",
      "recipe.manage",
      "crm.view",
      "crm.manage",
      "customer.view",
      "customer.create",
      "customer.update",
      "customer.delete",
      "customer.import",
      "customer.export",
      "loyalty.view",
      "loyalty.manage",
      "commercial.view",
      "commercial.create",
      "commercial.update",
      "commercial.archive",
      "commercial.manage_prices",
      "commercial.manage_bundles",
      "sales.view",
      "sales.create",
      "sales.update",
      "sales.manage",
      "quotes.view",
      "quotes.create",
      "quotes.edit",
      "quotes.send",
      "quotes.approve",
      "quotes.accept",
      "proposals.manage",
      "contracts.view",
      "contracts.create",
      "contracts.edit",
      "contracts.approve",
      "contracts.activate",
      "contracts.archive",
      "clauses.manage",
      "implementation.view",
      "implementation.manage",
      "implementation.assign",
      "implementation.complete",
      "implementation.approve",
      "implementation.close",
      "success.view",
      "success.manage",
      "success.assign",
      "success.review",
      "success.renew",
      "success.expand",
      "revenue.view",
      "revenue.manage",
      "invoices.manage",
      "payments.manage",
      "expenses.manage",
      "forecasting.view",
      "ai.tool.execute",
      "ai.tool.register",
      "ai.tool.disable",
      "ai.knowledge.view",
      "ai.knowledge.upload",
      "ai.knowledge.edit",
      "ai.automation.view",
      "ai.automation.create",
      "ai.automation.execute",
      "ai.automation.approve",
      "ai.agent.view",
      "ai.agent.create",
      "ai.agent.edit",
      "ai.agent.update",
      "ai.agent.delete",
      "ai.agent.execute",
      "ai.agent.deploy",
      "marketplace.view",
      "marketplace.install",
      "marketplace.purchase",
      "iam.view",
      "iam.manage_sessions",
      "iam.manage_api_keys",
      "notifications.view",
      "notifications.manage_templates",
      "notifications.manage_rules",
      "notifications.publish",
      "communication.view",
      "communication.reply",
      "communication.assign",
      "communication.manage",
      "files.view",
      "files.upload",
      "files.download",
      "files.edit",
      "files.share",
      "files.manage",
      "search.view",
      "search.query",
      "search.manage_index",
      "settings.view",
      "settings.edit",
      "settings.manage",
      "feature_flags.view",
      "feature_flags.evaluate",
      "feature_flags.manage",
      "api_gateway.view",
      "api_gateway.invoke",
      "api_gateway.manage",
      "monitoring_platform.view",
      "monitoring_platform.manage",
      "backup_platform.view",
      "backup_platform.manage",
      "localization_platform.view",
      "localization_platform.manage",
      "import_export_platform.view",
      "import_export_platform.manage",
      "tenant_platform.view",
      "tenant_platform.manage",
    ],
  },
  {
    slug: "supervisor",
    name: "Supervisor",
    description: "Supervise floor operations, staff shifts, and service quality.",
    permissionKeys: [
      "dashboard.view",
      "staff.view",
      "order.view",
      "order.create",
      "order.update",
      "menu.view",
      "reservation.view",
      "reservation.manage",
      "table.manage",
      "kitchen.view",
      "analytics.view",
      "branch.access",
    ],
  },
  {
    slug: "cashier",
    name: "Cashier",
    description: "Handle point-of-sale transactions and orders.",
    permissionKeys: [
      "dashboard.view",
      "order.view",
      "order.create",
      "menu.view",
      "pos.use",
      "payment.create",
      "receipt.view",
      "receipt.print",
      "branch.access",
    ],
  },
  {
    slug: "kitchen-staff",
    name: "Kitchen Staff",
    description: "Prepare orders and manage kitchen workflow.",
    permissionKeys: ["kitchen.view", "kitchen.update", "menu.view", "order.view", "inventory.view"],
  },
  {
    slug: "chef",
    name: "Chef",
    description: "View and manage kitchen orders and menu items.",
    permissionKeys: ["kitchen.view", "kitchen.update", "menu.view", "order.view", "inventory.view"],
  },
  {
    slug: "waiter",
    name: "Waiter",
    description: "Take orders and serve customers at tables.",
    permissionKeys: [
      "order.view",
      "order.create",
      "menu.view",
      "reservation.view",
      "customer.view",
    ],
  },
  {
    slug: "accountant",
    name: "Accountant",
    description: "Manage billing, revenue reporting, and financial records.",
    permissionKeys: [
      "dashboard.view",
      "analytics.view",
      "revenue.view",
      "revenue.manage",
      "invoices.manage",
      "payments.manage",
      "expenses.manage",
      "forecasting.view",
      "billing.view",
      "billing.update",
      "settings.view",
    ],
  },
  {
    slug: "marketing",
    name: "Marketing",
    description: "Run campaigns, manage customer engagement, and marketplace listings.",
    permissionKeys: [
      "dashboard.view",
      "crm.view",
      "crm.manage",
      "customer.view",
      "customer.create",
      "customer.update",
      "customer.import",
      "customer.export",
      "loyalty.view",
      "loyalty.manage",
      "marketplace.view",
      "marketplace.install",
      "communication.view",
      "communication.manage",
      "ai.view",
      "ai.use",
    ],
  },
  {
    slug: "support",
    name: "Support",
    description: "Handle customer support, communication, and service issues.",
    permissionKeys: [
      "dashboard.view",
      "customer.view",
      "customer.update",
      "communication.view",
      "communication.reply",
      "communication.assign",
      "communication.manage",
      "notifications.view",
      "reservation.view",
    ],
  },
  {
    slug: "receptionist",
    name: "Receptionist",
    description: "Manage reservations and greet customers.",
    permissionKeys: ["reservation.view", "reservation.manage", "staff.view"],
  },
];
