import {
  BILLING_AI_FEATURE_KEYS,
  BILLING_MODULE_KEYS,
  FEATURE_LIMIT_KEYS,
  UNLIMITED_LIMIT,
} from "@/modules/billing/constants/feature-access";
import {
  BILLING_CYCLES,
  BILLING_INVOICE_STATUSES,
  BILLING_PAYMENT_STATUSES,
  PLAN_TYPES,
  SUBSCRIPTION_STATUSES,
  TRIAL_STATUSES,
  TRIAL_DURATION_DAYS,
} from "@/modules/billing/constants/billing-status";
import type {
  BillingRecord,
  FeatureLimits,
  PlanFeatureAccess,
  SubscriptionPlan,
} from "@/modules/billing/types/billing-platform";

export const DEFAULT_BILLING_SCOPE = {
  tenantId: "tenant-harbour",
  workspaceId: "ws-harbour-kitchen",
  businessId: "biz-harbour-kitchen",
  userId: "user-harbour-owner",
  subscriptionId: "sub-harbour-001",
  planId: "plan-business",
  baseCurrency: "GBP",
} as const;

const NOW = "2026-02-15T23:00:00.000Z";

function buildLimits(
  partial: Partial<FeatureLimits> & Pick<FeatureLimits, "maxStaff" | "maxBranches">,
): FeatureLimits {
  return {
    maxStaff: partial.maxStaff,
    maxBranches: partial.maxBranches,
    maxMenuItems: partial.maxMenuItems ?? 100,
    maxTables: partial.maxTables ?? 50,
    maxReservations: partial.maxReservations ?? 500,
    maxOrders: partial.maxOrders ?? 5000,
    maxStorageMb: partial.maxStorageMb ?? 1024,
    maxAiCredits: partial.maxAiCredits ?? 500,
    maxApiCalls: partial.maxApiCalls ?? 10000,
    maxIntegrations: partial.maxIntegrations ?? 5,
  };
}

function buildFeatureAccess(partial: {
  modules: PlanFeatureAccess["enabledModules"];
  aiFeatures: PlanFeatureAccess["enabledAiFeatures"];
  limits: FeatureLimits;
  customLimits?: Partial<Record<string, number>>;
}): PlanFeatureAccess {
  return {
    enabledModules: partial.modules,
    enabledAiFeatures: partial.aiFeatures,
    limits: partial.limits,
    customLimits: partial.customLimits ?? {},
  };
}

const FREE_ACCESS = buildFeatureAccess({
  modules: [BILLING_MODULE_KEYS.DASHBOARD, BILLING_MODULE_KEYS.MENU, BILLING_MODULE_KEYS.ORDERS],
  aiFeatures: [BILLING_AI_FEATURE_KEYS.CHAT],
  limits: buildLimits({
    maxStaff: 2,
    maxBranches: 1,
    maxMenuItems: 25,
    maxTables: 10,
    maxReservations: 50,
    maxOrders: 500,
    maxStorageMb: 256,
    maxAiCredits: 50,
    maxApiCalls: 1000,
    maxIntegrations: 1,
  }),
});

const STARTER_ACCESS = buildFeatureAccess({
  modules: [
    BILLING_MODULE_KEYS.DASHBOARD,
    BILLING_MODULE_KEYS.MENU,
    BILLING_MODULE_KEYS.ORDERS,
    BILLING_MODULE_KEYS.POS,
    BILLING_MODULE_KEYS.RESERVATIONS,
  ],
  aiFeatures: [BILLING_AI_FEATURE_KEYS.CHAT, BILLING_AI_FEATURE_KEYS.RECOMMENDATIONS],
  limits: buildLimits({
    maxStaff: 10,
    maxBranches: 1,
    maxMenuItems: 100,
    maxTables: 30,
    maxReservations: 200,
    maxOrders: 2000,
    maxStorageMb: 512,
    maxAiCredits: 200,
    maxApiCalls: 5000,
    maxIntegrations: 2,
  }),
});

const PROFESSIONAL_ACCESS = buildFeatureAccess({
  modules: [
    BILLING_MODULE_KEYS.DASHBOARD,
    BILLING_MODULE_KEYS.MENU,
    BILLING_MODULE_KEYS.ORDERS,
    BILLING_MODULE_KEYS.POS,
    BILLING_MODULE_KEYS.KITCHEN,
    BILLING_MODULE_KEYS.RESERVATIONS,
    BILLING_MODULE_KEYS.TABLE_MANAGEMENT,
    BILLING_MODULE_KEYS.INVENTORY,
    BILLING_MODULE_KEYS.ANALYTICS,
  ],
  aiFeatures: [
    BILLING_AI_FEATURE_KEYS.CHAT,
    BILLING_AI_FEATURE_KEYS.RECOMMENDATIONS,
    BILLING_AI_FEATURE_KEYS.FORECASTING,
  ],
  limits: buildLimits({
    maxStaff: 30,
    maxBranches: 3,
    maxMenuItems: 500,
    maxTables: 100,
    maxReservations: 1000,
    maxOrders: 10000,
    maxStorageMb: 2048,
    maxAiCredits: 1000,
    maxApiCalls: 25000,
    maxIntegrations: 5,
  }),
});

const BUSINESS_ACCESS = buildFeatureAccess({
  modules: Object.values(BILLING_MODULE_KEYS),
  aiFeatures: Object.values(BILLING_AI_FEATURE_KEYS).filter(
    (f) => f !== BILLING_AI_FEATURE_KEYS.CUSTOM_AGENTS,
  ),
  limits: buildLimits({
    maxStaff: 100,
    maxBranches: 10,
    maxMenuItems: 2000,
    maxTables: 500,
    maxReservations: 5000,
    maxOrders: 50000,
    maxStorageMb: 10240,
    maxAiCredits: 5000,
    maxApiCalls: 100000,
    maxIntegrations: 15,
  }),
});

const ENTERPRISE_ACCESS = buildFeatureAccess({
  modules: Object.values(BILLING_MODULE_KEYS),
  aiFeatures: Object.values(BILLING_AI_FEATURE_KEYS),
  limits: buildLimits({
    maxStaff: UNLIMITED_LIMIT,
    maxBranches: UNLIMITED_LIMIT,
    maxMenuItems: UNLIMITED_LIMIT,
    maxTables: UNLIMITED_LIMIT,
    maxReservations: UNLIMITED_LIMIT,
    maxOrders: UNLIMITED_LIMIT,
    maxStorageMb: UNLIMITED_LIMIT,
    maxAiCredits: UNLIMITED_LIMIT,
    maxApiCalls: UNLIMITED_LIMIT,
    maxIntegrations: UNLIMITED_LIMIT,
  }),
  customLimits: { [FEATURE_LIMIT_KEYS.MAX_STAFF]: UNLIMITED_LIMIT },
});

export const MOCK_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: "plan-free",
    slug: "free",
    name: "Free",
    planType: PLAN_TYPES.FREE,
    description: "Get started with core restaurant tools",
    monthlyPriceCents: 0,
    yearlyPriceCents: 0,
    currency: "GBP",
    featureAccess: FREE_ACCESS,
    isPublic: true,
    isActive: true,
    trialDays: 0,
    sortOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "plan-starter",
    slug: "starter",
    name: "Starter",
    planType: PLAN_TYPES.STARTER,
    description: "Essential tools for small restaurants",
    monthlyPriceCents: 4900,
    yearlyPriceCents: 47000,
    currency: "GBP",
    featureAccess: STARTER_ACCESS,
    isPublic: true,
    isActive: true,
    trialDays: TRIAL_DURATION_DAYS,
    sortOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "plan-professional",
    slug: "professional",
    name: "Professional",
    planType: PLAN_TYPES.PROFESSIONAL,
    description: "Full operations suite for growing venues",
    monthlyPriceCents: 14900,
    yearlyPriceCents: 149000,
    currency: "GBP",
    featureAccess: PROFESSIONAL_ACCESS,
    isPublic: true,
    isActive: true,
    trialDays: TRIAL_DURATION_DAYS,
    sortOrder: 3,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "plan-business",
    slug: "business",
    name: "Business",
    planType: PLAN_TYPES.BUSINESS,
    description: "Complete platform for multi-location restaurants",
    monthlyPriceCents: 29900,
    yearlyPriceCents: 299000,
    currency: "GBP",
    featureAccess: BUSINESS_ACCESS,
    isPublic: true,
    isActive: true,
    trialDays: TRIAL_DURATION_DAYS,
    sortOrder: 4,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "plan-enterprise",
    slug: "enterprise",
    name: "Enterprise",
    planType: PLAN_TYPES.ENTERPRISE,
    description: "Unlimited scale with custom contracts",
    monthlyPriceCents: 0,
    yearlyPriceCents: 0,
    currency: "GBP",
    featureAccess: ENTERPRISE_ACCESS,
    isPublic: false,
    isActive: true,
    /** Mock-only legacy enterprise row — aligned to canonical trial duration for demos. */
    trialDays: TRIAL_DURATION_DAYS,
    sortOrder: 5,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const MOCK_BILLING_RECORD: BillingRecord = {
  plan: MOCK_SUBSCRIPTION_PLANS.find((p) => p.id === "plan-business")!,
  subscription: {
    id: DEFAULT_BILLING_SCOPE.subscriptionId,
    tenantId: DEFAULT_BILLING_SCOPE.tenantId,
    planId: "plan-business",
    status: SUBSCRIPTION_STATUSES.ACTIVE,
    billingCycle: BILLING_CYCLES.MONTHLY,
    currentPeriodStart: "2026-02-01",
    currentPeriodEnd: "2026-03-01",
    cancelAtPeriodEnd: false,
    cancelledAt: null,
    pausedAt: null,
    trialEnd: null,
    quantity: 1,
    currency: "GBP",
    mrrCents: 29900,
    createdAt: "2025-08-01T00:00:00.000Z",
    updatedAt: NOW,
  },
  workspaceSubscription: {
    id: "ws-sub-001",
    tenantId: DEFAULT_BILLING_SCOPE.tenantId,
    workspaceId: DEFAULT_BILLING_SCOPE.workspaceId,
    subscriptionId: DEFAULT_BILLING_SCOPE.subscriptionId,
    planId: "plan-business",
    status: SUBSCRIPTION_STATUSES.ACTIVE,
    featureAccess: BUSINESS_ACCESS,
    effectiveFrom: "2025-08-01",
    effectiveTo: null,
  },
  businessSubscriptions: [
    {
      id: "biz-sub-001",
      tenantId: DEFAULT_BILLING_SCOPE.tenantId,
      workspaceId: DEFAULT_BILLING_SCOPE.workspaceId,
      businessId: DEFAULT_BILLING_SCOPE.businessId,
      subscriptionId: DEFAULT_BILLING_SCOPE.subscriptionId,
      planId: "plan-business",
      status: SUBSCRIPTION_STATUSES.ACTIVE,
      branchCount: 1,
      staffCount: 6,
      featureAccess: BUSINESS_ACCESS,
    },
  ],
  billingCycles: [
    {
      id: "cycle-001",
      subscriptionId: DEFAULT_BILLING_SCOPE.subscriptionId,
      cycle: BILLING_CYCLES.MONTHLY,
      periodStart: "2026-02-01",
      periodEnd: "2026-03-01",
      amountCents: 29900,
      currency: "GBP",
      isPaid: false,
    },
  ],
  invoices: [
    {
      id: "binv-001",
      tenantId: DEFAULT_BILLING_SCOPE.tenantId,
      workspaceId: DEFAULT_BILLING_SCOPE.workspaceId,
      subscriptionId: DEFAULT_BILLING_SCOPE.subscriptionId,
      invoiceNumber: "BUSAL-INV-2026-0012",
      status: BILLING_INVOICE_STATUSES.OPEN,
      subtotalCents: 29900,
      discountCents: 0,
      taxCents: 5980,
      totalCents: 35880,
      amountPaidCents: 0,
      amountDueCents: 35880,
      currency: "GBP",
      periodStart: "2026-02-01",
      periodEnd: "2026-03-01",
      dueDate: "2026-02-15",
      paidAt: null,
      lineItems: [
        {
          id: "bline-001",
          invoiceId: "binv-001",
          description: "Business Plan — Monthly",
          quantity: 1,
          unitAmountCents: 29900,
          amountCents: 29900,
          periodStart: "2026-02-01",
          periodEnd: "2026-03-01",
        },
      ],
      createdAt: NOW,
    },
  ],
  payments: [
    {
      id: "bpay-001",
      tenantId: DEFAULT_BILLING_SCOPE.tenantId,
      invoiceId: "binv-prev",
      paymentMethodId: "pm-card-001",
      amountCents: 35880,
      currency: "GBP",
      status: BILLING_PAYMENT_STATUSES.SUCCEEDED,
      failureReason: null,
      paidAt: "2026-01-15T10:00:00.000Z",
      createdAt: "2026-01-15T10:00:00.000Z",
    },
    {
      id: "bpay-002",
      tenantId: DEFAULT_BILLING_SCOPE.tenantId,
      invoiceId: "binv-failed",
      paymentMethodId: "pm-card-001",
      amountCents: 35880,
      currency: "GBP",
      status: BILLING_PAYMENT_STATUSES.FAILED,
      failureReason: "card_declined",
      paidAt: null,
      createdAt: "2025-12-15T10:00:00.000Z",
    },
  ],
  paymentMethods: [
    {
      id: "pm-card-001",
      tenantId: DEFAULT_BILLING_SCOPE.tenantId,
      type: "card",
      label: "Visa ending 4242",
      last4: "4242",
      expiryMonth: 12,
      expiryYear: 2028,
      isDefault: true,
      isActive: true,
    },
  ],
  refunds: [],
  coupons: [
    {
      id: "coupon-launch20",
      code: "LAUNCH20",
      discountType: "percentage",
      valueBps: 2000,
      amountCents: null,
      maxRedemptions: 100,
      redemptionCount: 12,
      validFrom: "2026-01-01",
      validTo: "2026-06-30",
      isActive: true,
    },
  ],
  promotions: [],
  discounts: [],
  trial: {
    id: "trial-001",
    tenantId: DEFAULT_BILLING_SCOPE.tenantId,
    workspaceId: DEFAULT_BILLING_SCOPE.workspaceId,
    planId: "plan-business",
    status: TRIAL_STATUSES.CONVERTED,
    startedAt: "2025-07-15T00:00:00.000Z",
    endsAt: "2025-08-01T00:00:00.000Z",
    convertedAt: "2025-08-01T00:00:00.000Z",
    daysRemaining: 0,
  },
  taxes: [
    {
      id: "btax-001",
      invoiceId: "binv-001",
      taxName: "VAT",
      rateBps: 2000,
      taxableAmountCents: 29900,
      taxAmountCents: 5980,
      jurisdiction: "GB",
    },
  ],
  usageRecords: [
    {
      id: "usage-staff",
      tenantId: DEFAULT_BILLING_SCOPE.tenantId,
      workspaceId: DEFAULT_BILLING_SCOPE.workspaceId,
      meterKey: FEATURE_LIMIT_KEYS.MAX_STAFF,
      quantity: 6,
      recordedAt: NOW,
      periodStart: "2026-02-01",
      periodEnd: "2026-03-01",
    },
    {
      id: "usage-branches",
      tenantId: DEFAULT_BILLING_SCOPE.tenantId,
      workspaceId: DEFAULT_BILLING_SCOPE.workspaceId,
      meterKey: FEATURE_LIMIT_KEYS.MAX_BRANCHES,
      quantity: 1,
      recordedAt: NOW,
      periodStart: "2026-02-01",
      periodEnd: "2026-03-01",
    },
    {
      id: "usage-ai",
      tenantId: DEFAULT_BILLING_SCOPE.tenantId,
      workspaceId: DEFAULT_BILLING_SCOPE.workspaceId,
      meterKey: FEATURE_LIMIT_KEYS.MAX_AI_CREDITS,
      quantity: 342,
      recordedAt: NOW,
      periodStart: "2026-02-01",
      periodEnd: "2026-03-01",
    },
  ],
  enterpriseContract: null,
  customPlan: null,
  analytics: {
    tenantId: DEFAULT_BILLING_SCOPE.tenantId,
    mrrCents: 29900,
    arrCents: 358800,
    activeSubscriptions: 1,
    trialingCount: 0,
    churnRateBps: 250,
    arpuCents: 29900,
    failedPaymentCount: 1,
    couponRedemptionCount: 0,
    upgradeCount: 1,
    downgradeCount: 0,
  },
  aiContext: {
    tenantId: DEFAULT_BILLING_SCOPE.tenantId,
    summary: "Business Plan — £299/mo MRR, 6/100 staff used",
    churnRiskScore: 0.15,
    mrrForecastCents: 32000,
    recommendedPlanId: null,
    pricingOptimizationScore: 0.78,
    insights: ["Staff usage at 6% of limit", "AI credits at 34% of monthly allowance"],
    recommendedActions: ["Consider Professional if single-location operations suffice"],
    lastGeneratedAt: NOW,
  },
};

export { BUSINESS_ACCESS, PROFESSIONAL_ACCESS, STARTER_ACCESS, FREE_ACCESS, ENTERPRISE_ACCESS };
