export const ACTIVE_BUSINESS_COOKIE = "busal-active-business" as const;
export const ACTIVE_BRANCH_COOKIE = "busal-active-branch" as const;

export const BUSINESS_CONTEXT_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  BUSINESS_NOT_FOUND: "BUSINESS_NOT_FOUND",
  BUSINESS_INACTIVE: "BUSINESS_INACTIVE",
  BRANCH_NOT_FOUND: "BRANCH_NOT_FOUND",
  BRANCH_ACCESS_DENIED: "BRANCH_ACCESS_DENIED",
  BRANCH_REQUIRED: "BRANCH_REQUIRED",
  CROSS_BUSINESS_ACCESS: "CROSS_BUSINESS_ACCESS",
  STAFF_BUSINESS_RESTRICTED: "STAFF_BUSINESS_RESTRICTED",
  INVALID_CONTEXT: "INVALID_CONTEXT",
} as const;

export const BUSINESS_CONTEXT_ERROR_MESSAGES = {
  [BUSINESS_CONTEXT_ERROR_CODES.UNAUTHORIZED]: "Unauthorized",
  [BUSINESS_CONTEXT_ERROR_CODES.BUSINESS_NOT_FOUND]: "Business Not Found",
  [BUSINESS_CONTEXT_ERROR_CODES.BUSINESS_INACTIVE]: "Business is not active",
  [BUSINESS_CONTEXT_ERROR_CODES.BRANCH_NOT_FOUND]: "Branch not found",
  [BUSINESS_CONTEXT_ERROR_CODES.BRANCH_ACCESS_DENIED]: "Branch access denied",
  [BUSINESS_CONTEXT_ERROR_CODES.BRANCH_REQUIRED]: "Branch is required",
  [BUSINESS_CONTEXT_ERROR_CODES.CROSS_BUSINESS_ACCESS]: "Cross-business access blocked",
  [BUSINESS_CONTEXT_ERROR_CODES.STAFF_BUSINESS_RESTRICTED]:
    "Staff is restricted to assigned business",
  [BUSINESS_CONTEXT_ERROR_CODES.INVALID_CONTEXT]: "Invalid business context",
} as const;
