import {
  DELIVERY_STATUSES,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_EVENT_SOURCES,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_SCOPES,
  NOTIFICATION_STATUSES,
  QUEUE_STATUSES,
  SCHEDULE_TYPES,
} from "@/modules/notifications/constants/notification-status";
import type { NotificationRecord } from "@/modules/notifications/types/notification-platform";

export const DEFAULT_NOTIFICATION_SCOPE = {
  tenantId: "tenant-harbour",
  workspaceId: "ws-harbour-kitchen",
  businessId: "biz-harbour-kitchen",
  branchId: "branch-harbour-main",
  userId: "user-harbour-owner",
} as const;

const PERIOD_START = "2026-02-01";
const PERIOD_END = "2026-02-28";
const NOW = "2026-02-15T23:00:00.000Z";

export const MOCK_NOTIFICATION_RECORD: NotificationRecord = {
  notifications: [
    {
      id: "notif-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      workspaceId: DEFAULT_NOTIFICATION_SCOPE.workspaceId,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: DEFAULT_NOTIFICATION_SCOPE.branchId,
      templateId: "tmpl-reservation-confirmed",
      title: "Reservation Confirmed",
      body: "Table for 4 confirmed for tonight at 7:00 PM",
      channel: NOTIFICATION_CHANNELS.IN_APP,
      status: NOTIFICATION_STATUSES.DELIVERED,
      priority: NOTIFICATION_PRIORITIES.NORMAL,
      scope: NOTIFICATION_SCOPES.BUSINESS,
      eventSource: NOTIFICATION_EVENT_SOURCES.RESERVATIONS,
      eventKey: "reservation.confirmed",
      recipientId: DEFAULT_NOTIFICATION_SCOPE.userId,
      isRead: false,
      readAt: null,
      scheduledAt: null,
      sentAt: "2026-02-15T18:00:00.000Z",
      metadata: { reservationId: "res-001", partySize: "4" },
      createdAt: "2026-02-15T17:55:00.000Z",
      updatedAt: NOW,
    },
    {
      id: "notif-002",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      workspaceId: DEFAULT_NOTIFICATION_SCOPE.workspaceId,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: DEFAULT_NOTIFICATION_SCOPE.branchId,
      templateId: "tmpl-low-stock",
      title: "Low Stock Alert",
      body: "Salmon fillet is below reorder threshold (2 units remaining)",
      channel: NOTIFICATION_CHANNELS.EMAIL,
      status: NOTIFICATION_STATUSES.SENT,
      priority: NOTIFICATION_PRIORITIES.HIGH,
      scope: NOTIFICATION_SCOPES.BRANCH,
      eventSource: NOTIFICATION_EVENT_SOURCES.INVENTORY,
      eventKey: "inventory.low_stock",
      recipientId: DEFAULT_NOTIFICATION_SCOPE.userId,
      isRead: true,
      readAt: "2026-02-15T14:30:00.000Z",
      scheduledAt: null,
      sentAt: "2026-02-15T14:00:00.000Z",
      metadata: { itemId: "inv-001", stockLevel: "2" },
      createdAt: "2026-02-15T14:00:00.000Z",
      updatedAt: NOW,
    },
    {
      id: "notif-003",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      workspaceId: DEFAULT_NOTIFICATION_SCOPE.workspaceId,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: DEFAULT_NOTIFICATION_SCOPE.branchId,
      templateId: "tmpl-kitchen-delay",
      title: "Kitchen Prep Time Alert",
      body: "Average prep time exceeded 18 min threshold on Grill station",
      channel: NOTIFICATION_CHANNELS.PUSH,
      status: NOTIFICATION_STATUSES.FAILED,
      priority: NOTIFICATION_PRIORITIES.URGENT,
      scope: NOTIFICATION_SCOPES.BRANCH,
      eventSource: NOTIFICATION_EVENT_SOURCES.KITCHEN,
      eventKey: "kitchen.prep_time_exceeded",
      recipientId: DEFAULT_NOTIFICATION_SCOPE.userId,
      isRead: false,
      readAt: null,
      scheduledAt: null,
      sentAt: null,
      metadata: { station: "Grill", avgPrepTime: "22" },
      createdAt: "2026-02-15T19:30:00.000Z",
      updatedAt: NOW,
    },
    {
      id: "notif-004",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      workspaceId: DEFAULT_NOTIFICATION_SCOPE.workspaceId,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: null,
      templateId: "tmpl-billing-invoice",
      title: "Invoice Due",
      body: "Your Business Plan invoice of £358.80 is due on Feb 15",
      channel: NOTIFICATION_CHANNELS.EMAIL,
      status: NOTIFICATION_STATUSES.SCHEDULED,
      priority: NOTIFICATION_PRIORITIES.NORMAL,
      scope: NOTIFICATION_SCOPES.TENANT,
      eventSource: NOTIFICATION_EVENT_SOURCES.BILLING,
      eventKey: "billing.invoice_due",
      recipientId: DEFAULT_NOTIFICATION_SCOPE.userId,
      isRead: false,
      readAt: null,
      scheduledAt: "2026-02-16T09:00:00.000Z",
      sentAt: null,
      metadata: { invoiceId: "binv-001", amountCents: "35880" },
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],
  templates: [
    {
      id: "tmpl-reservation-confirmed",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      name: "Reservation Confirmed",
      slug: "reservation-confirmed",
      subject: "Reservation Confirmed — {{restaurantName}}",
      bodyTemplate: "Table for {{partySize}} confirmed for {{date}} at {{time}}",
      channel: NOTIFICATION_CHANNELS.IN_APP,
      eventSource: NOTIFICATION_EVENT_SOURCES.RESERVATIONS,
      eventKey: "reservation.confirmed",
      variables: ["restaurantName", "partySize", "date", "time"],
      isActive: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: "tmpl-low-stock",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      name: "Low Stock Alert",
      slug: "low-stock-alert",
      subject: "Low Stock: {{itemName}}",
      bodyTemplate: "{{itemName}} is below reorder threshold ({{stockLevel}} units remaining)",
      channel: NOTIFICATION_CHANNELS.EMAIL,
      eventSource: NOTIFICATION_EVENT_SOURCES.INVENTORY,
      eventKey: "inventory.low_stock",
      variables: ["itemName", "stockLevel"],
      isActive: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: "tmpl-kitchen-delay",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      name: "Kitchen Prep Time Alert",
      slug: "kitchen-prep-alert",
      subject: "Kitchen Alert: {{station}}",
      bodyTemplate:
        "Average prep time on {{station}} exceeded {{threshold}} min (current: {{avgPrepTime}} min)",
      channel: NOTIFICATION_CHANNELS.PUSH,
      eventSource: NOTIFICATION_EVENT_SOURCES.KITCHEN,
      eventKey: "kitchen.prep_time_exceeded",
      variables: ["station", "threshold", "avgPrepTime"],
      isActive: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: "tmpl-billing-invoice",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      name: "Invoice Due Reminder",
      slug: "billing-invoice-due",
      subject: "Invoice Due — {{planName}}",
      bodyTemplate: "Your {{planName}} invoice of {{amount}} is due on {{dueDate}}",
      channel: NOTIFICATION_CHANNELS.EMAIL,
      eventSource: NOTIFICATION_EVENT_SOURCES.BILLING,
      eventKey: "billing.invoice_due",
      variables: ["planName", "amount", "dueDate"],
      isActive: true,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],
  channels: [
    {
      id: "ch-email",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      channel: NOTIFICATION_CHANNELS.EMAIL,
      label: "Email (SendGrid)",
      isEnabled: true,
      providerName: "sendgrid",
      config: { fromAddress: "notifications@harbourkitchen.co.uk" },
      rateLimitPerHour: 500,
      createdAt: NOW,
    },
    {
      id: "ch-sms",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      channel: NOTIFICATION_CHANNELS.SMS,
      label: "SMS (Twilio)",
      isEnabled: true,
      providerName: "twilio",
      config: { fromNumber: "+447700900123" },
      rateLimitPerHour: 100,
      createdAt: NOW,
    },
    {
      id: "ch-in-app",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      channel: NOTIFICATION_CHANNELS.IN_APP,
      label: "In-App Notifications",
      isEnabled: true,
      providerName: null,
      config: {},
      rateLimitPerHour: 10000,
      createdAt: NOW,
    },
    {
      id: "ch-push",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      channel: NOTIFICATION_CHANNELS.PUSH,
      label: "Push (Firebase)",
      isEnabled: true,
      providerName: "firebase",
      config: {},
      rateLimitPerHour: 1000,
      createdAt: NOW,
    },
    {
      id: "ch-slack",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      channel: NOTIFICATION_CHANNELS.SLACK,
      label: "Slack",
      isEnabled: false,
      providerName: "slack",
      config: { workspaceId: "" },
      rateLimitPerHour: 200,
      createdAt: NOW,
    },
  ],
  preferences: [
    {
      id: "pref-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      userId: DEFAULT_NOTIFICATION_SCOPE.userId,
      channel: NOTIFICATION_CHANNELS.EMAIL,
      eventSource: NOTIFICATION_EVENT_SOURCES.BILLING,
      eventKey: "billing.invoice_due",
      isEnabled: true,
      quietHoursStart: "22:00",
      quietHoursEnd: "07:00",
      updatedAt: NOW,
    },
    {
      id: "pref-002",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      userId: DEFAULT_NOTIFICATION_SCOPE.userId,
      channel: NOTIFICATION_CHANNELS.PUSH,
      eventSource: NOTIFICATION_EVENT_SOURCES.KITCHEN,
      eventKey: "kitchen.prep_time_exceeded",
      isEnabled: true,
      quietHoursStart: null,
      quietHoursEnd: null,
      updatedAt: NOW,
    },
    {
      id: "pref-003",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      userId: DEFAULT_NOTIFICATION_SCOPE.userId,
      channel: NOTIFICATION_CHANNELS.SMS,
      eventSource: NOTIFICATION_EVENT_SOURCES.RESERVATIONS,
      eventKey: "reservation.confirmed",
      isEnabled: false,
      quietHoursStart: "23:00",
      quietHoursEnd: "08:00",
      updatedAt: NOW,
    },
  ],
  queue: [
    {
      id: "queue-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-004",
      channel: NOTIFICATION_CHANNELS.EMAIL,
      status: QUEUE_STATUSES.PENDING,
      priority: NOTIFICATION_PRIORITIES.NORMAL,
      retryCount: 0,
      maxRetries: 3,
      nextAttemptAt: "2026-02-16T09:00:00.000Z",
      lastAttemptAt: null,
      errorMessage: null,
      createdAt: NOW,
    },
    {
      id: "queue-002",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-003",
      channel: NOTIFICATION_CHANNELS.PUSH,
      status: QUEUE_STATUSES.RETRY,
      priority: NOTIFICATION_PRIORITIES.URGENT,
      retryCount: 2,
      maxRetries: 3,
      nextAttemptAt: "2026-02-15T23:30:00.000Z",
      lastAttemptAt: NOW,
      errorMessage: "Push token expired",
      createdAt: "2026-02-15T19:30:00.000Z",
    },
  ],
  deliveries: [
    {
      id: "del-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-001",
      queueId: "queue-del-001",
      channel: NOTIFICATION_CHANNELS.IN_APP,
      status: DELIVERY_STATUSES.DELIVERED,
      attemptNumber: 1,
      providerMessageId: null,
      deliveredAt: "2026-02-15T18:00:00.000Z",
      failureReason: null,
      createdAt: "2026-02-15T18:00:00.000Z",
    },
    {
      id: "del-002",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-002",
      queueId: "queue-del-002",
      channel: NOTIFICATION_CHANNELS.EMAIL,
      status: DELIVERY_STATUSES.DELIVERED,
      attemptNumber: 1,
      providerMessageId: "sg-msg-001",
      deliveredAt: "2026-02-15T14:05:00.000Z",
      failureReason: null,
      createdAt: "2026-02-15T14:00:00.000Z",
    },
    {
      id: "del-003",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-003",
      queueId: "queue-002",
      channel: NOTIFICATION_CHANNELS.PUSH,
      status: DELIVERY_STATUSES.FAILED,
      attemptNumber: 2,
      providerMessageId: null,
      deliveredAt: null,
      failureReason: "Push token expired",
      createdAt: NOW,
    },
  ],
  history: [
    {
      id: "hist-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-001",
      action: "created",
      channel: NOTIFICATION_CHANNELS.IN_APP,
      actorUserId: null,
      details: "Notification created from reservation.confirmed event",
      occurredAt: "2026-02-15T17:55:00.000Z",
    },
    {
      id: "hist-002",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-001",
      action: "delivered",
      channel: NOTIFICATION_CHANNELS.IN_APP,
      actorUserId: null,
      details: "Delivered to in-app inbox",
      occurredAt: "2026-02-15T18:00:00.000Z",
    },
    {
      id: "hist-003",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-003",
      action: "failed",
      channel: NOTIFICATION_CHANNELS.PUSH,
      actorUserId: null,
      details: "Delivery failed: Push token expired",
      occurredAt: NOW,
    },
    {
      id: "hist-004",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-003",
      action: "retried",
      channel: NOTIFICATION_CHANNELS.PUSH,
      actorUserId: null,
      details: "Retry attempt 2 queued",
      occurredAt: NOW,
    },
  ],
  rules: [
    {
      id: "rule-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: DEFAULT_NOTIFICATION_SCOPE.branchId,
      name: "Low Stock Alert Rule",
      eventSource: NOTIFICATION_EVENT_SOURCES.INVENTORY,
      eventKey: "inventory.low_stock",
      templateId: "tmpl-low-stock",
      channels: [NOTIFICATION_CHANNELS.EMAIL, NOTIFICATION_CHANNELS.IN_APP],
      scope: NOTIFICATION_SCOPES.BRANCH,
      targetRoleIds: ["role-manager", "role-owner"],
      isActive: true,
      conditions: { stockLevelBelow: "5" },
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: "rule-002",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: null,
      name: "Invoice Due Reminder",
      eventSource: NOTIFICATION_EVENT_SOURCES.BILLING,
      eventKey: "billing.invoice_due",
      templateId: "tmpl-billing-invoice",
      channels: [NOTIFICATION_CHANNELS.EMAIL],
      scope: NOTIFICATION_SCOPES.TENANT,
      targetRoleIds: ["role-owner"],
      isActive: true,
      conditions: { daysBeforeDue: "1" },
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],
  events: [
    {
      id: "evt-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: DEFAULT_NOTIFICATION_SCOPE.branchId,
      eventSource: NOTIFICATION_EVENT_SOURCES.RESERVATIONS,
      eventKey: "reservation.confirmed",
      payload: { reservationId: "res-001", partySize: "4", time: "19:00" },
      processedAt: "2026-02-15T17:55:00.000Z",
      ruleIds: [],
      occurredAt: "2026-02-15T17:55:00.000Z",
    },
    {
      id: "evt-002",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: DEFAULT_NOTIFICATION_SCOPE.branchId,
      eventSource: NOTIFICATION_EVENT_SOURCES.INVENTORY,
      eventKey: "inventory.low_stock",
      payload: { itemId: "inv-001", itemName: "Salmon fillet", stockLevel: "2" },
      processedAt: "2026-02-15T14:00:00.000Z",
      ruleIds: ["rule-001"],
      occurredAt: "2026-02-15T14:00:00.000Z",
    },
  ],
  schedules: [
    {
      id: "sched-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      notificationId: "notif-004",
      scheduleType: SCHEDULE_TYPES.ONCE,
      scheduledAt: "2026-02-16T09:00:00.000Z",
      cronExpression: null,
      timezone: "Europe/London",
      isActive: true,
      lastRunAt: null,
      nextRunAt: "2026-02-16T09:00:00.000Z",
      createdAt: NOW,
    },
  ],
  recipients: [
    {
      id: "recip-001",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      userId: DEFAULT_NOTIFICATION_SCOPE.userId,
      roleId: "role-owner",
      email: "owner@harbourkitchen.co.uk",
      phone: "+447700900456",
      pushToken: "fcm-token-001",
      slackUserId: null,
      preferredChannels: [NOTIFICATION_CHANNELS.EMAIL, NOTIFICATION_CHANNELS.IN_APP],
      scope: NOTIFICATION_SCOPES.BUSINESS,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: null,
    },
    {
      id: "recip-002",
      tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
      userId: "user-manager-001",
      roleId: "role-manager",
      email: "manager@harbourkitchen.co.uk",
      phone: "+447700900789",
      pushToken: "fcm-token-002",
      slackUserId: "U01234567",
      preferredChannels: [NOTIFICATION_CHANNELS.PUSH, NOTIFICATION_CHANNELS.SLACK],
      scope: NOTIFICATION_SCOPES.BRANCH,
      businessId: DEFAULT_NOTIFICATION_SCOPE.businessId,
      branchId: DEFAULT_NOTIFICATION_SCOPE.branchId,
    },
  ],
  analytics: {
    tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
    totalSent: 156,
    totalDelivered: 148,
    totalFailed: 8,
    totalRead: 112,
    deliveryRateBps: 9487,
    readRateBps: 7568,
    averageDeliveryTimeMs: 2340,
    channelBreakdown: [
      { channel: NOTIFICATION_CHANNELS.EMAIL, count: 68, deliveryRateBps: 9700 },
      { channel: NOTIFICATION_CHANNELS.IN_APP, count: 52, deliveryRateBps: 10000 },
      { channel: NOTIFICATION_CHANNELS.PUSH, count: 24, deliveryRateBps: 8750 },
      { channel: NOTIFICATION_CHANNELS.SMS, count: 12, deliveryRateBps: 9167 },
    ],
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
  },
  aiContext: {
    tenantId: DEFAULT_NOTIFICATION_SCOPE.tenantId,
    summary: "148/156 delivered — 1 unread, 1 failed push pending retry",
    unreadCount: 2,
    failedDeliveryCount: 1,
    recommendedChannel: NOTIFICATION_CHANNELS.IN_APP,
    optimalSendTime: "09:00",
    insights: [
      "In-app has 100% delivery rate this period",
      "Push failures correlate with expired tokens",
      "Email open rate highest at 9 AM",
    ],
    recommendedActions: [
      "Refresh push tokens for branch managers",
      "Enable Slack for kitchen alerts",
    ],
    lastGeneratedAt: NOW,
  },
};
