import { PERMISSION_CODES } from "@/modules/authorization/constants/permissions";

/** Notification permission aliases mapped to platform authorization codes. */
export const NOTIFICATION_MODULE_PERMISSIONS = {
  NOTIFICATION_READ: PERMISSION_CODES.NOTIFICATIONS_VIEW,
  NOTIFICATION_CREATE: PERMISSION_CODES.NOTIFICATIONS_MANAGE_TEMPLATES,
  NOTIFICATION_SEND: PERMISSION_CODES.NOTIFICATIONS_PUBLISH,
  NOTIFICATION_MANAGE: PERMISSION_CODES.NOTIFICATIONS_ADMIN,
} as const;

export type NotificationModulePermissionCode =
  (typeof NOTIFICATION_MODULE_PERMISSIONS)[keyof typeof NOTIFICATION_MODULE_PERMISSIONS];
